### ISSUE TITLE
No libraries are found, System, UnityEngine, UnityEditor, etc

### ISSUE THREAD

**Issue by joaomcarlos** [consulo/consulo-unity3d#10]
Hey.

I just found Consulo and wanted to try it out since I work heavily on Unity with MonoDevelop and I am losing my mind with that setup. I work on Javascript with Webstorm and Php with Phpstorm, so, I when I found Consulo its like I found the chalice of youth!

However, I am having problems getting my project to work correctly, namely it highlights stuff like UnityEditor, UnityEngine, and even System and Linq not being found.
It even highlights lines like bool doThis = true; stating that it can't convert System.Boolean to System.Boolean (weird shit).

There is a picture if the problem: 
http://puu.sh/gTU1T/44494f5719.png
And here is a picture of the solution (notice the paths):
http://puu.sh/gTUjU/a9c4d54c90.png

Maybe this info could be added to the bottom of the read me, it would have saved me 20 or so minutes since I didn't know where exactly was everything.

PS: Thank you for your awesome work.

**Comment by VISTALL** [comment]
Click pls Extensions -> Unity3D and show me it.

And open Bundles(the same dialog) and show me it too

**Comment by joaomcarlos** [comment]
Extensions : http://puu.sh/gTUDX/8a44090c98.png 
Bundles : http://puu.sh/gTUFc/6164de374a.png

PS: when I started the program and Imported the project the Unity SDK (whats this?) field was empty.

**Comment by VISTALL** [comment]
Select Unity3D in extensions tree

**Comment by joaomcarlos** [comment]
Extensions tree : http://puu.sh/gTUIL/c09052657f.png

**Comment by VISTALL** [comment]
U can view settings - click on Unity3D
![](http://klikr.org/992d87ce0062ee867c985de25909.png)

**Comment by joaomcarlos** [comment]
Right, mine looks different, default : http://puu.sh/gTUU8/4cd9423685.png
Dropdown : http://puu.sh/gTUUX/131b5aa653.png

**Comment by VISTALL** [comment]
And now - i saw the problem.

**SDK** selected **none**, select it name will be as in http://puu.sh/gTUFc/6164de374a.png

But u need select it for all modules. Strange - u import project, and dont selected SDK? Hm

![](http://klikr.org/b8db0a5ffb7c50422dd2e78d9893.png)

**I think need reimport project**

**Comment by joaomcarlos** [comment]
This is unrelated but, do you know how to change the auto-formatting of automatic properties?
Pic: http://puu.sh/gTWar/6b065a1c48.png

When using auto properties -> float Distance { get;set; } should be in the same line like I wrote and not like in the picture

**Comment by joaomcarlos** [comment]
On that picture, the Unity SDK field was empty.

Originally, I didn't have a Unity folder in my Applications folder, since I have multiple Unity versions I always rename them, like Unity4.6f3, Unity5f4, etc,etc. 

Since it wasn't finding the libraries, I decided to create a Unity folder and copy the contents of the Unity4.6f3 into it just in case. Maybe thats why the Unity SDK field was empty.

**Comment by VISTALL** [comment]
U can add own Unity SDKs, with different folders. For ex:

![](http://klikr.org/3ac623631551733fcdfc488fd65e.png)

Click **+** select Unity3d, and then choose Unity3D dir. And when u can choose it while import

Predefined bundles searching at default paths, for Unity(and on Mac) it 

```
/Applications/Unity/Unity.app
```

**Comment by VISTALL** [comment]
And u can - define two(or more) Unity SDKs, inside one project and switch it in one click(but it not an issue, it feature of consulo)

**Comment by joaomcarlos** [comment]
Maybe to avoid confusion with other people have the Import project form search the Applications folder for folders starting with Unity, and then if it finds, check if they are valid unity folders and add to the list.

That way, new people, who don't yet know everything about how to import and configure stuff in Consulo, can start using it straight away.

**Comment by VISTALL** [comment]
Predefined bundles - added while Consulo start, not at  import project and it not good reason to scan app dir(due we dont known max count of dirs, and dont forgot we have Windows too).

And for example u can move it to another dirs, not only app dir

Unity default install path is 

```
/Applications/Unity/Unity.app
```

If user is skilled - he can change path. If user is skilled he can write here, and get info :smiley: 

Main problem - nobody known(except me) how to setup Consulo.

Anyway - reimport helps? Can i close issue?

**Comment by joaomcarlos** [comment]
Reimport completely fixes the problem, don't even need to change anything or import anything.

Thank you.

PS: you can add those insights into the read me for the project.

**Comment by VISTALL** [comment]
Thanks

Maybe - but this is not feasible for me (it hard to me explain newbie questions).

Need good tutorial video(with voice and better content)

**Comment by vivekmishra161993** [comment]
For me too none of the unity imports are working on WIndows 10. Tried everything I can find about it but no luck

**Comment by VISTALL** [comment]
Hi. Can you use https://discuss.consulo.io ? Attach some screenshots, and how you created project, etc.

Thanks
