### ISSUE TITLE
Unity has issues if consulo is not running when the consulo plugin is installed

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo-unity3d#100]
It seems like the failure to connect to a running instance of consulo makes unity stutter/hang when the plugin is installed. I'd expect that it it should be possible to only work with the editor without having consulo running.

(Windows 10)

**Comment by VISTALL** [comment]
Hi. At what action unity hungs?

Thanks

**Comment by sfjohansson** [comment]
For instance when pressing play. Tested on an empty project and the issue appeared when there is Debug.Log output in the code, so if the plugin would attempt to forward these..then that could be it.

**Comment by VISTALL** [comment]
Reproduced

**Comment by VISTALL** [comment]
Unity 5.3 + ? Can you this build? 


[UnityEditorConsuloPlugin5.3.zip](https://github.com/consulo/consulo-unity3d/files/879253/UnityEditorConsuloPlugin5.3.zip)

**Comment by sfjohansson** [comment]
Great...that works... thanks for coming up with a fix so quick :)
