### ISSUE TITLE
Can't open project correclty

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#101]
<img width="1440" alt="screen shot 2017-03-20 at 12 13 00 pm" src="https://cloud.githubusercontent.com/assets/689092/24195795/76373462-0efb-11e7-85bf-9b2545507d06.png">

**Comment by VISTALL** [comment]
Hm. Looks like you have old broken consulo project. Try delete **.consulo* directory from root directory, and try again

Thanks you

**Comment by Selech** [comment]
I also get this error..
I have tried to delete the .consulo folder in the Unity Project's folder, but same thing happens. I have removed Consulo and settings multiple times, reinstalled the plugins and still same error. Following the guide (https://github.com/consulo/consulo-unity3d/wiki/1.-Setup-and-Usage) I'm not able to find / get the prompt about "Import project from external model", it simply opens Consulo with the project looking exactly like it the picture from original poster.

Is the guide up to date?

NOTE: I've used AppCleaner to remove additional files when removing Consulo.

**Comment by VISTALL** [comment]
Looks like not. Sorry. In Consulo 2 'Open' & 'Import from external model' was merged into one action - 'Open or import project'

**Comment by Selech** [comment]
Okay, thats fair, does "Open or import project" automatically see that it should open as a Unity project then?
It finds no modules when I use "Open or import project", and my settings are as follows:

<img width="427" alt="screen shot 2017-03-30 at 18 43 50" src="https://cloud.githubusercontent.com/assets/4905860/24515800/f3613e8c-1578-11e7-848a-c0f89140b29c.png">
<img width="420" alt="screen shot 2017-03-30 at 18 43 43" src="https://cloud.githubusercontent.com/assets/4905860/24515801/f3810780-1578-11e7-9875-07d2fd63ff45.png">

**Comment by Selech** [comment]
I just opened another project and it actually worked perfectly, until I removed it, and tried to import it again.. Are there some temp files stored somewhere?

**Comment by VISTALL** [comment]
Project files only stored in /.consulo dir inside root directory of unity project

**Comment by Selech** [comment]
Okay, I only get the "Import from Unity3D" prompt the first time I import a project, regardless of the .consulo folder in the Unity Project's folder. Also, it I remove everything about Consulo and try again from scratch, it stuff won't show the "Import from Unity3D" prompt the second time I try..

<img width="807" alt="screen shot 2017-03-30 at 19 21 24" src="https://cloud.githubusercontent.com/assets/4905860/24517325/1f182be4-157e-11e7-999c-32fed044d512.png">
 
If you have an idea, please let me know, I would like to try and use Consulo for a day or two.

I did try it briefly, and uninstalled, that why my main project won't work the second time, this bug seems like some kind of built in punishment for deleting the app and returning later ;)

**Comment by Selech** [comment]
Actually, to hack around this, I made a new project, opened it in Consulo and then in the "Import Project from Unity3D" prompt just pointed to the old (non-working) project's location, and BAM then it imports correctly!

**Comment by VISTALL** [comment]
Strange thing

**Comment by patrickoshaughnessey** [comment]
I am now seeing this exact frustrating behavior. I cannot seem to recreate my Unity project no matter what combination of destroying and re-installing Consulo and its plug-ins that I try.

**Comment by winxalex** [comment]
frustraing. deleting .consulo folder doesn't help

**Comment by VISTALL** [comment]
Can you write steps what u do, and show screenshots.

**Comment by winxalex** [comment]
I succeed by hack. Import some empty project. Then copy .consulo from that to problematic.

**Comment by winxalex** [comment]
<img width="777" alt="screen shot 2017-04-19 at 10 25 52 pm" src="https://cloud.githubusercontent.com/assets/689092/25200638/57d89df2-254f-11e7-996a-6e1eca40fd27.png">
I can't even delete there is no "X"

**Comment by VISTALL** [comment]
Problem exists with short name ?

**Comment by winxalex** [comment]
<img width="778" alt="screen shot 2017-04-19 at 10 29 16 pm" src="https://cloud.githubusercontent.com/assets/689092/25200752/be08c3e0-254f-11e7-80c1-6ef203b12a24.png">
No "X" on any of the items in list long short doesn't matter

**Comment by VISTALL** [comment]
TopTal project have 'X' ?

**Comment by winxalex** [comment]
no

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-04-19 at 10 34 45 pm" src="https://cloud.githubusercontent.com/assets/689092/25200948/82e14980-2550-11e7-96f7-af1debad9c8d.png">
 So this is the scenario how to recreate main problem. Import UnityProject. Then go to folder and delete .consulo dir. Try to import project again. It will load only solution and project files

**Comment by winxalex** [comment]
[consulo.zip](https://github.com/consulo/consulo-unity3d/files/938212/consulo.zip)
This are the recreated files

**Comment by VISTALL** [comment]
problem with recents move to https://github.com/consulo/consulo/issues/260

**Comment by VISTALL** [comment]
When you tried to open/import Unity project what icon you saw at directory ? (consulo icon or unity)

**Comment by winxalex** [comment]
I'm going thru welcome screen import and NO
<img width="1440" alt="screen shot 2017-04-19 at 10 43 40 pm" src="https://cloud.githubusercontent.com/assets/689092/25201399/e0e2e812-2551-11e7-9e79-924b2dc88d0d.png">
 unity icon on any of Unity Projects

**Comment by VISTALL** [comment]
Oh. Forgot, on MacOS we using native file chooser.

**Comment by VISTALL** [comment]
Close Consulo. Open Consulo.app (/Contents/) find consulo.vmoptions.

And add this line

```
-Dnative.mac.file.chooser.enabled=false
```

And open Consulo (and try again)

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-04-19 at 10 50 03 pm" src="https://cloud.githubusercontent.com/assets/689092/25201688/e49184d6-2552-11e7-8bd5-0f1b4bc13fdf.png"> Thru Modules choser shows Unity icon on the folder.
I'll try to add the line above.

**Comment by VISTALL** [comment]
You need select root directory (not sln file)

**Comment by winxalex** [comment]
No that was just to show you that Consulo know it is unity folder but doesn't import as such

**Comment by VISTALL** [comment]
When you select root Unity directory - it show dialog for SDK select ?

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-04-19 at 10 57 41 pm" src="https://cloud.githubusercontent.com/assets/689092/25201972/e941307a-2553-11e7-9cd6-29d1cc02ce23.png">

Both folders AnimatorControllerPlayableExample and OriginalFixed are unity but are shown with consulo icons.

**Comment by VISTALL** [comment]
(if project already imported - icon will be changed to consulo)

**Comment by winxalex** [comment]
Did you manage to reconstruct the issue as I told u?

**Comment by VISTALL** [comment]
![](http://klikr.org/87fefe9d1c00029fc14316a6b95e.gif)

NO .consulo dir. Project imported without problem

**Comment by VISTALL** [comment]
Maybe you had errors. Can you attach your idea.log

**Comment by winxalex** [comment]
It working now. Before we add vm options import project wasn't showing import unity popup(where u can select SDK) as shown in the gif. Now in chooser you have unity and consulo icons and import show Unity popup.

**Comment by winxalex** [comment]
Do this now. Don't delete project from the welcome screen. go and delete .consulo dir. Click on the welcome screen item in list not thru import. Bug happen again.

**Comment by winxalex** [comment]
Also you can do this. Normal Unity project >> Import. While Consulo is open, delete .consulo dir. Then Close project back to welcome screen. Try to import . BUG

**Comment by patrickoshaughnessey** [comment]
I am also seeing this same behavior, and it is very frustrating. I can no longer create new Unity projects.

**Comment by VISTALL** [comment]
Can you describe your problem? (better with screenshots)

Thanks

**Comment by patrickoshaughnessey** [comment]
Okay - I reinstalled Consulo, uninstalled all plugins, re-installed Unity plugin and its dependencies, deleted the .consulo project in my Unity folder, and then tried to re-create the project. This time, Consulo crashed after this step:

![image](https://user-images.githubusercontent.com/115180/28422677-65da5b1c-6d2e-11e7-905b-8deba1235b8f.png)

Here's the consulo.log:

2017-07-20 09:31:32,893 [ 122482]   INFO - ellij.project.impl.ProjectImpl - 95 project components initialized in 198 ms 
2017-07-20 09:31:32,894 [ 122483]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
2017-07-20 09:31:32,897 [ 122486]   WARN - impl.local.LocalFileSystemBase - Invalid path: file:///Users/poshaughnessey/dev/vrbots/vrbots/Unity/out 
2017-07-20 09:31:32,901 [ 122490]   INFO - i.vcs.changes.ChangeListWorker - default list not found when copy 
2017-07-20 09:31:32,901 [ 122490]   INFO - i.vcs.changes.ChangeListWorker - default list not found when copy in original object too 
2017-07-20 09:31:33,068 [ 122657]   INFO - i.vcs.changes.ChangeListWorker - default list not found when copy 
2017-07-20 09:31:33,068 [ 122657]   INFO - i.vcs.changes.ChangeListWorker - default list not found when copy in original object too 
2017-07-20 09:31:33,848 [ 123437]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 1ms; general responsiveness: ok; EDT responsiveness: ok 
2017-07-20 09:31:33,852 [ 123441]   INFO - tartup.impl.StartupManagerImpl - /Users/poshaughnessey/dev/vrbots/vrbots/Unity case-sensitivity: expected=false actual=false 
2017-07-20 09:31:34,018 [ 123607]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 169ms; general responsiveness: ok; EDT responsiveness: ok 
2017-07-20 09:31:34,020 [ 123609]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 212 files to update 
2017-07-20 09:31:34,159 [ 123748]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 1513 ms 
2017-07-20 09:31:35,073 [ 124662]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 1053ms; general responsiveness: ok; EDT responsiveness: ok 

And I've also attached the crash report.

[ConsuloCrash.txt](https://github.com/consulo/consulo-unity3d/files/1162621/ConsuloCrash.txt)

Here's the contents of the directory it created before it crashed:

![image](https://user-images.githubusercontent.com/115180/28422933-1d1e6c28-6d2f-11e7-8c5b-cd130204cb6c.png)

modules.xml:

![image](https://user-images.githubusercontent.com/115180/28422941-260cac82-6d2f-11e7-859f-d33047361b9b.png)

workspace.xml:

[workspace.xml.txt](https://github.com/consulo/consulo-unity3d/files/1162633/workspace.xml.txt)

profiles_settings.xml:

[profiles_settings.xml.txt](https://github.com/consulo/consulo-unity3d/files/1162635/profiles_settings.xml.txt)

Here's what the project looks like in Consulo:

![image](https://user-images.githubusercontent.com/115180/28423008-6b695b0e-6d2f-11e7-9050-05b54f26b37c.png)

**Comment by patrickoshaughnessey** [comment]
I tried manually creating the Unity module after the failed project creation, and that caused an exception in the Unity plugin:

https://hub.consulo.io/errorReport#d3d68d8a-bf23-4985-9bc9-53bc55297e0f

**Comment by VISTALL** [comment]
Can you dowload Consulo without JRE, and install Oracle JDK(if not installed, it will be notify at start) ?

**Comment by patrickoshaughnessey** [comment]
I tried Consulo without JRE, and also a fresh ~/Library/Preferences/Consulo. Same result - crash after project creation, and no Unity module created. Going to try a reboot, and see if that changes anything...

**Comment by VISTALL** [comment]
Can you show About information?

**Comment by patrickoshaughnessey** [comment]
![image](https://user-images.githubusercontent.com/115180/28425280-634b758c-6d35-11e7-98a7-bfc9dcda9034.png)

**Comment by patrickoshaughnessey** [comment]
Unity plugin version 2560

**Comment by patrickoshaughnessey** [comment]
Okay - so, a reboot seems to have fixed things up. I guess there was a memory violation happening?

**Comment by VISTALL** [comment]
You changed JDK - looks like JetBrains JDK bug
