### ISSUE TITLE
Consulo plugin seems to crash editor when entering playmode

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo-unity3d#102]
The version of the consulo plugin that solves the issues with unity hanging when consulo is not running in the background seems to make the editor crash frequently. 

The last output I get in the unity editor log is:

Refresh: detecting if any assets need to be imported or removed ... Refresh: elapses 0.101189 seconds (Nothing changed)
Refresh: detecting if any assets need to be imported or removed ... Refresh: elapses 0.098903 seconds (Nothing changed)

Packing sprites:
- Repacking is not required. Check took 18.473989 ms.
[VRDevice] Successfully created device Oculus.
Reloading assemblies for play mode.
Begin MonoManager ReloadAssembly

**Comment by VISTALL** [comment]
Strange. It's crashed without Unity Error Reporting ?
