### ISSUE TITLE
Fails To Resolve Oculus unity Package classes

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo-unity3d#103]
Seems like it fails to resolve scripts that are part of the Oculus VR Downloads

[https://developer.oculus.com/downloads/unity/](url)

![failed resolve](https://cloud.githubusercontent.com/assets/912814/24959501/e6dcf34c-1f8a-11e7-937c-7e6a52532075.PNG)

They work fine in other IDE's

**Comment by VISTALL** [comment]
Hm. I'ill download, and test.

Thanks

**Comment by VISTALL** [comment]
You download **Oculus Utilities for Unity 5 1.13.0** ?

**Comment by sfjohansson** [comment]
Updated a few days ago... structure of classes should be pretty much the same.
I'm using these two but probably good idea to try the bunch
https://developer.oculus.com/downloads/package/oculus-utilities-for-unity-5/
https://developer.oculus.com/downloads/package/oculus-platform-sdk/

**Comment by VISTALL** [comment]
Looks like - you need reimport project after adding **unitypackage**

![](http://klikr.org/52f98db0bac3637e1d6ff47fea3d.png)

**Comment by sfjohansson** [comment]
Let me try..Is there menu item for doing it as the file dialog is using a combo ( open or reimport)?

**Comment by VISTALL** [comment]
Menu item in context menu on root directory

**Comment by sfjohansson** [comment]
Ahh there it is...thank you that did... had a horrible afternoon having to use monodevelop... reminds me of the time before I discovered Consulo

**Comment by VISTALL** [comment]
:) np

Thanks

**Comment by VISTALL** [comment]
ref https://github.com/consulo/consulo-unity3d/issues/45
