### ISSUE TITLE
Missing .dll from Standard libs (UnityEngine.Timeline)

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#104]
<img width="1440" alt="screen shot 2017-04-19 at 11 41 49 pm" src="https://cloud.githubusercontent.com/assets/689092/25203551/eafad816-2559-11e7-8f93-f0ca7328ad79.png">
<img width="1440" alt="screen shot 2017-04-19 at 11 40 45 pm" src="https://cloud.githubusercontent.com/assets/689092/25203580/03d41794-255a-11e7-8afd-072b43b52bc8.png">
<img width="1440" alt="screen shot 2017-04-19 at 11 44 08 pm" src="https://cloud.githubusercontent.com/assets/689092/25203614/2589cce4-255a-11e7-88b7-bd150c38b893.png">

**Comment by VISTALL** [comment]
It's new Unity ? looks like no suppor for it

**Comment by winxalex** [comment]
Last beta? but shouldn't be diff?

**Comment by VISTALL** [comment]
Unity have different libraries in different paths.

Consulo have logic for adding on each version

https://github.com/consulo/consulo-unity3d/blob/master/src/consulo/unity3d/projectImport/Unity3dProjectUtil.java#L386

Looks like its a new library without support

**Comment by winxalex** [comment]
do u scanning UnityExtensions folder?

**Comment by VISTALL** [comment]
It's not scan - it add known library with known name. Sometime ago unity had different paths for extensions.

I will add this library maybe today

**Comment by VISTALL** [comment]
Pushed last build to release channel.
