### ISSUE TITLE
Add Watch doesn't show (Variable do)

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#105]
<img width="1440" alt="screen shot 2017-04-30 at 5 35 45 pm" src="https://cloud.githubusercontent.com/assets/689092/25565666/aeb3a052-2dcb-11e7-9bce-789073857e8a.png">
<img width="1440" alt="screen shot 2017-04-30 at 5 35 49 pm" src="https://cloud.githubusercontent.com/assets/689092/25565667/b47337e6-2dcb-11e7-8441-c8fae2954468.png">

**Comment by VISTALL** [comment]
Hi. Can give me some more information ? Not understand

**Comment by winxalex** [comment]
Variables show value of joint.connectedBody (Joint is ConfigurableJoint) and watch doesn't show(can't calc)

**Comment by VISTALL** [comment]
Can you show declaration(all call nodes)? (due it's based on AST tree)

**Comment by VISTALL** [comment]
Reproduced
![](http://klikr.org/55508fdc5b641e3217c6a8db7cd3.png)

**Comment by winxalex** [comment]
You should add Configurable joint as Component. Menu “ADD” or gameObject.AddComponent<ConfigurableJoint>()

Not thru “new”. I’m seeing is joint is null.

**Comment by VISTALL** [comment]
It's work anyway (yeh me not Unity developer)

**Comment by VISTALL** [comment]
this is complex issue, working on it. Added throw info inside debugger

![](http://klikr.org/92f74c98c6ea6f2c2b861cbaf40f.png)

**Comment by VISTALL** [comment]
Fixed in last builds of C#/.NET (u can test it in nightly channel or wait sometime for it)
