### ISSUE TITLE
Found error in comment

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#106]
<img width="1440" alt="screen shot 2017-05-07 at 6 14 19 pm" src="https://cloud.githubusercontent.com/assets/689092/25782778/20215830-3351-11e7-8753-e7a0c089d948.png">

**Comment by VISTALL** [comment]
Hi. Props is nested type?

**Comment by winxalex** [comment]
Yes. But why is reading comment?

**Comment by VISTALL** [comment]
It's parsing reference for navigation + rename handling.

In most cases - grammar for it is default as in C#. That case - is special for nested types (looks like)

**Comment by VISTALL** [comment]
$moveto consulo-csharp
