### ISSUE TITLE
Move statement up command doesn't work

### ISSUE THREAD

**Issue by temporaryna** [consulo/consulo-unity3d#107]
Move statement up command doesn't work
it should move all statement but moves just 1 line
![image](https://cloud.githubusercontent.com/assets/712775/25945039/2d821cc6-364e-11e7-823e-711e919928fc.png)
![image](https://cloud.githubusercontent.com/assets/712775/25945057/3d74ba80-364e-11e7-9fe2-725e66ff2ea3.png)

**Comment by VISTALL** [comment]
#moveto consulo-csharp

**Comment by VISTALL** [comment]
$moveto consulo-csharp
