### ISSUE TITLE
Consulo only recognize UNITY_EDITOR define constants.

### ISSUE THREAD

**Issue by potterdai** [consulo/consulo-unity3d#108]
Consulo only recognize UNITY_EDITOR define constants.
UNITY_ANDROID, UNITY_IOS, etc. those constants are not recognized and considered undefined, even tried re-importing unity project.

**Comment by VISTALL** [comment]
Hi. You got message like "UnityEditor is not responding" ? Can you start UnityEditor(with this plugin https://github.com/consulo/UnityEditorConsuloPlugin), and call Reimport again.

Thanks

**Comment by potterdai** [comment]
Hmmmm, everything seems normal.

Just if I put

#if UNITY_IOS
.......codes....
#endif

Those codes within won't be recognized by Consulo.

**Comment by VISTALL** [comment]
Can you check what variables defined?  (File -> Project Structure -> select root module -> Extensions -> Unity3D)

![](http://klikr.org/b2d065bbcd05d4fadb6dc82149ba.png)

**Comment by potterdai** [comment]
Aha, this is the place to set it up. =)

it's only
UNITY_EDITOR
DEBUG
TRACE
I did install the UnityEditorConsuloPlugin5.3.dll into my unity folder.

Is there any reason the constants are not sync with Consulo settings?

**Comment by VISTALL** [comment]
>> Is there any reason the constants are not sync with Consulo settings?

There no good way to resolve **defines** from Unity (due project created outside Unity, we do not use **.sln** files - they are very limited, Consulo need more information about project files, and no API for fetching them).

If you Re-Import with plugin, you will get list like this: 

![](http://klikr.org/c74d5e366076d646bd933bf2bf8b.gif)

**Comment by VISTALL** [comment]
>> Aha, this is the place to set it up. =)

You can, but - every Re-import will restore defaults. Mutability is more defect, than feature

**Comment by potterdai** [comment]
I see, thank you for clarify this.
This is really strange, I put the plugin into the editor folder, and re-import the entire project (Both in Unity3D and Consulo). I cannot get the constant list as shown above.
I'm using Unity 5.6.1.

**Comment by VISTALL** [comment]
Hm. Strange. UnityEditor is opened?

**Comment by potterdai** [comment]
Yep, it's opened, and app path is correctly defined in Consulo...

**Comment by potterdai** [comment]
I just used the source code from UnityEditorConsuloPlugin instead of compiled dll.
Now it imports successfully.
Thank you for the great tool you have written! = )
For now I think I will just directly use the source code.

**Comment by VISTALL** [comment]
Hm... That really strange.

I will rebuild binaries tomorrow. And check again

Thanks you.

**Comment by NIA** [comment]
The colleague of mine just installed latest release Consulo build (`#2010 built on April 18`) and has same problem with fetching preprocessor defines from Unity into Consulo. I guided him to make the aforementioned steps
- manually place dll from https://github.com/consulo/UnityEditorConsuloPlugin into Assets/Editor/Plugins
- reopen Unity and Consulo
- press Reimport on UnityEditorConsuloPlugin2017.2.dll in Unity

But still there are only UNITY_EDITOR, DEBUG and TRACE in the Preprocessor variables list. Althouth the warning about _UnityEditor is not responding_ disappeared after doing the steps above and I expected that Unity and Consulo finally managed to communicate to each other.

Also clicking on a file in Project tab in Unity does not open it in Consulo, even though he configured it in Edit→Preferences→External tools. Nothing just happens.

The version of Unity is **2017.3.1f1**

**Comment by VISTALL** [comment]
can we go to https://discuss.consulo.io/c/net/unity? :)

Thanks
