### ISSUE TITLE
Lacking "IgnoreDataMemberAttribute"

### ISSUE THREAD

**Issue by potterdai** [consulo/consulo-unity3d#109]
Can I change the .net version from 3.5 to 3.5 SP1 ?
There are some attributes lacking in current version of .NET like "IgnoreDataMemberAttribute".

https://msdn.microsoft.com/en-us/library/system.runtime.serialization.ignoredatamemberattribute(v=vs.90).aspx

**Comment by VISTALL** [comment]
Looks like it's only bug with project import. Library **System.Runtime.Serialization** is not added.

For now you can add manually. File -> Project Structure -> |correct module, like Assembly-CSharp| -> Depedencies -> |+| -> Standard Library -> select **System.Runtime.Serialization**. I will fix it at midday.

**Comment by potterdai** [comment]
Yep, that solves the problem! Thank you for the help!

**Comment by VISTALL** [comment]
Thanks

**Comment by VISTALL** [comment]
Fixed. Now (re-)import will add this library to dependencies.

Thanks you
