### ISSUE TITLE
MacOSX: After building new executable, it can't open it 

### ISSUE THREAD

**Issue by joaomcarlos** [consulo/consulo-unity3d#11]
---

15:53:17 Compilation completed successfully in 1 min 2 sec
15:53:17 Error running BuildMacOSX64: /Users/silent/Documents/Dropbox/Development/Unity/TSW Unity4.6 Test/out/production/Assembly-CSharp/TSW.app/Contents/MacOS/TSW is not exists

---

http://puu.sh/gU6I9/ea97719926.png
http://puu.sh/gU6Fc/32f9eac807.png

**Comment by joaomcarlos** [comment]
Oh, and if I don't replace the module name manually, I get this:

---

15:49:33 Compilation completed successfully in 59 sec
15:49:33 Error running TSW Unity4.6 Test: /Users/silent/Documents/Dropbox/Development/Unity/TSW Unity4.6 Test/out/production/TSW Unity4.6 Test/$ModuleName$.exe/Contents/MacOS/$ModuleName$ is not exists

---

**Comment by VISTALL** [comment]
I think it duplicate https://github.com/consulo/consulo-unity3d/issues/4  but on MacOS

I known this bug - but i cant reproduce it

**Comment by VISTALL** [comment]
I think - i will done https://github.com/consulo/consulo-unity3d/issues/8 this issue - and u will test again.

Sorry for that - for now u can only run inside Unity Editor:(

**Comment by joaomcarlos** [comment]
It creates the file perfectly, just doesn't run it.
If you run the .app file, macosx will trigger everything needed to open the sub-file, thats how executables work in macosx.

**Comment by VISTALL** [comment]
I already have some hack for MacOS - but u found case when it not works

https://github.com/consulo/consulo-unity3d/blob/master/src/org/mustbe/consulo/unity3d/module/Unity3dModuleExtension.java#L233

**Comment by VISTALL** [comment]
Me closed #8 - later update Unity3d plugin(and consulo - npe fix), reimport project and try compile and run. Create new issue if need
