### ISSUE TITLE
Are you ready for C#6 in Unity3D

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#110]
https://forum.unity3d.com/threads/upgraded-mono-net-in-editor-on-5-5-0b9.438359/#n43

What changes will involve in consulo this change .NET 4.6 ???

**Comment by VISTALL** [comment]
Hi.

C# 6 is supported. If used Unity highter that 5.5.0 - C# 6 is default lang version

But default .NET framework is 2.0. 

I will check how handle framework change.

Thanks

**Comment by VISTALL** [comment]
As i saw. They used libraries from Unity 5.5.0b9\Editor\Data\Mono\lib\mono\2.0  - no matter what.

Looks like it's not .NET 2.0. Just  historic name
