### ISSUE TITLE
Clicking Install missing Unity plugin  doesn't seem to work on PC

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo-unity3d#111]
I get the popup to install the unity plugin when I open a project that does not have it.  When I do click "Install" the dialog gets dismissed but no plugin seems to get installed inside the unity project.

**Comment by CaiusPeng** [comment]
I also found it last week!



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
由： sfjohansson <notifications@github.com>
日期: 2017/6/15 17:42 (GMT+08:00)
收件人： consulo/consulo-unity3d <consulo-unity3d@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [consulo/consulo-unity3d] Clicking Install missing Unity plugin doesn't seem to work on PC (#111)


I get the popup to install the unity plugin when I open a project that does not have it. When I do click "Install" the dialog gets dismissed but no plugin seems to get installed inside the unity project.

―

**Comment by VISTALL** [comment]
Hi guys. Fixed. Sorry - i missed that.

Thanks.
