### ISSUE TITLE
Not hiding/closing popups Mac (CMD+SHIFT+N) 

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#117]
<img width="1440" alt="screen shot 2017-09-15 at 6 37 56 pm" src="https://user-images.githubusercontent.com/689092/30493621-1bf6b5d8-9a45-11e7-9924-85a727c34e8c.png">

**Comment by VISTALL** [comment]
Omg. Escape helps? Can you show about info?

**Comment by winxalex** [comment]
Escape or CMD W can't close it. Only close of Consulo

**Comment by VISTALL** [comment]
I need JDK information for test :)

**Comment by winxalex** [comment]
1.8.0_152 release

**Comment by VISTALL** [comment]
And escape help? (or popup is not closable)

**Comment by VISTALL** [comment]
JB build or Oracle?

**Comment by winxalex** [comment]
JDK no other info

**Comment by VISTALL** [comment]
![](http://klikr.org/032c25951c4037c2b77a87e0d6a4.png)

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-09-15 at 7 08 03 pm" src="https://user-images.githubusercontent.com/689092/30494634-3a4630c8-9a49-11e7-9a42-9a3dfc2d8fed.png">

**Comment by winxalex** [comment]
see the file how many errors has
Unity doesn't show not one
