### ISSUE TITLE
Slow type complete

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#118]
I have very powerful mac and when I type I"m waiting waiting to complete variable name

**Comment by VISTALL** [comment]
How big your project? 

Can you attach thread dumps, and logs? (About -> show log in finder)

And how big delay?

**Comment by winxalex** [comment]
100 or 200 max C1 haven't problem and some C2 until this new taking 1.5GB Wow

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-09-15 at 6 55 12 pm" src="https://user-images.githubusercontent.com/689092/30494201-7509866c-9a47-11e7-8d4e-c2d0ec937fa0.png">
File have 1600 lines. It was very fast in prev versions

**Comment by VISTALL** [comment]
Prev? How old? C# plugin had only few changes in last month (maybe unity changes broke it)

**Comment by VISTALL** [comment]
I added some cache for unity markers - test it after update Unity plugin build 2909 +

**Comment by VISTALL** [comment]
I think i found this problem - fixed in new builds
