### ISSUE TITLE
Property autocompliting suggest on object doesn't work

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#119]
<img width="1440" alt="screen shot 2017-09-15 at 6 42 17 pm" src="https://user-images.githubusercontent.com/689092/30493768-c850cb34-9a45-11e7-9e3c-7aa25023667b.png">
[Interpolator.txt](https://github.com/consulo/consulo-unity3d/files/1307027/Interpolator.txt)
This shit doesn't support .cs

**Comment by winxalex** [comment]
struct is inside class defined as you can see

**Comment by VISTALL** [comment]
Oh. I known about this issue (https://github.com/consulo/consulo-csharp/issues/464) ,for now i have no idea how fix it, without any problems

Thanks, sorry
