### ISSUE TITLE
Why consulo takes 1.5 GB memory ???

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#120]

**Comment by VISTALL** [comment]
C# plugin is not very optimized vs other plugins. But looks like (after reading other your issues)  - it's a breaking change in last month ?

**Comment by winxalex** [comment]
This issue is should be Consulo IDE 2.2GB its crazy. Not one program is at least near, Unity ...,or event InteliJ, you doing something wrong def.
<img width="1440" alt="screen shot 2017-09-24 at 5 12 13 pm" src="https://user-images.githubusercontent.com/689092/30783933-ea181a8a-a14b-11e7-9a6e-6f0616ea6ddd.png">

**Comment by VISTALL** [comment]
Can you enable Memory Bar ? (Preferences -> General -> UI -> Window Options -> Show Memory indicator) ?

Maybe you can set smaller limit, if not all memory used (on mac memory limited ~ 1.5 gb)

**Comment by winxalex** [comment]
there is no such option or I coldn't find it
<img width="1440" alt="screen shot 2017-09-24 at 5 24 36 pm" src="https://user-images.githubusercontent.com/689092/30784028-6d59840a-a14d-11e7-880e-933d36c475b5.png">
It starts with 1.5/6GB and increase overtime. Maybe also cos pop up search windows. I need to close IDE from time to time.Hell.

**Comment by VISTALL** [comment]
![](http://klikr.org/2ae0e7549e03e9ece6b6d779377d.png)

**Comment by winxalex** [comment]
<img width="193" alt="screen shot 2017-09-25 at 10 55 50 am" src="https://user-images.githubusercontent.com/689092/30800459-5a22ef96-a1e0-11e7-969e-5237a47b2418.png">
Still you allocating alot and by doing that no other app can use it. Ration is like 1:10. If app used 100MB you allocate 10x 1.5GB. Even Photoshop gives u option to setup allocation. Why not automatic allocation when needed and if static not more then 2x-3x which is still much much less.

**Comment by VISTALL** [comment]
It's problem (or not) of Java Runtime, need set max memory value . I change this value from 786m to 1.5g since C# analysis had problem with memory consumption

You can change it here
> Consulo.app\Contents\consulo.vmoptions

Thanks

**Comment by VISTALL** [comment]
Last .NET chain must be more cleaner. I loaded project with 4k C# files(and called completion) in 500mb ram. 

Test it!
