### ISSUE TITLE
Reporting Not existing errors

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#121]
[Archive.zip](https://github.com/consulo/consulo-unity3d/files/1307421/Archive.zip)
<img width="1440" alt="screen shot 2017-09-15 at 6 57 22 pm" src="https://user-images.githubusercontent.com/689092/30494338-fb75b662-9a47-11e7-9f40-1270fd38775b.png">

I've one file and from beginning using consulo never got without syntax error (not existing)

Example attached No Unity Code at all. Showing 3 errors . Doesn't like IList

**Comment by VISTALL** [comment]
Can you show method declaration? Looks like it's duplication of https://github.com/consulo/consulo-csharp/issues/476

It's blinking bug - not reproducable for me.

Thanks

**Comment by winxalex** [comment]
We need to solve that Generics problems one for all time

**Comment by winalex** [comment]
[Editor.zip](https://github.com/consulo/consulo-unity3d/files/1307093/Editor.zip)
I'm sending you the zip. Pls remove it when you take it.

**Comment by VISTALL** [comment]
dropped. I will test maybe tomorrow

Thanks

**Comment by winxalex** [comment]
put in assets folder of unity project. Shouldn't work in full but should work to degree you extract what you need. EditorGUILayoutEx.cs is most problematic

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-09-15 at 7 16 40 pm" src="https://user-images.githubusercontent.com/689092/30495026-9f7ba2c4-9a4a-11e7-8869-a8ca982eebd1.png">
Example
[TestIListToArray.cs.zip](https://github.com/consulo/consulo-unity3d/files/1307457/TestIListToArray.cs.zip)

<img width="1440" alt="screen shot 2017-09-15 at 8 39 29 pm" src="https://user-images.githubusercontent.com/689092/30498336-8fc31252-9a56-11e7-9482-531a2d8a3372.png">
You can remove UnityEngine and everything and can see that IList is the problem

**Comment by VISTALL** [comment]
>> We need to solve that Generics problems one for all time

Yeah. I hate this bug, but it's blinking. It's apear in big projects - and don't known how reproduce in small example. (due i don't known problem)

**Comment by winxalex** [comment]
IList and I'm sending the []  which is implementing IList

**Comment by VISTALL** [comment]
It's the same problem. Resolver can't find <T> from IList :(

**Comment by winalex** [comment]
why is that happen. Let me eat something be back in 15min and make you some example if you can't see from Editor.zip

**Comment by winalex** [comment]
I'm back

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-09-15 at 7 38 23 pm" src="https://user-images.githubusercontent.com/689092/30495742-7e71270e-9a4d-11e7-9160-e8340d1ddc5f.png">
[Utility.cs.zip](https://github.com/consulo/consulo-unity3d/files/1307165/Utility.cs.zip)
This file doesn't depend of Unity stuff

**Comment by VISTALL** [comment]
Looks like i can reproduce this example.

Thanks! I'll play with debug

**Comment by VISTALL** [comment]
```csharp
using System;
using System.Collections.Generic;
using System.Linq;

namespace A {
	public class SwitchUtility {
		public static Func<Type, T> Switch<T>(IList<Func<Type, T>> cases) {
			return o =>
			{
				var @case = cases
				.Select(f => f(o))
				.FirstOrDefault(a => a != null);


				return @case;
			};
		}
	}
}

```

**Comment by winxalex** [comment]
GOOD!

**Comment by winxalex** [comment]
Did you saw I made you small examples for everything?

**Comment by VISTALL** [comment]
yeah. i will test it after sleep

**Comment by VISTALL** [comment]
When i played with this issue - i found some strange error (when **f** is not resolved)

And simplified this test

![](http://klikr.org/f7a8a17e8ae5f306fd1015d90c17.png)

**Comment by winxalex** [comment]
I notice that eveything involving IList, Array, IEnumerable  C# compiler have big difficulties. Could you recreated from other examples that I supplied above?

**Comment by VISTALL** [comment]
It's problem with deep generic resolving.

https://github.com/consulo/consulo-csharp/issues/307

I forgot about this issue - need return to it.
