### ISSUE TITLE
When Event is subclassed from UnityEvent<any class> AddListner showing not existing  error

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#122]
<img width="1440" alt="screen shot 2017-09-15 at 8 01 01 pm" src="https://user-images.githubusercontent.com/689092/30496765-ba6ac5b4-9a50-11e7-89c1-1ca966a88091.png">
[Archive.zip](https://github.com/consulo/consulo-unity3d/files/1307244/Archive.zip)

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-09-15 at 7 59 55 pm" src="https://user-images.githubusercontent.com/689092/30496696-848dc176-9a50-11e7-9fc7-5d9f71ce7526.png">
<img width="1440" alt="screen shot 2017-09-15 at 8 00 02 pm" src="https://user-images.githubusercontent.com/689092/30496698-8624e8ca-9a50-11e7-844d-bbfb806850d6.png">

**Comment by VISTALL** [comment]
No luck

![](http://klikr.org/8638db9bc59d3d060fae25dba3b8.png)

Lokks like it's part of https://github.com/consulo/consulo-csharp/issues/483

**Comment by winxalex** [comment]
How your MyEvent looks like? Should be MyEvent:UnityEvent<ScriptableObject>

**Comment by VISTALL** [comment]
Yeah as you attached

```csharp
using UnityEngine;
using UnityEngine.Events;

public class MyEvent:UnityEvent<ScriptableObject> {

}
```
