### ISSUE TITLE
Showing $locvar to show local var in Debug variables

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#123]
If I type name of local var doesn't show value. I can see the local var inside
$locvar->
             mylocalvar

**Comment by VISTALL** [comment]
Hi. Can you provide some screenshots, etc. I have no idea - about what you talking about.

Thanks

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2017-09-18 at 7 33 06 pm" src="https://user-images.githubusercontent.com/689092/30589596-5b87f7c2-9d3b-11e7-99ac-7b6fe3b9e1db.png">
1) unityFieldName in watch have no value
2)Local value haven't display its value in IDE even already debug step have pass that point.

**Comment by winxalex** [comment]
💃

**Comment by VISTALL** [comment]
Hmm. This is the first time I see logic like this

**Comment by VISTALL** [comment]
Reproduced


![](http://klikr.org/2021d6b19db710a48416095bf1c5.png)

**Comment by winxalex** [comment]
add 'a" to watch list would give you .....

**Comment by VISTALL** [comment]
Yeah. It's due no local variable **a** in stackframe (it's wrapped in another object)

**Comment by VISTALL** [comment]
MS compiler

![](http://klikr.org/89b5a14002962d80ccc18166160e.png)

**Comment by VISTALL** [comment]
Roslyn
![](http://klikr.org/52e3cbe878053be843d9bcb28d29.png)

**Comment by VISTALL** [comment]
Now debugger handle this value correctly.

C# evaluator in progress

**Comment by VISTALL** [comment]
Fixed! 

Thanks
