### ISSUE TITLE
Search show first __ instead of letter that I've typed

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#124]
<img width="1440" alt="screen shot 2017-09-19 at 1 01 20 pm" src="https://user-images.githubusercontent.com/689092/30589523-17f18b68-9d3b-11e7-8a85-714a5f752ebb.png">

**Comment by VISTALL** [comment]
as expected

### java
![](http://klikr.org/5abe14ab7a4c93c48162353a8f57.gif)

## # csharp

![](http://klikr.org/0f8f1a0a90d3e0e4336564bbe4a1.gif)
