### ISSUE TITLE
Just inspect any game object you will see empty props = (nothing)

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#126]
<img width="1440" alt="screen shot 2017-09-29 at 12 55 18 pm" src="https://user-images.githubusercontent.com/689092/31163356-5a6aba52-a8e2-11e7-86c1-fa8eadeaf9b7.png">

**Comment by VISTALL** [comment]
Some of those values are "throwed exceptions" - but they handled by debugger (like System.NotSupportedException)

**Comment by VISTALL** [comment]
I will update it, and now you will get errors like this 

![](http://klikr.org/b0de8a233d9e4b196b19d5c831ae.png)

Thanks
