### ISSUE TITLE
Plugin manager shows no available plugins in Consulo #1862, and Unity missing in #1872

### ISSUE THREAD

**Issue by patrickoshaughnessey** [consulo/consulo-unity3d#127]

**Comment by VISTALL** [comment]
Hi. One moment

**Comment by VISTALL** [comment]
It's this https://github.com/consulo/hub.consulo.io/issues/19  need something todo with that.

I'm pushed last builds to release channel, after new minutes - need update Consulo

Sorry

**Comment by VISTALL** [comment]
Done. Consulo 1874 now have all plugins.

Sorry.
