### ISSUE TITLE
Problems with Unity 2017.2's Ads & IAP libs

### ISSUE THREAD

**Issue by TeorikDeli** [consulo/consulo-unity3d#129]
Hi!

Consulo (up-to-date version) cannot find declarations for Unity Ads & Purchases after I update Unity to 2017.2. When I downgrade to 2017.1.2, everything works fine. But I have to use 2017.2 =) I attached some screenshots from Consulo.

Ads & IAP working proper on Unity. I also checked on MonoDevelop to see if it has the same problem, it can find declarations and I can use code completion. So, I think the problem is Consulo & Unity 2017.2.

By the way, I also tried with an empty project.

<img width="778" alt="ekran resmi 2017-10-20 19 00 27" src="https://user-images.githubusercontent.com/9395555/31831109-f60b0a8a-b5ca-11e7-8a4c-cd0430408dd5.png">
<img width="708" alt="ekran resmi 2017-10-20 19 00 50" src="https://user-images.githubusercontent.com/9395555/31831118-fe7cbd62-b5ca-11e7-976b-a88890fb4496.png">
<img width="570" alt="ekran resmi 2017-10-20 19 01 19" src="https://user-images.githubusercontent.com/9395555/31831124-02d2e706-b5cb-11e7-8776-520bc4577ad3.png">
<img width="335" alt="ekran resmi 2017-10-20 19 17 11" src="https://user-images.githubusercontent.com/9395555/31831207-4dc0e3c6-b5cb-11e7-8795-fc42bf0873d6.png">

**Comment by VISTALL** [comment]
Hi. Looks like they changed library paths. I will check 

Thanks

**Comment by VISTALL** [comment]
><HintPath>C:/Users/VISTALL/AppData/LocalLow/Unity/cache/packages/packages.unity.com/com.unity.analytics@1.0.1/UnityEngine.Analytics.dll</HintPath>

what the heck?

Unity again changed library paths. I will add support for that in near future (nightly channel busy for some rework)

Thanks

**Comment by VISTALL** [comment]
note for me:

>/Users/vistall/Library/Unity/cache/packages/packages.unity.com/com.unity.analytics@1.0.1/UnityEngine.Analytics.dll

mac

**Comment by VISTALL** [comment]
> /home/vistall/.config/unity3d/cache/packages/packages.unity.com/com.unity.analytics@1.0.1/UnityEngine.Analytics.dll

Linux

**Comment by VISTALL** [comment]
Fixed in nighlty channel

**Comment by VISTALL** [comment]
You can switch to it (https://github.com/consulo/consulo/wiki/Update-channels)

But be carefull nightly stable for this week (after update - go back to release channel)

Thanks

**Comment by TeorikDeli** [comment]
Wouw! Thank you! 🤘🏻
