### ISSUE TITLE
Can't explicitly convert to object (Not exisitng bug)

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#132]
<img width="1440" alt="screen shot 2017-11-07 at 1 00 35 pm" src="https://user-images.githubusercontent.com/689092/32493778-62ec86e0-c3bf-11e7-953c-63d814defa86.png">

**Comment by VISTALL** [comment]
Hi.

Can you say C# your version plugin build ? 

Thanks

**Comment by VISTALL** [comment]
Can you check it after plugin update?

**Comment by winxalex** [comment]
Fixed

**Comment by winxalex** [comment]
Only not used argument after update

**Comment by VISTALL** [comment]
Can you close outdated issue ?
