### ISSUE TITLE
Not existing class overlaping

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#134]
<img width="1440" alt="screen shot 2017-11-07 at 12 58 27 pm" src="https://user-images.githubusercontent.com/689092/32493819-8ec814e6-c3bf-11e7-819e-1d9d0d405071.png">

Unity have same class in UnityEngine.Events but shouldn't be a problem cos diffrent namespace

**Comment by VISTALL** [comment]
Hi. It's was fixed. Can you update to last nightly build ? 

Thanks

**Comment by winxalex** [comment]
Its fixed
