### ISSUE TITLE
Auto complete don't work when name starts @keyword

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#135]
<img width="1440" alt="screen shot 2017-11-07 at 1 54 32 pm" src="https://user-images.githubusercontent.com/689092/32494766-38dac8d6-c3c3-11e7-9d05-fa624610bdb1.png">

**Comment by VISTALL** [comment]
Hi. I will check it after **unused** problem.

Can you report next time in C# repository ( https://github.com/consulo/consulo-csharp) due it's independent issue. (not related to unity)

Thanks

**Comment by winxalex** [comment]
How can I move?

**Comment by VISTALL** [comment]
You can't (github too). It's ok, but harder view open C# issues.

**Comment by winxalex** [comment]
have u included UnityEditor.Graphs seem like not doing auto complete

**Comment by VISTALL** [comment]
I catched error. Pushed fix.
