### ISSUE TITLE
Debug point is checked before play and "X" when I click play

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#136]
<img width="1440" alt="screen shot 2017-11-09 at 4 15 35 pm" src="https://user-images.githubusercontent.com/689092/32612750-59e2fe66-c569-11e7-9652-a9326e4f1e9b.png">
<img width="1440" alt="screen shot 2017-11-09 at 4 15 47 pm" src="https://user-images.githubusercontent.com/689092/32612745-5795d17e-c569-11e7-9b6a-a5984d4a3892.png">

Also there is substential wait of debug points to show check state after Debug is clicked. I'm focusing every time Unity then back to consulo to see if Debug point show checked sign.....
Local variables also not shown many times....

**Comment by VISTALL** [comment]
Hi. Checked breakpoint show breakpoint status (for example no bytecode for pause at current line). For example - it can be **X** when debugger can't resolve bytecode instruction (need good example for fix this problem).

Debugger attached to **Editor** instance not **Game**.  It's Unity architecture - there no external game instance for debug, only **Editor**

Thanks

**Comment by winxalex** [comment]
I can see log on same line but debugger doesn’t enter.

**Comment by VISTALL** [comment]
This issue you can always reproduce ? Or it's one-time.

I wanna fix this issue, but need found scenario how reproduce it.

How long you hold your debug session ?  For example you start debug, then edit code - check, edit, check ?  Maybe be you wrote some code in this file, and after some time - debugger can't stop inside those file.

Thanks
