### ISSUE TITLE
Consulo crashes immidieatley after start on highSierra

### ISSUE THREAD

**Issue by HovhannesNicoghosyan** [consulo/consulo-unity3d#140]
Hello, i downloaded consulo on high sierra and it worked fine, now it does not even want to open.
I've tried to reinstall but it does not work.

**Comment by VISTALL** [comment]
Hi. What you did ? And How it's crashed ? Native crash ? (you can show log from Mac) 

Thanks

**Comment by HovhannesNicoghosyan** [comment]
there is only " the application consulo could not be opened". 
I've reinstall os and it worked till i closed the app. when i want to open it the second, situation reapeats.

**Comment by HovhannesNicoghosyan** [comment]
when i open with terminal current log appears
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Consulo.app.

**Comment by VISTALL** [comment]
You used Consulo from one user ?

Can you try do in terminal

chmod +x /Applications/Consulo.app/Contents/MacOS/consulo*

**Comment by HovhannesNicoghosyan** [comment]
no, i have only one user on my mac.
i did it in terminal but nothing happens

**Comment by VISTALL** [comment]
Consulo throw same error ? (at start)

**Comment by HovhannesNicoghosyan** [comment]
nothing, only finder dialog opened with text "Consulo application could not be opened"

**Comment by VISTALL** [comment]
Can you try 

> open -a /Applications/Consulo.app

**Comment by HovhannesNicoghosyan** [comment]
the same error i wrote about above
"LSOpenURLsWithRole() failed for the application /Applications/Consulo.app with error -10810.
"
