### ISSUE TITLE
Debugger crashing Unity 

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#142]
Happen often. Especially if you go fas in Debug next, next line
[crash_0adbb32563f7d845bf80f224f4498c19.zip](https://github.com/consulo/consulo-unity3d/files/1559574/crash_0adbb32563f7d845bf80f224f4498c19.zip)
Unity crash (I know same moment, cos hdd become loud) and Consulo is saying waiting to debugger (X can't be canceled or return timeout)

**Comment by VISTALL** [comment]
Hi. From my expirence, it's reproducable bug, but need found where it. For exampale pausing or stepping to some position.

 (few month ago i fixed bug in debugger library for mono&unity, which provide same problem)

Thanks

**Comment by winxalex** [comment]
![clipboard02](https://user-images.githubusercontent.com/689092/34171192-c8a36e8c-e4ed-11e7-9955-82d5e772255a.jpg)

I crashed 5 times in row

**Comment by winxalex** [comment]
maybe if I'm not waiting collecting data... to finish maybe something else

**Comment by VISTALL** [comment]
Hi. I sympathize with you. But i can't help you without your help in this problem, or without your source.

You need find where it crashed.

For now, i'm blind - it's not reproducable crash with simple code.

Thanks

**Comment by VISTALL** [comment]
I got some strange issue with UnityConsulo plugin. 

Can you delete my unity plugin from project ? And try without it 

related https://github.com/consulo/UnityEditorConsuloPlugin/issues/11

Just for test

Thanks

**Comment by parmaia** [comment]
Hi! This happens to me too, I think that it crashes during coroutines. If you want, I can do more tests on this to provide you more info.

**Comment by VISTALL** [comment]
Hello. It will be great, due i have no idea how reproduce it. I tested some big project on my mac or pc, and no success. 

Thanks
