### ISSUE TITLE
Integrated Vuforia Support

### ISSUE THREAD

**Issue by TeorikDeli** [consulo/consulo-unity3d#143]
Hi!

As release of the Unity 2017.2, Vuforia became integrated in Unity. I don't use Vuforia as a plugin anymore. So, all of it's namespaces, classes are not showing in consulo. Can you add Vuforia libraries for consulo? I am not sure if I can add these myself to my consulo project. 🤔

<img width="535" alt="ekran resmi 2017-12-21 22 54 32" src="https://user-images.githubusercontent.com/9395555/34272688-43e03476-e6a2-11e7-8c60-87f26b92d37c.png">

Thanks.

**Comment by VISTALL** [comment]
Hi. Oo. I will check, thanks

**Comment by VISTALL** [comment]
Note for me. After Unity 2017.2 (or maybe early) - added new libraries by path `Unity 2017.3\Editor\Data\PlaybackEngines\VuforiaSupport`

MonoDevelop add this two libraries as dependencies to projects (C# and C# Editor, very strange, editor library in default project, looks like a bug)

> Managed\Runtime\Vuforia.UnityExtensions.dll
> Managed\Editor\Vuforia.UnityExtensions.Editor.dll

For now idk, how validate project for adding Vuforia dependencies. Maybe check for exising `Assets\Vuforia` directory.

@TeorikDeli do you have **Vuforia** directory in project (in assets) ?

Thanks

**Comment by TeorikDeli** [comment]
@VISTALL , yeah I have. After activating the Vuforia AR support, Unity will import Vuforia pack. But, this pack doesn't include dlls or core scripts. Some simple scripts, shaders, materials, prefabs, editor scripts and textures/fonts.

**Comment by VISTALL** [comment]
Yeah, but i can't determinate enabled Vuforia or not, since Unity used undocumented binary config storage file.

**Comment by VISTALL** [comment]
Can you try Unity plugin from nightly channel ?

**Comment by TeorikDeli** [comment]
OK, I'll inform you about that when I can test it.

**Comment by VISTALL** [comment]
Nice, thanks

**Comment by TeorikDeli** [comment]
By the way, how can I use nightly channel? Just download this package https://hub.consulo.io/#!repo/nightly/consulo.unity3d and then, add it via plugins->install from disk? Or should I also install nightly consulo?

**Comment by VISTALL** [comment]
https://github.com/consulo/consulo/wiki/Update-channels

**Comment by VISTALL** [comment]
and then click About -> Check for updates

**Comment by TeorikDeli** [comment]
I tried with nightly, still cannot find the Vuforia namespace.

**Comment by VISTALL** [comment]
u downloaded updates ? (via check for updates)

**Comment by TeorikDeli** [comment]
Yeah, build numbers are the latest (Unity3D 3756).

**Comment by VISTALL** [comment]
Ah. Reimport unity project (click on Re-import project - in context menu on project directory)

**Comment by TeorikDeli** [comment]
Still the same. Also restarted consulo, then reimported the project. I'll try with a new project.

**Comment by VISTALL** [comment]
looks like i missed something.

Can you find your Unity distribution and check those paths

%UNITY%\Editor\Data\PlaybackEngines\VuforiaSupport\Managed\Runtime\Vuforia.UnityExtensions.dll

%UNITY%\Editor\Data\PlaybackEngines\VuforiaSupport\Managed\Editor\Vuforia.UnityExtensions.Editor.dll


and.

Directory %PRJECT%/Assets/Vuforia  exists? Thanks

**Comment by TeorikDeli** [comment]
Yes I have Vuforia folder in my project. I am on Mac, so I checked for DLLs from temp files:

-r:'/Applications/Unity/PlaybackEngines/VuforiaSupport/Managed/Editor/Vuforia.UnityExtensions.Editor.dll'
-r:'/Applications/Unity/PlaybackEngines/VuforiaSupport/Managed/Runtime/Vuforia.UnityExtensions.dll'


Full content: 
`
-debug
-target:library
-nowarn:0169
-langversion:4
-out:'Temp/Assembly-CSharp.dll'
-unsafe
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEditor.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.CoreModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.AccessibilityModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.ParticleSystemModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.PhysicsModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.VehiclesModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.ClothModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.AIModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.AnimationModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.TextRenderingModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UIModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.TerrainPhysicsModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.IMGUIModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.ClusterInputModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.ClusterRendererModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UNETModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.DirectorModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UnityAnalyticsModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.PerformanceReportingModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UnityConnectModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.WebModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.ARModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.VRModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UIElementsModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.StyleSheetsModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.AssetBundleModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.AudioModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.CrashReportingModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.GameCenterModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.GridModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.ImageConversionModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.InputModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.JSONSerializeModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.ParticlesLegacyModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.Physics2DModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.ScreenCaptureModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.SharedInternalsModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.SpriteMaskModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.SpriteShapeModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.TerrainModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.TilemapModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UnityWebRequestModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UnityWebRequestAudioModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UnityWebRequestTextureModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.UnityWebRequestWWWModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.VideoModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEngine/UnityEngine.WindModule.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/Editor/UnityEditor.UI.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/UnityEngine.Networking.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/Editor/UnityEditor.Networking.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/TestRunner/Editor/UnityEditor.TestRunner.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/TestRunner/UnityEngine.TestRunner.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/TestRunner/net35/unity-custom/nunit.framework.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Timeline/RuntimeEditor/UnityEngine.Timeline.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Timeline/Editor/UnityEditor.Timeline.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/TreeEditor/Editor/UnityEditor.TreeEditor.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UIAutomation/UnityEngine.UIAutomation.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UIAutomation/Editor/UnityEditor.UIAutomation.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityGoogleAudioSpatializer/Editor/UnityEditor.GoogleAudioSpatializer.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityGoogleAudioSpatializer/RuntimeEditor/UnityEngine.GoogleAudioSpatializer.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/Editor/UnityEditor.HoloLens.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/RuntimeEditor/UnityEngine.HoloLens.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnitySpatialTracking/Editor/UnityEditor.SpatialTracking.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnitySpatialTracking/RuntimeEditor/UnityEngine.SpatialTracking.dll'
-r:'/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityVR/Editor/UnityEditor.VR.dll'
-r:'/Applications/Unity/PlaybackEngines/VuforiaSupport/Managed/Editor/Vuforia.UnityExtensions.Editor.dll'
-r:'/Applications/Unity/PlaybackEngines/VuforiaSupport/Managed/Runtime/Vuforia.UnityExtensions.dll'
-r:'/Applications/Unity/Unity.app/Contents/Managed/UnityEditor.Graphs.dll'
-r:'/Applications/Unity/PlaybackEngines/AndroidPlayer/UnityEditor.Android.Extensions.dll'
-r:'/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.dll'
-r:'/Applications/Unity/Unity.app/Contents/PlaybackEngines/MacStandaloneSupport/UnityEditor.OSXStandalone.Extensions.dll'
-r:'/Users/TeorikDeli/Library/Unity/cache/packages/packages.unity.com/com.unity.ads@2.0.3/UnityEngine.Advertisements.dll'
-r:'/Users/TeorikDeli/Library/Unity/cache/packages/packages.unity.com/com.unity.ads@2.0.3/Editor/UnityEditor.Advertisements.dll'
-r:'/Users/TeorikDeli/Library/Unity/cache/packages/packages.unity.com/com.unity.analytics@2.0.13/UnityEngine.Analytics.dll'
-r:'/Users/TeorikDeli/Library/Unity/cache/packages/packages.unity.com/com.unity.analytics@2.0.13/Editor/UnityEditor.Analytics.dll'
-r:'/Users/TeorikDeli/Library/Unity/cache/packages/packages.unity.com/com.unity.purchasing@0.0.19/UnityEngine.Purchasing.dll'
-r:'/Users/TeorikDeli/Library/Unity/cache/packages/packages.unity.com/com.unity.purchasing@0.0.19/Editor/UnityEditor.Purchasing.dll'
-r:'/Users/TeorikDeli/Library/Unity/cache/packages/packages.unity.com/com.unity.standardevents@1.0.10/UnityEngine.StandardEvents.dll'
-r:'/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Xcode.dll'
-r:'/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Common.dll'
-define:UNITY_5_3_OR_NEWER
-define:UNITY_5_4_OR_NEWER
-define:UNITY_5_5_OR_NEWER
-define:UNITY_5_6_OR_NEWER
-define:UNITY_2017_1_OR_NEWER
-define:UNITY_2017_2_OR_NEWER
-define:UNITY_2017_3_OR_NEWER
-define:UNITY_2017_3_0
-define:UNITY_2017_3
-define:UNITY_2017
-define:PLATFORM_ARCH_64
-define:UNITY_64
-define:ENABLE_AUDIO
-define:ENABLE_CACHING
-define:ENABLE_CLOTH
-define:ENABLE_DUCK_TYPING
-define:ENABLE_GENERICS
-define:ENABLE_PVR_GI
-define:ENABLE_MICROPHONE
-define:ENABLE_MULTIPLE_DISPLAYS
-define:ENABLE_PHYSICS
-define:ENABLE_SPRITERENDERER_FLIPPING
-define:ENABLE_SPRITES
-define:ENABLE_GRID
-define:ENABLE_TILEMAP
-define:ENABLE_TERRAIN
-define:ENABLE_RAKNET
-define:ENABLE_DIRECTOR
-define:ENABLE_UNET
-define:ENABLE_LZMA
-define:ENABLE_UNITYEVENTS
-define:ENABLE_WEBCAM
-define:ENABLE_WWW
-define:ENABLE_CLOUD_SERVICES_COLLAB
-define:ENABLE_CLOUD_SERVICES_COLLAB_SOFTLOCKS
-define:ENABLE_CLOUD_SERVICES_ADS
-define:ENABLE_CLOUD_HUB
-define:ENABLE_CLOUD_PROJECT_ID
-define:ENABLE_CLOUD_SERVICES_USE_WEBREQUEST
-define:ENABLE_CLOUD_SERVICES_UNET
-define:ENABLE_CLOUD_SERVICES_BUILD
-define:ENABLE_CLOUD_LICENSE
-define:ENABLE_EDITOR_HUB
-define:ENABLE_EDITOR_HUB_LICENSE
-define:ENABLE_WEBSOCKET_CLIENT
-define:ENABLE_DIRECTOR_AUDIO
-define:ENABLE_DIRECTOR_TEXTURE
-define:ENABLE_TIMELINE
-define:ENABLE_EDITOR_METRICS
-define:ENABLE_EDITOR_METRICS_CACHING
-define:ENABLE_NATIVE_ARRAY
-define:ENABLE_SPRITE_MASKING
-define:INCLUDE_DYNAMIC_GI
-define:INCLUDE_GI
-define:ENABLE_MONO_BDWGC
-define:PLATFORM_SUPPORTS_MONO
-define:RENDER_SOFTWARE_CURSOR
-define:INCLUDE_PUBNUB
-define:ENABLE_PLAYMODE_TESTS_RUNNER
-define:ENABLE_VIDEO
-define:ENABLE_RMGUI
-define:ENABLE_PACKMAN
-define:ENABLE_CUSTOM_RENDER_TEXTURE
-define:ENABLE_STYLE_SHEETS
-define:ENABLE_LOCALIZATION
-define:PLATFORM_STANDALONE_OSX
-define:PLATFORM_STANDALONE
-define:UNITY_STANDALONE_OSX
-define:UNITY_STANDALONE
-define:ENABLE_SUBSTANCE
-define:ENABLE_GAMECENTER
-define:ENABLE_RUNTIME_GI
-define:ENABLE_MOVIES
-define:ENABLE_NETWORK
-define:ENABLE_CRUNCH_TEXTURE_COMPRESSION
-define:ENABLE_UNITYWEBREQUEST
-define:ENABLE_CLOUD_SERVICES
-define:ENABLE_CLOUD_SERVICES_ANALYTICS
-define:ENABLE_CLOUD_SERVICES_PURCHASING
-define:ENABLE_CLOUD_SERVICES_CRASH_REPORTING
-define:ENABLE_CLOUD_SERVICES_NATIVE_CRASH_REPORTING
-define:ENABLE_CLUSTERINPUT
-define:ENABLE_VR
-define:ENABLE_AR
-define:ENABLE_SPATIALTRACKING
-define:ENABLE_WEBSOCKET_HOST
-define:ENABLE_MONO
-define:NET_2_0_SUBSET
-define:ENABLE_PROFILER
-define:DEBUG
-define:TRACE
-define:UNITY_ASSERTIONS
-define:UNITY_EDITOR
-define:UNITY_EDITOR_64
-define:UNITY_EDITOR_OSX
-define:ENABLE_NATIVE_ARRAY_CHECKS
-define:UNITY_TEAM_LICENSE
'Assets/Vuforia/Scripts/DefaultInitializationErrorHandler.cs'
'Assets/Vuforia/Scripts/DefaultTrackableEventHandler.cs'
-r:'/Applications/Unity/Unity.app/Contents/Mono/lib/mono/unity/System.Runtime.Serialization.dll'
-r:'/Applications/Unity/Unity.app/Contents/Mono/lib/mono/unity/System.Xml.Linq.dll'
-r:'/Applications/Unity/Unity.app/Contents/Mono/lib/mono/unity/UnityScript.dll'
-r:'/Applications/Unity/Unity.app/Contents/Mono/lib/mono/unity/UnityScript.Lang.dll'
-r:'/Applications/Unity/Unity.app/Contents/Mono/lib/mono/unity/Boo.Lang.dll'
-sdk:unity
`

**Comment by VISTALL** [comment]
Can you show page like this (project dir right click -> project structure -> modules -> Assembly-CSharp)

Open Dependencies

![](http://klikr.org/dd49e012af5de8bd43354f15a74c.png)

and Extensions tab(and unity extension), but on **project root module**

![](http://klikr.org/c1fb876ac1972d74ff036ea241fe.png)

**Comment by TeorikDeli** [comment]
<img width="1250" alt="ekran resmi 2017-12-22 18 42 17" src="https://user-images.githubusercontent.com/9395555/34303754-eb212fec-e747-11e7-87d4-ef45fc3d7321.png">
<img width="1249" alt="ekran resmi 2017-12-22 18 41 51" src="https://user-images.githubusercontent.com/9395555/34303755-eb42e1be-e747-11e7-825b-f70ecec279c8.png">

Well, Vuforia showing in there 🤔

**Comment by VISTALL** [comment]
Yeah. It's wrong paths for Mac. And yesterday, i forgot charger for my mac >.< at work. Bad luck

For now you can add via plus (in dependency tab - Assembly-CSharp module) select this libraries

r:'/Applications/Unity/PlaybackEngines/VuforiaSupport/Managed/Editor/Vuforia.UnityExtensions.Editor.dll' -r:'/Applications/Unity/PlaybackEngines/VuforiaSupport/Managed/Runtime/Vuforia.UnityExtensions.dll' 

but it will be reseted after Reimport

**Comment by TeorikDeli** [comment]
It works now 🕺🏻 Thank you!

**Comment by VISTALL** [comment]
I will fix, as fast i get my mac charger. Sry

**Comment by VISTALL** [comment]
Got charger. On macOS Unity placed vuforia engine in not default path 

> /Applications/Unity/PlaybackEngines

when Unity.app placed at 

> /Applications/Unity/Unity.app

will fix after work.

It's note for me. 

Thanks

**Comment by VISTALL** [comment]
Can you test last build ?

**Comment by TeorikDeli** [comment]
Yeeeey! Everything works for Vuforia! 💪🏻 Thank you!

But, I have a problem with opening scripts from Unity on nightly channel. It doesn't focus to Consulo and doesn't open the file I double clicked on, then Consulo gives me this error:

<img width="570" alt="ekran resmi 2017-12-26 19 41 37" src="https://user-images.githubusercontent.com/9395555/34360774-f99fb590-ea74-11e7-9c9e-9b74a21fea9f.png">

This wasn't happening on release channel.

**Comment by VISTALL** [comment]
That strange. It's depend to UnityConsulo plugin. Looks like it's not working anymore. Hm
