### ISSUE TITLE
Ctrl + B  on variable which is usage do optimized search 

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#145]
![consulo](https://user-images.githubusercontent.com/689092/34390882-dbe9817e-eb42-11e7-821c-f83acd2326e2.jpg)
Thk u very much for the optimized search. Why don't u search binaries too :dagger:  :)

**Comment by VISTALL** [comment]
Hello. Sorry - i missed this issue. Looks like need provide action for filtering assets usage

Thanks

**Comment by VISTALL** [comment]
![hideassetusage](https://user-images.githubusercontent.com/542934/37236029-deed8856-2414-11e8-982d-4be19eef0fc6.gif)
added option for show usages. By default disabled
