### ISSUE TITLE
Consulo get into endless loop and stuck parsing this file

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#146]
[FunctionComponentNode.zip](https://github.com/consulo/consulo-unity3d/files/1596561/FunctionComponentNode.zip)

**Comment by winxalex** [comment]
Happy New Year

**Comment by VISTALL** [comment]
Hello. Sorry but i can't reproduce. Looks like it's based on your code

![](https://i.gyazo.com/a1de458794ea7ae100350f3b5d8eb4c2.png)

ton of red code, but it's okey

Happy New Year too.

Thanks

**Comment by winxalex** [comment]
Try just that METHODS part you will stuck parser I think

**Comment by VISTALL** [comment]
i copied full file to project - no success
