### ISSUE TITLE
Adding methods via completion suggests wrong parameter type

### ISSUE THREAD

**Issue by Simplifier** [consulo/consulo-unity3d#147]
Parameter type is the same as parameter name
![](https://api.monosnap.com/rpc/file/download?id=HyC7ESjnpX1kS08pA8dyXcpysJka1K)

**Comment by VISTALL** [comment]
Hello. Fixed in nightly channel (nightly -> release iteration delayed)

Thanks

**Comment by Simplifier** [comment]
When I switched to night build, it broke. C# and other plugins don't work anymore. What did i do wrong?

**Comment by VISTALL** [comment]
Can you show what you mean *broke*? U got error like "wrong version"? I am working in Consulo from nightly build, and it's Ok.  Can you check again (check for updates)? Maybe you run update while some plugin was broken .

Thanks
