### ISSUE TITLE
Recognize class as Playable

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#149]
Example class have nothing with IPlayable
<img width="1440" alt="screen shot 2018-02-15 at 2 49 20 pm" src="https://user-images.githubusercontent.com/689092/36259825-ba604f3a-125f-11e8-9088-cdff8eee5588.png">
myClass.Destroy (I dont' have such function)
<img width="1440" alt="screen shot 2018-02-15 at 2 48 59 pm" src="https://user-images.githubusercontent.com/689092/36259879-eb491532-125f-11e8-9de4-675378ce596a.png">
Recognize as existing function in package playables 
<img width="1440" alt="screen shot 2018-02-15 at 2 49 54 pm" src="https://user-images.githubusercontent.com/689092/36259912-15e3e2cc-1260-11e8-9497-74b75a94358d.png">

and when I do Alt+Enter show no error.

**Comment by VISTALL** [comment]
Hello. Can you create simple reproduce example? 

Thanks.
