### ISSUE TITLE
multi-modules

### ISSUE THREAD

**Issue by FredDull** [consulo/consulo-unity3d#15]
![image](https://cloud.githubusercontent.com/assets/12006286/7449803/ded24d54-f26f-11e4-9b10-1fb48d432b00.png)
when I import a real unity project into consulo (100+ files), there are 5 modules in it. When I edit a cs file, consulo hangs again. If I delete all the modules except the one I need, the situation is much better, but I need to add all the dependencies to it manually. By the way, consulo adds a dll file twice to a module (in box 2).

**Comment by FredDull** [comment]
all the plugins are the latest ones.

**Comment by VISTALL** [comment]
Hi.  Dropping modules is not good idea. Current strucuture is like original Unity Visual Studio model

Hangs while editing .cs files - its C# related problem. C# implementation is in early stage of testing and can have performance issues.

I think need - teach you how use profiler, and found a problem.

**Comment by FredDull** [comment]
ok, I'll try to get u a list of snapshots.

**Comment by VISTALL** [comment]
Memory settings problem
