### ISSUE TITLE
Connection to Debugger 5 to 10s event on dual Mac Quad core

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#151]
Until (checked sign on the debbuging point is shown pass 5 or more seconds)

**Comment by VISTALL** [comment]
I think need optimize calling Unity VM when breakpoint reached. Reviewing what i can cache some values or rewrite logic.

Thanks

**Comment by VISTALL** [comment]
Tested on prev build and current, and i don't so much delay. My mac
```
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
```

Will anyway optimize that i can
