### ISSUE TITLE
Consulo doesn't like System.Linq

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#152]
Doesn't offer auto complete on extension functions and auto add of System.Linq. I always manually add System.Linq. Doesn't support debugging in Lambda functions try for example ForEach debug point inside is always x when start. Shows not existing errors.
<img width="1440" alt="screen shot 2018-03-10 at 10 04 20 am" src="https://user-images.githubusercontent.com/689092/37240388-d34a32de-244a-11e8-9cd9-f3b5ac9c3278.png">

**Comment by VISTALL** [comment]
Red code with import Linq - or without it ?

**Comment by winxalex** [comment]
with (I write no error in Unity)

**Comment by winxalex** [comment]
This is critical issue. Consulo hangs I'm restarting non stop. Your parser is broken and get into internal loop.
Consulo isn't usable NOW.

**Comment by winxalex** [comment]
Doesn't suggest to include System.Linq and doesn't recognize parts as System.Linq when I use that namespace.

**Comment by VISTALL** [comment]
Hello. I need code example for reproduce. Thanks
