### ISSUE TITLE
UnityEditorConsuloPlugin not Installed

### ISSUE THREAD

**Issue by parmaia** [consulo/consulo-unity3d#154]
Hi, this is happening since few weeks ago, basically if I create a new project in Unity, then open it in consulo does not tell me to install the UnityEditorConsuloPlugin dll in the project.

I searched in the consulo menu if there is an option to manually check/update/install UnityEditorConsuloPlugin dll but found nothing.

What I'm doing is to copy Editor/Plugins/UnityEditorConsuloPlugin2017.2.dll manually from other project.

I'm on Windows 10, using consulo build 2010. And no matter what version of Unity I try > 2017.2).

**Comment by VISTALL** [comment]
Hello. I will test it after my holidays(around two weeks left). Sorry for long delay of reply, edge internet :(

Thanks.

**Comment by parmaia** [comment]
Perfect, enjoy your holidays. By now I can work without problems doing the manual copy of the dll.

Thanks for the answer.

**Comment by VISTALL** [comment]
Hello. I tested with 2017+ (2018+ too) - there no problem. I think problem was due plugin didn't known anything about some 2017/2018 versions (i added new versions).

I have some sort of version list, where need add new versions:

https://github.com/consulo/consulo-unity3d/blob/master/plugin/src/main/java/consulo/unity3d/bundle/Unity3dDefineByVersion.java#L34

**Comment by parmaia** [comment]
This is working great now! I'll close the issue.
