### ISSUE TITLE
Automate adding TestRunner.dll library with UnityEngine.TestTools namespace

### ISSUE THREAD

**Issue by avvakhnin** [consulo/consulo-unity3d#155]
Consulo highlight TestTools as error. But all problems pass when I add "TestRunner" as "Standart library" on "Modules" tab. Another method to pass problem - add dll as library

Linux (Lubuntu)
Unity3d - 2018.2.0b5
Consulo - 2010
Last version of UnityEditorConsuloPlugin2017.2.dll

Windows 10
Unity3d - 2017.3.0b2
Consulo - 1634
Last version of UnityEditorConsuloPlugin2017.2.dll

![default](https://user-images.githubusercontent.com/31824236/40962520-6b719762-68ae-11e8-9799-a5af71bc6cd1.png)

![default](https://user-images.githubusercontent.com/31824236/40962528-72607494-68ae-11e8-9f83-511bc19a3771.png)

![windowsextends](https://user-images.githubusercontent.com/31824236/40962561-84050f52-68ae-11e8-81de-4018065b0afd.PNG)

**Comment by VISTALL** [comment]
Thanks!
