### ISSUE TITLE
Everytime you do update consulo things happen GRRR :)

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#158]
<img width="1440" alt="screen shot 2018-10-17 at 8 41 22 pm" src="https://user-images.githubusercontent.com/689092/47108861-0996e980-d24d-11e8-9c79-3c433a2d91cf.png">

**Comment by VISTALL** [comment]
Hello. Looks like Unity sdk is not resolved. Can you say your Unity version? Also 

File -> Project Structure -> select root project and show this page

![](https://klikr.org/1cad528eb6272a17d17c062c5db3.png)

and another page with same SDK name

![](https://klikr.org/f1a8b87e9370d562edd0345a4df9.png)


Thanks

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2018-10-17 at 8 52 29 pm" src="https://user-images.githubusercontent.com/689092/47109639-0e5c9d00-d24f-11e8-997a-3c8ca00e1c90.png">
If you have entry here and no matter if Unity SDK exist at that location. It didn't show (it should) this:
<img width="1440" alt="screen shot 2018-10-17 at 8 55 32 pm" src="https://user-images.githubusercontent.com/689092/47109688-36e49700-d24f-11e8-99f9-522ea720ce69.png">
After I delete entry it will show this "good" message. But If I can't apply. 
<img width="1440" alt="screen shot 2018-10-17 at 8 58 02 pm" src="https://user-images.githubusercontent.com/689092/47109766-6398ae80-d24f-11e8-9df5-a5c48d4f1e3c.png"> Apply button is disabled.

**Comment by winxalex** [comment]
From 2018.2 Unity know use UnityHub.

**Comment by VISTALL** [comment]
after change sdk - you need Re-import unity project.

I will check you Unity Hub . Yeah i don't handle unity hub paths

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2018-10-17 at 9 05 54 pm" src="https://user-images.githubusercontent.com/689092/47110206-7b246700-d250-11e8-8d8f-e31c48ae720a.png">

UnityEngine.Purchasing is included

**Comment by parmaia** [comment]
Yes, Re-importing unity project usually solves this kind of problems for me.

**Comment by VISTALL** [comment]
Hello. Added resolving for Unity distribution from Unity Hub. 

Can you say your unity version where library is not resolved? Unity change libraries paths in last versions, sometimes they can't resolved by default paths.

Thanks
