### ISSUE TITLE
Debbuger not working

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#159]
Win 10
Unity 2018.2.17f1
![untitled](https://user-images.githubusercontent.com/689092/49167120-a78dd180-f32c-11e8-8335-65223f312123.jpg)

Consulo build #2183
I'm putting breakpoints, consulo is connected to editor, breakpoints anywhere are empty (no sign) or when I put new while in debug (X) (X) (X).....

**Comment by winxalex** [comment]
I did update project and sync and now... seems working????

**Comment by VISTALL** [comment]
Hello. Looks like this file is new, and not attached to project system (need call Re-import Unity Project).

I think need add some file notification, when file is not attached.

Thanks

**Comment by VISTALL** [comment]
Added notification
![](https://klikr.org/efe41279e0800be6ac5530bc9e02.png)
