### ISSUE TITLE
Collecting data....

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#160]
I've clicked throut the stek functions, going to first function cosulo is stuck. This is often behaviour. Why don't you return "time out" or disbale switching of stek function while load, cos fast switch stuck everything,....not very nice implementation.

**Comment by VISTALL** [comment]
Hello. This stuck is not normal - and that can be fixed if i reproduce it.

About timeout - i will think about that (as i known timeout exists - but idk why it not works)

Thanks
