### ISSUE TITLE
Debbuger disconnect if error happen inside consulo

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#161]
When Consulo hang for some reason, it will be good if disconnects debugger link, cos it also stucks Unity. 
We should be able to disconnect even manually.

**Comment by VISTALL** [comment]
Hello. I heard about that problem - but i can't fix it without any details. I need log file from Consulo(and unity console log also) or reproduce example.

Thanks

**Comment by winxalex** [comment]
it would be good in most important try catch you do disconnect. I could click on disconnect button when Unity crash and nothing happen progress control on bottom bar is animating...
