### ISSUE TITLE
Opening Unity API Documentation in browser from Consulo (Feature request)

### ISSUE THREAD

**Issue by brogan89** [consulo/consulo-unity3d#166]
Would be nice to have a way open Unity API documentation in a browser based on context. I can't seem to find anything related to that in Consulo. There is an extension for it in vscode and it comes with Unity plugin for Visual Studio. So wondering if it can be added to Consulo as well?

**Comment by VISTALL** [comment]
Hello. Can you show example? As I known - each Unity library have .xml documentation, which can view via Ctrl + Q (at windows).

**Comment by brogan89** [comment]
Yes, but I am meaning for taking the user to Unity's API docs. Like this extensions for VSCode https://github.com/TobiahZ/unity-tools#command-open-documentation-for-selection 
Its not a major issue, but it is something very useful when you want to see code examples etc

**Comment by VISTALL** [comment]
Hello. I pushed fix to master (and it will be in nightly channel soon). 

But i tested only at Windows (Shift + F1 -> Show External Documentation) 

Also it must work at windows.

Later i will test it at macOS

**Comment by VISTALL** [comment]
updated macospaths
