### ISSUE TITLE
Unity SDK not found in Ubuntu 18.04

### ISSUE THREAD

**Issue by ejgutierrez74** [consulo/consulo-unity3d#169]
I have configured Consulo but didnt work, and seems i cant add the sdk...

![imagen](https://user-images.githubusercontent.com/11474846/52175830-131b7180-27aa-11e9-9327-58c57c21911b.png)

![imagen](https://user-images.githubusercontent.com/11474846/52175834-22022400-27aa-11e9-802b-347f221fc48f.png)

![imagen](https://user-images.githubusercontent.com/11474846/52175837-2af2f580-27aa-11e9-9ac1-789dca6821c2.png)

Any help would be apreciated..

Thanks

**Comment by VISTALL** [comment]
Hello. 

Bundles tab - it's list of all bundles(sdk) which Consulo resolved.

For project - select Unity3D at last screen 

![](https://klikr.org/120cd21ca5319a0b3c027296b01b.png)

**Comment by VISTALL** [comment]
And then invoke 'Reimport Unity project' from context menu (right click on root directory)

**Comment by ejgutierrez74** [comment]
I have done and seems to work but some other errors arise: Here is the event log...
```
3/02/19
23:52	Plugin Manager
				Plugin "Images" was not loaded: required plugin "consulo.library.batik" not installed.
				Plugin "Task Management" was not loaded: required plugin "consulo.library.flexmark" not installed.
				Disable not loaded plugins
				Open plugin manager

23:52	Consulo
				UnityEditor is not responding.
				Defines is not resolved.

23:53	Unity3D Plugin
				Consulo plugin for UnityEditor is missing
				Install

23:54	Consulo
				UnityEditor is not responding.
				Defines is not resolved.

23:54	Unity3D Plugin
				Consulo plugin for UnityEditor is missing
				Install
```

1 - Also i cant open an script, if consulo is not launched... with vscode if you dont have vscode launched, when you want to edit an script it automatically open vscode and the corresponding file....

![imagen](https://user-images.githubusercontent.com/11474846/52184363-996b9e00-2812-11e9-998b-ad4a47f4bcf0.png)

2 - And finally you have to install module for consulo editor in every project of unity ?

Thanks and seems its an impressive software that i have just began to discover....

**Comment by VISTALL** [comment]
About that:

> 23:52	Plugin Manager
> 				Plugin "Images" was not loaded: required plugin "consulo.library.batik" not installed.
> 				Plugin "Task Management" was not loaded: required plugin "consulo.library.flexmark" not installed.
> 				Disable not loaded plugins
> 				Open plugin manager


Please install those two libraries ![](https://klikr.org/04e88d42858517e3c22926ee2e2c.png)

(looks like it's a bug - i will fix it)

> 1 - Also i cant open an script, if consulo is not launched... with vscode if you dont have vscode launched, when you want to edit an script it automatically open vscode and the corresponding file....
> 2 - And finally you have to install module for consulo editor in every project of unity ?

For cold opening Consulo u need UnityEditorConsuloPlugin  in project and select External Editor to Consulo.

You need copy UnityEditorConsuloPlugin to each projects. It's limitation of Unity - due there no global **plugins**. My plugin it's a hack - due there no way for patch UnityEditor :(


Strange error - i first time see that. I will check at this week

Thanks

**Comment by ejgutierrez74** [comment]
Thanks i could install that packages. Seems that i can start consulo without problems now.

1 - VSCode you dont need as i know to install in every project to use it....

**Comment by VISTALL** [comment]
Yeah. It's works due Unity contains implementation of creator .sln+.csproj files.

Consulo from start not use VS files - that why need custom implementation of project importing (from start Consulo not contains VS project system, and VS project system limited, and i don't want migrate to it)

Thanks. Can i close this issue?

**Comment by ejgutierrez74** [comment]
Yes was only a suggestion

**Comment by VISTALL** [comment]
Thanks for few other issues. I will fix it after my primary job
