### ISSUE TITLE
Highlighting suspended temporaly 

### ISSUE THREAD

**Issue by ejgutierrez74** [consulo/consulo-unity3d#170]
![imagen](https://user-images.githubusercontent.com/11474846/52204973-f3ea1600-2875-11e9-81fd-46d2a4d1ac8e.png)

Seems highlighting have been disabled, dont know if its a bug or something i tweak, but i can get it back to work.... 

Thanks

**Comment by VISTALL** [comment]
Hello. In other files highlight works? Restart not help? Also can you attach log (help -> show log in ...)

You changed something in project structure?

Thanks

**Comment by ejgutierrez74** [comment]
[threadDump-20190204-000358.txt](https://github.com/consulo/consulo-unity3d/files/2831380/threadDump-20190204-000358.txt)
[threadDump-20190204-000403.txt](https://github.com/consulo/consulo-unity3d/files/2831381/threadDump-20190204-000403.txt)
[consulo.log](https://github.com/consulo/consulo-unity3d/files/2831383/consulo.log)

I atach the files i found...seems restarting solves the problem...another thing yesterday was, that i modified a file, so it appears its name underlined... but i save it ctrl+s, and it continued with underlined...as consulo didnt save it....But this changes where applied to unity... Strange thing just to let you know,

Thanks

**Comment by VISTALL** [comment]
Strange

**Comment by ejgutierrez74** [comment]
do you need more info?

**Comment by VISTALL** [comment]
If this issue repeated - try to find reproduce example. It will be nice. Thanks
