### ISSUE TITLE
Editor Error

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#171]
Assertion failed on expression: 'ptr == NULL || !HAS_ROOT_REFERENCE(GET_CURRENT_ALLOC_ROOT_REFERENCE()) || GET_CURRENT_ALLOC_ROOT_REFERENCE() == GET_ROOT_REFERENCE(s_MonoDomainContainer, kMemMono)'
UnityEngine.Networking.UnityWebRequest:SendWebRequest()
Consulo.Internal.UnityEditor.<SendRequestToConsuloImpl>c__Iterator0:MoveNext()
Consulo.Internal.UnityEditor.ConsuloIntegration:SendRequestToConsulo(String, JSONClass)
Consulo.Internal.UnityEditor.ConsuloIntegration:SendToConsulo(String, JSONClass, Boolean)
Consulo.Internal.UnityEditor.WebApiServer:<WebApiServer>m__2()

**Comment by VISTALL** [comment]
Hello. It's strange. Idk how reproduce that due it's a problem inside Unity.

I want rewrite sending data (remove usage of UnityWebRequest) - but i found some problem in native .NET webrequest (it not send any data). That why i don't known simple fix for it.

(commit https://github.com/consulo/UnityEditorConsuloPlugin/commit/06e3a31a8e08cd66f7df58c9424bd6a6cdc29700)

Thanks
