### ISSUE TITLE
Unity Integration Error

### ISSUE THREAD

**Issue by TheYellowArchitect** [consulo/consulo-unity3d#178]
Hello, I got a crash report https://hub.consulo.io/errorReport#286acd4d-106d-4a4b-8550-10a0d6d4f277

I installed Consulo and worked normally, had the definitions and auto-complete and all.
Then I tried to make a small script (below) and Unity crashed when I alt-tabbed back to Unity
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;//Any class using UnityEditor cannot be built btw.

public class ToolGit : EditorWindow
{
	[MenuItem("Window/Git")]
	static void OpenWindow()
	{
		//This seems kinda complicated but here is how it goes.
		//ToolGit is an extension of EditorWindow so it has GetWindow function.
		//We downcast it here.
		ToolGit newWindow = (ToolGit)GetWindow(typeof(ToolGit));

		//We never want the window to be very small
		newWindow.minSize = new Vector2(300, 400);
	}

}
```

Now, when I open Unity, I can still open Consulo by opening any .cs file inside Unity
BUT, it gets the "IDE" error of UI Designer (IntelliJ?)

I tried disabling the plugin UI Designer, and while it opens the script no issues, there are no definitions, it's literally a text editor

As for other info to provide, I cannot think of any, except on the first times I used Consulo with Unity and opened a script, I got an error in Unity (in the console) which said something about cannot create thread or class or something, one every second almost, but after a few seconds it stopped popping up. I doubt it's related but anyway, maybe it helps

===

I fiddled around a bit, I enabled UI Designer plugin, closed and re-opened Consulo, imported the Unity Project and it works normally as it should, definitions and all O_o
Though, I am afraid of another crash, will post when it happens (hopefully not)

**Comment by VISTALL** [comment]
Hello. UI Designer plugin installed as part of "Java IDE". I saw your error - looks like open project problem.

About unity error. I known about it, i need some time for rewrite plugin, complex task for me at current moment.

Thanks

**Comment by TheYellowArchitect** [comment]
I worked today for like 8 hours with only 2 crashes (above included) so that's pretty good given I use version control and cannot lose anything
Yes, opening the project is tricky, once it opens up properly its stable and no issues

Only 1 question, once Unity crashes (cuz of Consulo), can there be a file corruption? I mean, does Consulo access any other file aside of code assets?

> About unity error. I known about it, i need some time for rewrite plugin, complex task for me at current moment.

I am glad to hear this, thanks for replying so swiftly and planning to update a code editor that so few use <3

**Comment by VISTALL** [comment]
>Only 1 question, once Unity crashes (cuz of Consulo), can there be a file corruption? 

I think unity crashed due Consulo integration plugin inside project (it's not perfect). Anyway - try to remove it (UnityEditorConsuloPlugin library).

You lose only navigation editor->consulo. Debugging will work as expected.

I'm working on improving UnityEditorConsuloPlugin , but need time

Thanks.
