### ISSUE TITLE
Double clicking on script doesn't work

### ISSUE THREAD

**Issue by avvakhnin** [consulo/consulo-unity3d#179]
I have:
Windows 10 x64
Unity3d 2020.2.0a13
Consulo 2020.8
UnityEditorConsuloPlugin2017.2.dll in \Assets\Editor\Plugins

1. When i have launched Unity3D and Consulo and I click on script - there is no any reaction. Consulo isn't focused and file isn't opened there
2. When i have launched Unity3D and not launched Consulo - Consulo begin starting and stuck.
3. In prev. case, if I clear Editor Args in External Tools - Consulo run normally. But file doesn't open in IDE

**Comment by VISTALL** [comment]
Hello. It's a Editor plugin bug. I don't have too much time for it, but i'm working on fix/

Thanks for issue

**Comment by VISTALL** [comment]
Hello. Try new npm version of plugin

https://github.com/consulo/UnityEditorConsuloPlugin
