### ISSUE TITLE
Workflow question/suggestion

### ISSUE THREAD

**Issue by BinaryPat** [consulo/consulo-unity3d#18]
if I have my project on in Unity I cannot build in Consulo because Unity won't allow another instance with the same project. I assume that this is expected. 

The next question is if I have Unity closed I can build and run no problem, but I cannot debug. Is this expected? 

I have been debugging by attaching to Unity but I cannot attach to the player. 

It would be nice to build from Consulo event when Unity is running, It would also be nice to see the error messages from Unity in Consulo with the ability to click to go to the file line where the error occurred 

Finally thank you for making Consulo!

**Comment by VISTALL** [comment]
Hi.

For now consulo used Unity by command line, but it obsolete variant, me waiting Unity devs, when they release Rest API. Compilation from command line - builded without Debug(idk why, no answer from Unity)

Attaching to player sometimes dont work, on MacOS ports cant binded(idk why, dont have MacBook).

Unity have hardcoded IDE support - i cant modify it: (

Thanks

**Comment by VISTALL** [comment]
Any questions?

**Comment by BinaryPat** [comment]
No, I understand thanks for answering

-Pat
