### ISSUE TITLE
Consulo fails to load git upm external libraries

### ISSUE THREAD

**Issue by TCROC** [consulo/consulo-unity3d#182]
![image](https://user-images.githubusercontent.com/24307049/98702944-ffbb1400-2348-11eb-97ae-bf7b042dd176.png)

The top library is a git upm package.  Other upm packages are loaded correctly.

**Comment by VISTALL** [comment]
Hello. Bug reproduced. It's not handled file or git upm packages.

I will fix it at this week or next.

Thanks

**Comment by TCROC** [comment]
Awesome!  Thanks for getting back to me!  No rush.

**Comment by TCROC** [comment]
Looking at the issue more, it also occurs for [embedded upm packages](https://docs.unity3d.com/Manual/upm-embed.html).

![image](https://user-images.githubusercontent.com/24307049/98851599-7d078700-2424-11eb-84b1-992ae7a4eb21.png)

This is how we normally do our package development.

And to add more details:

Unity Version: 2019.4.13f1
OS: Ubuntu 18.04

**Comment by TCROC** [comment]
Here is a link to a repo demonstrating the bug: https://github.com/TCROC/ConsuloBug.git

**Comment by VISTALL** [comment]
Thanks for project

**Comment by VISTALL** [comment]
I'm surprised about Packages dir handle. I didn't knew that.

**Comment by TCROC** [comment]
Let me know if you are able to reproduce it on your end with that project I shared when you get a chance.

**Comment by VISTALL** [comment]
Already reproduced. Consulo didn't handle internal packages. Only external, due i'm didn't knew about this handle from Unity.

Thanks, its unexpected

**Comment by TCROC** [comment]
Np!  Here are the current packages that VS Code recognizes:

![image](https://user-images.githubusercontent.com/24307049/98860967-7849cf80-2432-11eb-9b11-f6705135ae92.png)

And here are the docs on the different UPM kinds:

https://docs.unity3d.com/Manual/upm-manifestPrj.html

![image](https://user-images.githubusercontent.com/24307049/98861052-a202f680-2432-11eb-9e5f-232cc3344db2.png)

The ones that I'm personally familiar with are embedded, local, registry, and git.

I'm pretty sure they are translated like this:

Embedded = in Packages folder
Local = On disk
Registry = the same way consulo unity plugin is distributed
Git = git repositories, tags, and branches formatted for upm

I'm not sure on Built-in and Local tarball.  I'm sure Unity has more precise explanations in their docs.

**Comment by TCROC** [comment]
The project I shared with you is making use of both Git and Embedded

**Comment by VISTALL** [comment]
Hello. First part, support for Embedded packages pushed. But it only for nightly branch (https://github.com/consulo/Docs/blob/master/Update%20Channels.md)

**Comment by TCROC** [comment]
Awesome!  I'll test it out when I get a spare moment!

**Comment by TCROC** [comment]
Just checking in to see where this bug is at.  I haven't gotten around to testing it on my end yet.  Had some other critical priorities come up on our project.  I will get to testing this though.

**Comment by VISTALL** [comment]
> Just checking in to see where this bug is at. I haven't gotten around to testing it on my end yet. Had some other critical priorities come up on our project. I will get to testing this though.

Np. I have primary too ;)

**Comment by VISTALL** [comment]
must be all fixed

**Comment by TCROC** [comment]
Ok cool.  I'll try it out soon and let you know how it goes! :)

**Comment by TCROC** [comment]
> Hello. First part, support for Embedded packages pushed. But it only for nightly branch (https://github.com/consulo/Docs/blob/master/Update%20Channels.md)

I tried to test out this update, but the nightly builds won't load the Unity Plugin because it says that the required JavaScript plugin is incompatible
