### ISSUE TITLE
Consulo not importing Unity libraries automatically

### ISSUE THREAD

**Issue by xCISACx** [consulo/consulo-unity3d#183]
- IDE build number: 2729 (nightly)
- OS name and version: Windows 10 (2004)

Consulo can auto-complete the type names when writing them, but it does not automatically import the required libraries (UnityEngine.AI and UnityEngine.UI, in this case).
Is there a setting to turn this feature on? 
I'd like it to do it without me having to press Alt + Enter every time, if possible.
I searched the settings but couldn't find anything.

![image](https://user-images.githubusercontent.com/37281623/99071465-17450780-25aa-11eb-87d0-43732291c48b.png)

**Comment by VISTALL** [comment]
There few cases. If you type NavMeshAgent - you will see it in popup, and then you press Enter it will add correct **using**.

Second case its when you insert some code without using, or type without completion - it will be show Using popup.

And you are right without user it will be not add using.

It's C# issue

**Comment by xCISACx** [comment]
I see, so there is no way to implement it in Consulo then, language limitation?
I found a Visual Studio plugin for it: https://marketplace.visualstudio.com/items?itemName=Fudge.auto-using
I was wondering if such plugin could be made for Consulo.

**Comment by VISTALL** [comment]
>I was wondering if such plugin could be made for Consulo.

If you try select class from popup it will insert

![examplePopup](https://user-images.githubusercontent.com/542934/99073133-64cf6d80-25c6-11eb-8cbe-046a9222e185.gif)

> I see, so there is no way to implement it in Consulo then, language limitation?

Add using on fly - just only human-hours.

**Comment by xCISACx** [comment]
I see, I'll use the pop-up then, I did not notice it worked if done through it.

**Comment by VISTALL** [comment]
Np. Questions are welcome too
