### ISSUE TITLE
Namespace "System.Net.Http", Http is not resloved

### ISSUE THREAD

**Issue by TCROC** [consulo/consulo-unity3d#190]
Consulo fails to resolve Http in the System.Net.Http namespace in a Unity project:

![image](https://user-images.githubusercontent.com/24307049/101394162-1eec8900-3896-11eb-8b2d-2926fd8afede.png)

```cs
using UnityEngine;
using System.Net.Http;

namespace SomeNamespace1
{
    public class SomeScript1 : MonoBehaviour
    {
        // Start is called before the first frame update
        void Start()
        {
            HttpClient httpClient = new HttpClient();
        }

        // Update is called once per frame
        void Update()
        {

        }
    }
}
```

Unity resolves it fine tho and doesn't have any errors:

![image](https://user-images.githubusercontent.com/24307049/101394305-4e9b9100-3896-11eb-9587-e8bf048e024f.png)

[consulo.log](https://github.com/consulo/consulo-unity3d/files/5654751/consulo.log)

OS: Ubuntu 18.04
Unity Version: 2019.4.14f1
Unity Consulo Plugin Version: 2.4.0
<details>
<summary>Consulo About</summary>
<pre><code>
 Consulo:
  version = 2020.12
  build number = 2806
  build date = December 7, 2020
 Plugins:
  com.intellij = 2806
  com.intellij.xml = 2657
  com.intellij.properties = 2761
  consulo.dotnet = 3284
  consulo.dotnet.mono = 3833
  consulo.csharp = 4831
  consulo.javascript = 3066
  consulo.java = 4351
  com.intellij.uiDesigner = 5391
  consulo.nunit = 4363
  consulo.platform.desktop = 2806
  org.jetbrains.idea.maven = 5318
  org.jetbrains.plugins.yaml = 2127
  consulo.devkit = 8572
  consulo.unity3d = 7516
 JVM:
  vendor = JetBrains s.r.o
  version = 11.0.4
  runtimeVersion = 11.0.4+10-b304.77
  locale = en_US
 JVM Env:
  __idea.mac.env.lock = unlocked
  awt.toolkit = sun.awt.X11.XToolkit
  java.specification.version = 11
  sun.cpu.isalist = 
  sun.jnu.encoding = UTF-8
  log4j.shutdownHookEnabled = false
  sun.arch.data.model = 64
  consulo.properties.file = /home/t-croc/Applications/Consulo/consulo.properties
  sun.font.fontmanager = sun.awt.X11FontManager
  idea.properties.file = /home/t-croc/Applications/Consulo/consulo.properties
  java.vendor.url = https://www.jetbrains.com/
  consulo.home.path = /home/t-croc/Applications/Consulo/platform/build2806
  sun.java2d.uiScale.enabled = true
  log4j2.messageFactory = org.apache.logging.log4j.message.SimpleMessageFactory
  sun.io.useCanonCaches = false
  sun.boot.library.path = /home/t-croc/Applications/Consulo/platform/build2806/jre/lib
  jna.tmpdir = /home/t-croc/.consulo_settings/system/tmp
  sun.java.command = consulo.desktop.bootstrap/consulo.desktop.boot.main.Main
  jdk.debug = release
  sun.awt.exception.handler = com.intellij.openapi.application.impl.AWTExceptionHandler
  java.specification.vendor = Oracle Corporation
  jdk.module.path = /home/t-croc/Applications/Consulo/platform/build2806/boot
  java.version.date = 2019-07-16
  java.home = /home/t-croc/Applications/Consulo/platform/build2806/jre
  file.separator = /
  java.vm.compressedOopsMode = 32-bit
  line.separator = \n
  java.specification.name = Java Platform API Specification
  java.vm.specification.vendor = Oracle Corporation
  idea.home.path = /home/t-croc/Applications/Consulo/platform/build2806
  jdk.module.main.class = consulo.desktop.boot.main.Main
  awt.useSystemAAFontSettings = lcd
  sun.management.compiler = HotSpot 64-Bit Tiered Compilers
  jb.restart.code = 88
  java.runtime.version = 11.0.4+10-b304.77
  user.name = t-croc
  javax.swing.rebaseCssSizeMap = true
  sun.java2d.pmoffscreen = false
  sun.awt.noerasebackground = true
  file.encoding = UTF-8
  sun.java2d.noddraw = true
  jnidispatch.path = /home/t-croc/.consulo_settings/system/tmp/jna15199293809251991195.tmp
  idea.popup.weight = heavy
  jna.loaded = true
  java.io.tmpdir = /tmp
  java.version = 11.0.4
  java.vm.specification.name = Java Virtual Machine Specification
  java.awt.printerjob = sun.print.PSPrinterJob
  sun.os.patch.level = unknown
  consulo.vm.options.file = /home/t-croc/Applications/Consulo/consulo64.vmoptions
  java.library.path = /home/t-croc/Applications/Consulo/platform/build2806/bin::/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
  java.vendor = JetBrains s.r.o
  io.netty.processId = 44696
  sun.io.unicode.encoding = UnicodeLittle
  java.rmi.server.disableHttp = true
  io.netty.machineId = 28:f0:76:ff:fe:16:65:0e
  java.util.concurrent.ForkJoinPool.common.parallelism = 8
  sun.desktop = gnome
  java.class.path = 
  sun.awt.enableExtraMouseButtons = true
  java.vm.vendor = JetBrains s.r.o
  consulo.module.path.boot = true
  java.util.Arrays.useLegacyMergeSort = true
  user.timezone = America/New_York
  jb.vmOptionsFile = /home/t-croc/Applications/Consulo/consulo64.vmoptions
  idea.no.launcher = false
  swing.bufferPerWindow = false
  os.name = Linux
  java.vm.specification.version = 11
  sun.java.launcher = SUN_STANDARD
  user.country = US
  sun.cpu.endian = little
  user.home = /home/t-croc
  user.language = en
  idea.cycle.buffer.size = 1024
  java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
  jdk.module.main = consulo.desktop.bootstrap
  idea.max.intellisense.filesize = 2500
  sun.java2d.d3d = false
  java.net.preferIPv4Stack = true
  path.separator = :
  idea.use.default.antialiasing.in.editor = false
  os.version = 5.4.0-56-generic
  jna.nosys = true
  java.runtime.name = OpenJDK Runtime Environment
  sun.nio.ch.bugLevel = 
  java.vm.name = OpenJDK 64-Bit Server VM
  jna.platform.library.path = /usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/lib64:/usr/lib:/lib:/usr/lib/i386-linux-gnu:/lib/i386-linux-gnu:/lib32:/usr/lib32
  java.vendor.url.bug = https://youtrack.jetbrains.com
  java.util.concurrent.ForkJoinPool.common.threadFactory = consulo.bootstrap.concurrent.IdeaForkJoinWorkerThreadFactory
  user.dir = /home/t-croc
  os.arch = amd64
  io.netty.serviceThreadPrefix = Netty 
  idea.dynamic.classpath = false
  java.vm.info = mixed mode
  java.vm.version = 11.0.4+10-b304.77
  java.rmi.server.hostname = localhost
  sun.awt.datatransfer.timeout = 2000
  java.class.version = 55.0
 OS:
  name = Linux
  version = 5.4.0-56-generic
  arch = amd64
 Env:
  PATH = /usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/t-croc/.dotnet/tools
  XAUTHORITY = /run/user/1000/gdm/Xauthority
  XMODIFIERS = @im=ibus
  XDG_DATA_DIRS = /usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  GDMSESSION = ubuntu
  MANDATORY_PATH = /usr/share/gconf/ubuntu.mandatory.path
  TEXTDOMAINDIR = /usr/share/locale/
  GTK_IM_MODULE = ibus
  DBUS_SESSION_BUS_ADDRESS = unix:path=/run/user/1000/bus
  DEFAULTS_PATH = /usr/share/gconf/ubuntu.default.path
  XDG_CURRENT_DESKTOP = ubuntu:GNOME
  SSH_AGENT_PID = 2229
  LD_LIBRARY_PATH = /home/t-croc/Applications/Consulo/platform/build2806/bin:
  QT4_IM_MODULE = xim
  SESSION_MANAGER = local/tcroc-Z390-UD:@/tmp/.ICE-unix/2133,unix/tcroc-Z390-UD:/tmp/.ICE-unix/2133
  USERNAME = t-croc
  LOGNAME = t-croc
  PWD = /home/t-croc
  IM_CONFIG_PHASE = 2
  GJS_DEBUG_TOPICS = JS ERROR;JS LOG
  SHELL = /bin/bash
  GIO_LAUNCHED_DESKTOP_FILE = /home/t-croc/.local/share/applications/alacarte-made-3.desktop
  GNOME_DESKTOP_SESSION_ID = this-is-deprecated
  GTK_MODULES = gail:atk-bridge
  CLUTTER_IM_MODULE = xim
  TEXTDOMAIN = im-config
  ALL_JVM_ARGS = --add-opens=java.desktop/sun.awt=consulo.container.impl --add-opens=java.desktop/sun.awt.image=consulo.container.impl --add-opens=java.desktop/sun.java2d=consulo.container.impl --add-opens=java.desktop/sun.font=consulo.container.impl --add-opens=java.desktop/java.awt=consulo.container.impl --add-opens=java.desktop/javax.swing=consulo.container.impl --add-opens=java.desktop/javax.swing.plaf.basic=consulo.container.impl --add-opens=java.base/java.lang=consulo.container.impl --add-opens=java.desktop/javax.swing.text.html=consulo.container.impl --add-opens=java.desktop/java.awt.peer=consulo.container.impl  -Xms512m -Xmx1500m -XX:ReservedCodeCacheSize=240m -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+UseCodeCacheFlushing -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -XX:+HeapDumpOnOutOfMemoryError -Dawt.useSystemAAFontSettings=lcd  -Djb.vmOptionsFile="/home/t-croc/Applications/Consulo/consulo64.vmoptions" -Dconsulo.vm.options.file="/home/t-croc/Applications/Consulo/consulo64.vmoptions" -p "/home/t-croc/Applications/Consulo/platform/build2806/boot" -Dconsulo.module.path.boot=true -Dconsulo.home.path="/home/t-croc/Applications/Consulo/platform/build2806" -Didea.home.path="/home/t-croc/Applications/Consulo/platform/build2806" -Didea.properties.file="/home/t-croc/Applications/Consulo/consulo.properties" -Dconsulo.properties.file="/home/t-croc/Applications/Consulo/consulo.properties"   
  XDG_SESSION_DESKTOP = ubuntu
  CONSULO_HOME = /home/t-croc/Applications/Consulo/platform/build2806
  SHLVL = 0
  QT_IM_MODULE = xim
  XDG_CONFIG_DIRS = /etc/xdg/xdg-ubuntu:/etc/xdg
  LANG = en_US.UTF-8
  XDG_SESSION_ID = 3
  XDG_SESSION_TYPE = x11
  JDK = /home/t-croc/Applications/Consulo/platform/build2806/jre
  DISPLAY = :1
  ROOT_DIR = /home/t-croc/Applications/Consulo
  MAIN_CLASS_NAME = -m consulo.desktop.bootstrap/consulo.desktop.boot.main.Main
  GPG_AGENT_INFO = /run/user/1000/gnupg/S.gpg-agent:0:1
  DESKTOP_SESSION = ubuntu
  USER = t-croc
  XDG_MENU_PREFIX = gnome-
  GIO_LAUNCHED_DESKTOP_FILE_PID = 4439
  QT_ACCESSIBILITY = 1
  WINDOWPATH = 2
  GJS_DEBUG_OUTPUT = stderr
  SSH_AUTH_SOCK = /run/user/1000/keyring/ssh
  XDG_SEAT = seat0
  GNOME_SHELL_SESSION_MODE = ubuntu
  XDG_VTNR = 2
  XDG_RUNTIME_DIR = /run/user/1000
  HOME = /home/t-croc
</code></pre>
</details>

**Comment by TCROC** [comment]
This actually appears to be occurring for more than just System.Net.Http

![image](https://user-images.githubusercontent.com/24307049/101395574-23b23c80-3898-11eb-96f3-bc728c5e3fc5.png)

It is also occurring for UnityEngine.UI and TMPro.

The ZXing namespace is a plugin's namespace similar to that Newtonsoft error you resolved earlier.  I'll open up a seperate issue for that since it isn't only Unity related.

**Comment by VISTALL** [comment]
That strange. I'm sure UI is working (I'm every day works with Unity). Can you File -> Project Structure, and show me what you have? Also view Dependencies tab for Assembly-CSharp

**Comment by TCROC** [comment]
This is the Project Structure:

![image](https://user-images.githubusercontent.com/24307049/101397580-ddaaa800-389a-11eb-834b-7b05705cb1b9.png)

How do I get to the Dependencies tab?

**Comment by VISTALL** [comment]
Modules tab

**Comment by TCROC** [comment]
Awesome!  Just found it! :)

![image](https://user-images.githubusercontent.com/24307049/101397975-69bccf80-389b-11eb-8bf0-030570875483.png)

![image](https://user-images.githubusercontent.com/24307049/101398079-8e18ac00-389b-11eb-8d7c-86f077d8c583.png)

(I blurred out the one.  It was a private package that is irrelevant)

**Comment by VISTALL** [comment]
Np. Right *+* and select .NET library. System.Http for example. Helps or not

**Comment by TCROC** [comment]
That worked! :)

**Comment by TCROC** [comment]
Now we just have to resolve the Unity.UI issue

**Comment by TCROC** [comment]
And TMPro

**Comment by VISTALL** [comment]
looks like bug. Can you say what depedencies you added? Also reimport will drop choose changes

**Comment by TCROC** [comment]
I added System.Net.Http

![image](https://user-images.githubusercontent.com/24307049/101402041-31b88b00-38a1-11eb-8cdd-672b61a7c6ee.png)

**Comment by TCROC** [comment]
I'll fill out a separate issue for those other problems with UnityEngine.UI, the ZXing, and TMPro

**Comment by TCROC** [comment]
Ok so I can't seem to recreate the issue in an example project.  It only occurs in this project.  Any ideas as to where to look for the issue?

**Comment by TCROC** [comment]
The System.Net.Http error occurs in the example project, but not the other ones

**Comment by TCROC** [comment]
I think I found the issue!  (At least in my main project).  The issue with UnityEngine.UI, plugins, and TMPro seems to only occur for embedded packages.  I'll see if I can recreate it in an example project and share it with you

**Comment by TCROC** [comment]
Yep!  That causes it!  I'll open up a separate issue with a link to a GitHub project.

**Comment by VISTALL** [comment]
Test new build

**Comment by TCROC** [comment]
This appears to be working now
