### ISSUE TITLE
Steamworks Dependency Not Detected

### ISSUE THREAD

**Issue by TheYellowArchitect** [consulo/consulo-unity3d#199]
The code in Consulo, using Steamworks; library's functions is full of errors, yet, it compiles normally, as expected in Unity, and the logic works (code below shows steam username, and also unlocks achievements - it works)
I tried clicking "Re-Import Unity Project" as suggested here https://github.com/consulo/consulo-unity3d/issues/194 but it didn't work

Image of the project folder
![consulo](https://user-images.githubusercontent.com/25630803/114187713-2764d700-98fd-11eb-9675-3866ea2af813.PNG)
![14](https://user-images.githubusercontent.com/25630803/114189363-fab1bf00-98fe-11eb-8be8-45153a8f5223.PNG)

Image of the manifest.json (no idea why it's so empty)
![Computer](https://user-images.githubusercontent.com/25630803/114187816-47949600-98fd-11eb-8ddb-fbb2903544e5.PNG)

Trying to find declaration of Steamworks; -> "Cannot find declaration"

Link to Steamworks library and how I installed it
https://steamworks.github.io/installation/
I did Option A, aka downloaded the unity package, and imported it.
It works properly btw, the issue is that Consulo doesn't detect the library/dependency, making it very hard to code :(

**Specs**
Windows 7 x64
Unity 2018.1.1f1
Consulo 2020.12

Minor note that I don't use Consulo plugin for Unity, but this is no problem for me, as I just ctrl+shift+N to edit any file, then compiling in Unity like normal :)

Any idea how to fix this?
I can post everything you wish if it helps :)

**Comment by VISTALL** [comment]
Hello. You called Re-Import Unity project?

**Comment by VISTALL** [comment]
I will try reproduce this bug

**Comment by TheYellowArchitect** [comment]
> Hello. You called Re-Import Unity project?

Yup, at the root of the project
![14](https://user-images.githubusercontent.com/25630803/114196105-e91fe580-9905-11eb-8f6c-9bfd1b0b4ab0.PNG)

> I will try reproduce this bug

Well, it is a bizzare bug, and probably related to packages or something
I cannot code until I fix this so tell me if you want anything I can help with :+1:

**Comment by VISTALL** [comment]
Can you find file 'isteamfriends.cs' and open it in Consulo?

**Comment by TheYellowArchitect** [comment]
![14](https://user-images.githubusercontent.com/25630803/114197095-de198500-9906-11eb-8dfd-f929f6257cfa.PNG)

**Comment by VISTALL** [comment]
Oh. Steam API protected by desktop defines, which is not provided when UnityEditor is not resolved (Editor plugin).

You can add variable by hand here (https://klikr.org/99cd13aea3be698a6b84cfa939f3.png)

Or use plugin (https://consulo.help/plugins/consulo.unity3d/using_consulo_as_external_editor/) and reimport.

**Comment by TheYellowArchitect** [comment]
>Or use plugin (https://consulo.help/plugins/consulo.unity3d/using_consulo_as_external_editor/) and reimport.

I cannot use plugin because of an old issue, but it's no issue, so I went to put variable by hand

Any suggestion? Did I do something wrong? Perhaps it wants Steamworks with caps?

https://user-images.githubusercontent.com/25630803/114198833-9eec3380-9908-11eb-8b2d-e3626d5bf49f.mp4

**Comment by VISTALL** [comment]
Add 'UNITY_STANDALONE_WIN'

**Comment by VISTALL** [comment]
there 

```charp
#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif
```

protectors
> UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX

**Comment by TheYellowArchitect** [comment]
![14](https://user-images.githubusercontent.com/25630803/114199590-49645680-9909-11eb-8389-7c925348a882.PNG)

Bless you dude. Every time I have any issue with Consulo, you reply instantly to fix, yet you are just 1 person, and are not even paid for this. Incredible respect, and thank you for assisting me yet again <3

**Comment by VISTALL** [comment]
Thanks. But you need always add it on each reimport :(

**Comment by TheYellowArchitect** [comment]
It's alright, definitely better than not being able to code at all :heart: 
You won me a day of coding (I didn't expect a reply since tomorrow) so spending 1 minute for each re-import is already worth it xaxaxaxa

**Comment by VISTALL** [comment]
Hello. I add some hacky method for adding custom defines.(works for last nigthly builds)

file

Assets/consulo.rsp

with lines

```
-define:UNITY_ANDROID
```
