### ISSUE TITLE
Unity networking needs to be added to list of DLLs when importing projects

### ISSUE THREAD

**Issue by Hodkinson** [consulo/consulo-unity3d#20]
In my case, I added C/programfiles/unity/editor/data/unityextensions/unity/networking/UnityEngine.Networking.dll and the errors with the networking classes went away.

I'm not sure if the UNetWeaver or CecilTools mono libs are required, I added them too just in case.

**Comment by VISTALL** [comment]
unity 5.1?

**Comment by Hodkinson** [comment]
Yes, 5.1.1

**Comment by VISTALL** [comment]
Thanks for information. I will fix it after one week, due i dont have access to my PC.

**Comment by VISTALL** [comment]
In Progress

**Comment by nuggus** [comment]
Hi, I am new to unity networking, could you please tell me from where can i get UnityEngine.Networking.dll file

**Comment by VISTALL** [comment]
Why u need it? If u working inside Consulo or MonoDevelop - its autoimported with Unity 5.1+ version

**Comment by nuggus** [comment]
Thankyou for ur Reply. I am getting below error 

Assets/Standard Assets/Characters/ThirdPersonCharacter/Scripts/ThirdPersonUserControl.cs(3,19): error CS0234: The type or namespace name `Networking' does not exist in the namespace`UnityEngine'. Are you missing an assembly reference?

So  i found dll file is missing, if i am wrong please help me to solve this issue.

**Comment by VISTALL** [comment]
What Unity version u have? And its a Unity problem - please use their community forum http://unity3d.com/community

**Comment by nuggus** [comment]
i am using unity 5.0.2f1 personal

**Comment by VISTALL** [comment]
New unity networking introduced in 5.1 version

**Comment by nuggus** [comment]
oh, I will update to new version and try if my problem is resolved.

**Comment by nuggus** [comment]
VISTALL, do u have any idea on how to change the look of the default ThirdPersonCharacter in unity 5. I want to set up my own character

**Comment by VISTALL** [comment]
No - as i say, its Unity problem - and you need go to Unity community forum

**Comment by nuggus** [comment]
Issue Resolved, when I updated my Unity Version.
