### ISSUE TITLE
Unhandled Exceptions when editing .shader files with CGPROGRAM ... ENDCG block

### ISSUE THREAD

**Issue by TicTac-93** [consulo/consulo-unity3d#206]
Tested with Unity 2020.3.48 and 2022.3.14, Consulo 2023.8

When CGPROGRAM ... ENDCG is present, the editor will lock up and throw an exception (submitted via Consulo **[here](https://hub.consulo.io/public/errorReport/qiyaCK8eJLNFHoxKnF50XRFVetL7UhTVkZXeJOdvjN24aTKM)**).  Sometimes it will highlight the block, which I believe is intended behavior, but other times it will not.  In all cases, if those two lines are present it will throw an exception and behave oddly, specifically seeming to block new lines from being created.

**Comment by VISTALL** [comment]
Hello. I will chech today. Can you provide simple example? and/or gif/video of this bug

**Comment by VISTALL** [comment]
Reproduced

**Comment by VISTALL** [comment]
I fixed this issue. Fix avaliable in nightly chanell (https://consulo.help/platform/settings/platformAndPlugins/updateSettings/)

**Comment by TicTac-93** [comment]
Got it working, though I had to manually install Consulo v3411 -- The in-app updater was not working for some reason.
