### ISSUE TITLE
Cannot run project from Consulo when Unity Editor is open (Unity 5.1)

### ISSUE THREAD

**Issue by bfishman** [consulo/consulo-unity3d#21]
Hello. Great work, I love what you're doing here.

I've gotten Consulo to successfully build my Unity 5.1 project, and even run it when the Unity editor is closed. But if the Unity Editor is open, I get a failure with the following message in the log file:

``` text
 BATCHMODE ARGUMENTS:

-batchmode
-projectPath
C:/Users/Public/Documents/Unity Projects/Test Project
-buildWindowsPlayer
C:/Users/Public/Documents/Unity Projects/Test Project/out/production/Test Project/$ModuleName$.exe
-quit
Successfully changed project path to: C:/Users/Public/Documents/Unity Projects/Test Project
C:/Users/Public/Documents/Unity Projects/Test Project
It looks like another Unity instance is running with this project open.

Multiple Unity instances cannot open the same project.

Project: C:/Users/Public/Documents/Unity Projects/Test Project

(Filename: C:/buildslave/unity/build/Editor/Src/Application.cpp Line: 303)


Aborting batchmode due to failure:
Fatal error! It looks like another Unity instance is running with this project open.

Multiple Unity instances cannot open the same project.

Project: C:/Users/Public/Documents/Unity Projects/Test Project
```

I'm using the latest (as of right this moment) version of Consulo and the Unity3d Plugin. Any suggestions?

**Comment by VISTALL** [comment]
Hi. Yeah i known about this problem. For now - i dont known how communicate with  UnityEditor, when Editor is opened.

Unity working on REST api, but for now it not shipped.

I did not found way how fix it.

Batch mode have some another issues(like he dont building in debug mode, and debug is not working.

**Comment by bfishman** [comment]
Does this work for earlier versions of Unity? I've seen your gifs of debugging from Consulo.  

Anyway, understood that it's an issue talking to Unity. Feel free to close. Thank you again for your efforts.

**Comment by VISTALL** [comment]
Debug work if u attach to Editor, or attach to app (if it builded in debug mode by Editor)

**Comment by VISTALL** [comment]
MonoDevelop can compile project - but how i dont known. Trying to decompile assemblies, is bad idea.   Unity opened many their repositories https://github.com/Unity-Technologies but it hard to read, no docs:)

**Comment by bfishman** [comment]
![image](https://cloud.githubusercontent.com/assets/3529531/8446926/38306568-1f6e-11e5-98c8-eb6e18c875c8.png)

I am able to right-click scripts in the Unity Editor and edit them using Consulo, but not debug unfortunately. Is there an argument I need to pass to Consulo?

**Comment by bfishman** [comment]
Also, I've created a debug-build from the Editor. You say I can debug this with Consulo?

![image](https://cloud.githubusercontent.com/assets/3529531/8446970/afd1ba18-1f6e-11e5-825f-32f81fe5dbf7.png)

**Comment by VISTALL** [comment]
![](http://klikr.org/3d778b825d0120e58bf8ded90cdc.png)

You have this button? If u running Editor it will show one item:

![](http://klikr.org/c7cdbb99934c17ffa57bd2c1ef9c.png)

**Comment by bfishman** [comment]
Thank you!  That worked great. I can now use breakpoints.

Would you like help writing tutorials/documentation for this plugin?

**Comment by VISTALL** [comment]
It will be great. I dont have time to write all

**Comment by VISTALL** [comment]
About debug, it will show not only Editor - it will show an App  if u run outside Editor(with debug option)

**Comment by bfishman** [comment]
How do you make a debug run configuration? 

Also, for the write-up you will either have to give me access to contribute to the wiki, or perhaps I can create a fork of the plugin and you can pull the document. Not sure.

**Comment by VISTALL** [comment]
For now - u can only attach to apy desktop app.

**Comment by VISTALL** [comment]
I am enabled wiki, anybody can edit it https://github.com/consulo/consulo-unity3d/wiki

**Comment by bfishman** [comment]
Will edit. I still am not sure if I understand what you meant by "About debug, it will show not only Editor - it will show an App if u run outside Editor(with debug option"

I will start the tutorial now, will show how to point Consulo towards your Unity directory, how to link Unity Editor to Consulo, and how to attach Consulo to Unity process

**Comment by VISTALL** [comment]
Sorry :)

Batch mode(via command line) always ignore 'Script debugging' option. I did not found way how enable it.

That why - if u want debug 'Standalone App' outside Editor, u need compile app by Editor(not consulo)

**Comment by bfishman** [comment]
Hm. So I build an EXE with the editor, having 'Script Debugging' enabled. Then what?

FYI, almost done with the wiki.

**Comment by VISTALL** [comment]
Run it, and then try to attach, if all is ok - u will see another process to attach

**Comment by bfishman** [comment]
It's attaching but nothing is outputting to the console. Perhaps I have to have breakpoints enabled before compiling?

Also... I don't know what changed but now I'm having the "Multiple Unity instances cannot open the same project." problem again, but now after having successfully attached to the Unity Editor process...

**Comment by VISTALL** [comment]
i think unity process didnot closed(kill it by task manager)

Hm. I will test attach to 'Standalone App' later, maybe some regression.

**Comment by bfishman** [comment]
Standalone app - I got it to use breakpoints, was attaching during the "Launcher" window (where you choose resolution, etc"), but needed to attach once the game had actually started.

It was not showing console output (using 'print()'), however (this did work when attaching to the editor process).   Will try to kill unity process and try again, standby...

**Comment by bfishman** [comment]
Still no luck running from Consulo with Editor open. Not sure what changed, I may need to restart. (Unity process was not running)

**Comment by VISTALL** [comment]
Running from consulo is useless, no debug. 

Use only Editor for building app

**Comment by VISTALL** [comment]
I think need disable compilation & running inside Consulo, too many problems with it

**Comment by bfishman** [comment]
It may save you some headaches at least :)   

Just finished the wiki page, let me know if you want me to make changes or add anything else.

**Comment by bfishman** [comment]
https://github.com/consulo/consulo-unity3d/wiki/Setup-and-Usage

**Comment by VISTALL** [comment]
Oh, big thanks. 

Some correction. Microsoft .NET & Mono .NET is not needed for unity:)

Run configuration is not needed too. Attach working without it.

**Comment by VISTALL** [comment]
please use new issue https://github.com/consulo/consulo-unity3d/issues/22

dont spam here:)

**Comment by VISTALL** [comment]
Building via command line is dropped from code. Issue obsolete
