### ISSUE TITLE
Wiki: Setup Page

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-unity3d#22]
https://github.com/consulo/consulo-unity3d/wiki/Setup-and-Usage

**Comment by VISTALL** [comment]
Some correction. Microsoft .NET & Mono .NET is not needed for unity:)

Run configuration is not needed too. Attach working without it.

Project Structure can accessed via Start Page

![](http://klikr.org/c10b2593cac2dbccc0daa1f3e422.gif)

Unity Bundle always exists, if install in Default Path

**Comment by bfishman** [comment]
I'll make those changes tomorrow, heading to bed now.  Thanks for the GIF!  (still no attach, but I haven't restarted my computer yet so that might fix it)

**Comment by VISTALL** [comment]
restart dont fix it. It regression. I will check it when come home

**Comment by VISTALL** [comment]
It will be good if u dont miss info from this issues:

https://github.com/consulo/consulo-csharp/issues/279  - need call 'Sync Project' manually if project file changed by external tool

https://github.com/consulo/consulo/issues/108 - default memory values often too small for Unity develop

**Comment by bfishman** [comment]
I will start a new 'Troubleshooting' page

**Comment by VISTALL** [comment]
not bad. Thanks.

Maybe about memory link to original Wiki? Because this it can be a global issue - and fix is one for all. It hard to change text in all repositories

**Comment by VISTALL** [comment]
Can you split Run and Attach tutorial? Attch work without Run, and Run without Attach.

I thinking about disabling Running, and tutorial will became obsolete

**Comment by bfishman** [comment]
Okay, changes made. Is that what you meant?

**Comment by VISTALL** [comment]
Yeah that i mean(maybe split only in one page, but not matter) :smiley: thanks.

What u think about adding link to wiki inside README?

**Comment by bfishman** [comment]
I think that would be good

**Comment by VISTALL** [comment]
Can u add it at your fork? and create request. I cant choose what add to it.

**Comment by VISTALL** [comment]
I saw that u wrote "Green Plus" - on OS X, plus colored in black

**Comment by Taraweesh** [comment]
added command line args 
 --line $(Line) "$(File)"
to the wiki page. I know it works in windows but cannot test on mac.

**Comment by VISTALL** [comment]
Hi, i saw it. 

On OS X u cant set program parameters :cry:

**Comment by NickVolynkin** [comment]
Just made a few improvements, please check for mistakes. bfishman - great job done! Thank you for participation!

**Comment by NickVolynkin** [comment]
Taraweesh - thank you too! Will check this option on osx later.
