### ISSUE TITLE
UnityEngine.UI not found

### ISSUE THREAD

**Issue by ernestp** [consulo/consulo-unity3d#26]
UnityEngine.UI library not found for imported project.
Consulo: 1.0 #966
JVM: 1.8.0_40
Unity: 5.1.2f
Mac OS X: 10.10.4
Unity Plugin: 778

**Comment by VISTALL** [comment]
Hi again. If u have really unity plugin 778 - its too old. 

Current build is **1449**

**Comment by ernestp** [comment]
After update Unity plugin and reimport there is no problem with UI library.

**Comment by sunyikang** [comment]
@ernestp Hi ernestp, may I ask how to check the unity plugin version? And how to upgrade it?

**Comment by VISTALL** [comment]
![](http://klikr.org/06b3206dee2dfb7a3d9cdd3b18c2.png)

Here.

U can update all plugins by invoke Help -> Check for Updates

**Comment by sunyikang** [comment]
Thank you Vistall!!!
