### ISSUE TITLE
Unity plugin not work after update

### ISSUE THREAD

**Issue by ernestp** [consulo/consulo-unity3d#27]
On IDE start following message arrive:

Plugin Manager
 Plugin "Unity3D" was not loaded: required plugin "org.mustbe.consulo.javascript" not installed.  Disable Unity3D Open plugin manager

**Comment by VISTALL** [comment]
Please install **JavaScript** plugin by hands

**Comment by ernestp** [comment]
Seems is some mess here. I've downloaded new version of Consulo and all plugins is not updated.

**Comment by VISTALL** [comment]
Consulo dont have any bundled plugins. You need manually install it. 

But - mostly u can update it by clicking, Help -> Check for updates

**Comment by ernestp** [comment]
Yes, thanks, it worked )

**Comment by VISTALL** [comment]
Next - about UI library
