### ISSUE TITLE
Missed major preprocessor variable define if minor version is not equal zero, like 5.1

### ISSUE THREAD

**Issue by ernestp** [consulo/consulo-unity3d#28]
After project import one of project dependencies not found: DarkTonic.CoreGameKit
Code for this module included in sources. Tried to rebuild - doesn't help.

Consulo: 1.0 #966
JVM: 1.8.0_40
Unity: 5.1.2f
Mac OS X: 10.10.4
Unity plugin: 1449

Seems that problem is that Consulo not define UNITY_5 for compile. That brakes compilation logic for that module. Seems that this problem was not appears in older version of Unity plugin.

**Comment by VISTALL** [comment]
Preprocessor - is known issue of C# plugin, currenly is not fixed

https://github.com/consulo/consulo-csharp/issues/118

**Comment by ernestp** [comment]
Seems that variable UNITY_5_1 is defined.
But in Unity 5.1.2 code compiles fine. So seems that both variables UNITY_X and UNITY_X_X must be defined.

**Comment by VISTALL** [comment]
Oh - that bug, i will change title of this issue
