### ISSUE TITLE
automatic unity3d project reimport / refresh 

### ISSUE THREAD

**Issue by strobe** [consulo/consulo-unity3d#32]
please add some command/button that will allow to do consulo project recreation or updating if something has changed in unity generated VS solution files

(as reference of this feature take a look to IDEA sbt (scala build tool)(at scala plugin) tool window)

**Comment by VISTALL** [comment]
At root project directory - right click, Sync Project

**Comment by strobe** [comment]
thanks, 
is it really doing same job as project import from scratch with indexes update?

**Comment by VISTALL** [comment]
yeh

**Comment by VISTALL** [comment]
If find some bug - report pls

**Comment by strobe** [comment]
yes, sure I will 
thanks
