### ISSUE TITLE
[Ubuntu 15.10 x64] Unable to add Unity SDK

### ISSUE THREAD

**Issue by ghost** [consulo/consulo-unity3d#36]
Unity has released an experimental build of their Editor yesterday

I tried to add unity sdk from consulo, but i get this error:

"The selected directory is not a valid home for Unity3D"

I tried these directories:

/opt/Unity/
/opt/Unity/Editor/
/opt/Unity/Editor/Data

All of them doesn't work

**Comment by VISTALL** [comment]
Can u provide link for Linux binaries of Unity ?

Linux binaries is not supported

**Comment by ghost** [comment]
I can't access my linux partition now, but here is the installer http://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

**Comment by VISTALL** [comment]
Thanks

**Comment by VISTALL** [comment]
Fixed by https://github.com/consulo/consulo-unity3d/commit/d2509837c50f349d781fa77b5f3fd73da68c3810

Try update after half hour

**Comment by ghost** [comment]
Wow that was fast! thanks a lot :)
