### ISSUE TITLE
Consulo is freezy on Mac OS

### ISSUE THREAD

**Issue by minhdu** [consulo/consulo-unity3d#38]
Hi Consulo team, i'm using Consulo Unity IDE to write code, i very like it and guess Consolu can become a best solution to replace MonoDevelop for Unity developer on MacOS, but there is a critical problem that Consulo can freeze anytime when i am writing the code, i'm using OSX 10.10.5. Please have a consider to investigate and solve this problem!

**Comment by VISTALL** [comment]
I think i known a problem.

.NET/C# implemention can provide some garbage - because it not optimized too much.

Please check this wiki page https://github.com/consulo/consulo/wiki/Frequently-Asked-Questions

**Comment by minhdu** [comment]
@VISTALL thank for your reply, i was read wiki and try to adjust limit memory up to 2048m but there are nothing improved, Consulo keep freeze when the code suggestion popup is appear.

**Comment by VISTALL** [comment]
Try enable memory usage panel, settings>-apperance->show memory indicator.
If its not memory problem, i ill show how make CPU usage dump.

**Comment by VISTALL** [comment]
and your count of C# files

**Comment by minhdu** [comment]
@VISTALL I have 73 C# (.cs) files, here is screenshot of memory indicator:
http://postimg.org/image/cx5e248zd/
In my case, Consulo even never got more than 500Mb of memory

**Comment by minhdu** [comment]
Beside cs file, I also use some plugin in my project (that is in dll), do you think it is the reason of this issue?

**Comment by VISTALL** [comment]
I dont think so. I will write instruction how make CPU dump(its a problem for me, because i am not at home)

I will do my best

**Comment by minhdu** [comment]
Thank you, i'm waiting for your instruction! :)

**Comment by VISTALL** [comment]
Sorry - need wait Octoberm due even you will give me dump, i cant download it :(

**Comment by minhdu** [comment]
Yes, i'm still waiting...! :)

**Comment by minhdu** [comment]
@VISTALL maybe this issue is solved, i has downloaded the #1144 build and Consulo is now stop from freezing!

**Comment by VISTALL** [comment]
Nice one.

After few day test - please notify me about this issue.

**Comment by minhdu** [comment]
Yes, of course!

**Comment by VISTALL** [comment]
Any news?

**Comment by minhdu** [comment]
Sometimes, a lot of exception has been threw in the console (i has been submitted), it cause lag a bit then everything is back to normal, maybe freeze issue is solved, so please close it, thank for your support! :)

**Comment by VISTALL** [comment]
Some of them i saw - but i cant reproduce them. 

Thanks anyway
