### ISSUE TITLE
Consulo doesn't substitude $ModuleName$ variable when generate Unity executable.

### ISSUE THREAD

**Issue by sergerus** [consulo/consulo-unity3d#4]

**Comment by VISTALL** [comment]
On MacOS? If yes - change pls target

![](http://klikr.org/f0681f15a6e86caae9c5a9ca08b5.png)

**Comment by sergerus** [comment]
Change caption.

**Comment by VISTALL** [comment]
it generated $ModuleName$.exe file at file system? :)

**Comment by sergerus** [comment]
Yes. 
![modulenamebug](https://cloud.githubusercontent.com/assets/6523253/6036926/c715a0a4-ac6e-11e4-8bc9-cb922b1649bd.png)

**Comment by VISTALL** [comment]
Cant reproduce - with old unity project system, or with new import unity project system.

**Comment by VISTALL** [comment]
Unity plugin build is last?

**Comment by VISTALL** [comment]
Last is 674

**Comment by VISTALL** [comment]
Can try in another project - but dont use old project files, create new and then build project

**Comment by sergerus** [comment]
http://youtu.be/u4_d7Ni8lCE Consulo and all plugins have last versions.

**Comment by VISTALL** [comment]
Cant reproduce. Tried with new installation of consulo too. Idk. Can u attach  log - **Help -> Show Log In Explorer**.

**Comment by VISTALL** [comment]
https://github.com/consulo/consulo-unity3d/issues/11#issuecomment-87444238
