### ISSUE TITLE
Code suggestion when typing the lowercase letter

### ISSUE THREAD

**Issue by minhdu** [consulo/consulo-unity3d#40]
Hello @VISTALL , i have a suggest about "code suggestion popup" - i mean the popup show the list of method/field/property... when we typing a letter...

Example:
I have a class with name: MyClassName
When i typing "m" (lowercase), the popup doesn't show MyClassName, it only show when i typing exactly letter that is "M" (uppercase)

So, can you improve this thing?

**Comment by VISTALL** [comment]
Please change  code completion case sensitive, from **All** to **None**

Here 

![](http://klikr.org/46fbdbc1e65ea3ed41a74cd6500c.png)

**Comment by minhdu** [comment]
Oh sorry, I see, thank you! :)

**Comment by VISTALL** [comment]
Np. You cant known all options :)

**Comment by cupsster** [comment]
Please can this be added to WIKI? It definitevely helps with speed of codding :) It was bit frustrating for me from beginning as well but now I found solution I'm happy camper again.

**Comment by VISTALL** [comment]
Wiki is open for all users (https://github.com/consulo/consulo-unity3d/wiki)
