### ISSUE TITLE
'Change Signature' refactoring not working

### ISSUE THREAD

**Issue by MaDDoXbr** [consulo/consulo-unity3d#41]
It does change the calling methods parameters (weirdly, it just leaves new elements blank), but not the method signature itself. It returns a NullPointerException: null error in the console.

**Comment by MaDDoXbr** [comment]
![screen shot 2015-10-03 at 19 44 56](https://cloud.githubusercontent.com/assets/265085/10265447/459b849c-6a07-11e5-879e-70de3cf9e150.png)

**Comment by VISTALL** [comment]
Hi. I saw exception that you reported. I will fix it at this week

**Comment by MaDDoXbr** [comment]
Thanks for the quick response. Amazing work so far btw, congrats!

Em domingo, 4 de outubro de 2015, Valeriy Semenchuk <
notifications@github.com> escreveu:

> Hi. I saw exception that you reported. I will fix it at this week
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/consulo/consulo-unity3d/issues/41#issuecomment-145348039
> .

## 

---

Breno Azevedo da Silva

## @brenoazevedo

_Freakow_

**Comment by VISTALL** [comment]
Hi again. For now i cant reproduce this issue. But - i another but. Out / Ref types works bad

**Comment by VISTALL** [comment]
Hi. I fixed related problem with change signature dialog (wrong out/ref types). A NPE - i am trying to reproduce, but no success.

I will try to search way to repeat - but it another issue

**Comment by MaDDoXbr** [comment]
Thanks again Valeriy. Last version I've tried change signature was working
fine, I found no more issues.

On Mon, Nov 9, 2015 at 3:57 PM, Valeriy Semenchuk notifications@github.com
wrote:

> Hi. I fixed related problem with change signature dialog (wrong out/ref
> types). A NPE - i am trying to reproduce, but no success.
> 
> I will try to search way to repeat - but it another issue
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/consulo/consulo-unity3d/issues/41#issuecomment-155140079
> .

## 

---

Breno Azevedo da Silva

## @brenoazevedo

_Freakow_
