### ISSUE TITLE
Int and Int32 are being reported as incompatible for comparison

### ISSUE THREAD

**Issue by MaDDoXbr** [consulo/consulo-unity3d#43]
Unity internally converts Int32 to Int when needed, making comparisons (<, =, >) of these two types compile and work fine. Nevertheless Consulo reports an incompatible-type error, as shown in the attached screenshot. For the record, if I int-cast the Int32 property the error goes away, but this shouldn't be needed.
<img width="776" alt="int_vs_int32" src="https://cloud.githubusercontent.com/assets/265085/10968472/848f0c5e-83a8-11e5-9c70-872d97ecceff.png">

**Comment by VISTALL** [comment]
Hi. Can you say your C# Plugin Version(you can get it in Plugin page).

Looks like https://github.com/consulo/consulo-csharp/issues/313 but it was fixed in a week ago

**Comment by MaDDoXbr** [comment]
Updating the plugin worked out that issue indeed, thanks - but another showed up, in property int getters. This wasn't showing as an error previously.
<img width="532" alt="property" src="https://cloud.githubusercontent.com/assets/265085/10976905/53d64168-83d5-11e5-97ed-30d5dce0ac8a.png">

**Comment by VISTALL** [comment]
Hi. I will reopen - old issue.

Please for C# bugs use C# repository.

Thanks
