### ISSUE TITLE
Negating an object to test its nullity error

### ISSUE THREAD

**Issue by mnandrei90** [consulo/consulo-unity3d#48]
For the lines of code below, the error appears at "if".
<code>
var obj = null;
if (!obj ) break;
</code>

The error message is:
<code>
!   (p0:System.Boolean) cannot be applied
to (p0:System.Boolean)
</code>

**Comment by VISTALL** [comment]
Hi. Thanks. Its regression

simple code

``` csharp
using UnityEngine;

public class RegressionTest
{
    public static void Main()
    {
        GameObject gameObject = null;

        if(!gameObject)
        {
            return;
        }
    }
}
```

**Comment by VISTALL** [comment]
Fixed. After one hour you need update C# plugin
