### ISSUE TITLE
Unity player not shown

### ISSUE THREAD

**Issue by gregorytkach** [consulo/consulo-unity3d#5]
Hi. I have issue --> http://prntscr.com/61wh1h . I have installed 4.6.0 Unity,  Mac OS 10.10.3, Web Player Unity also installed.

**Comment by VISTALL** [comment]
I am dont tested with web player(and iOS support is not implemented)

**Comment by gregorytkach** [comment]
How I can debug my project? Consulo Unity3D plugin didn't find any installed player? And button "run project" disabled. I was learn UnityProcessDialog.java, UnityPlayerService.java and scan used ports on my laptop and Unity Editor didn't use any port which included in "UnityPlayerService::ourPorts". But I have one which not listed --> http://prntscr.com/6253fg Mb. it help us resolve this issue.

**Comment by VISTALL** [comment]
Consulo provide only C# code edit. For unknown me reason - unity app what compiled from command line(by consulo) dont have scripting debug, and attaching is failed.

**Comment by gregorytkach** [comment]
Do you have in your todo list debug feature for unity app/player/editor or you think it impossible right now?

**Comment by VISTALL** [comment]
Plugin debug default app for mac + win. But with iOS  - no impl. WebPlayer i dont tested.

No hands for do all)

**Comment by VISTALL** [comment]
Incomplete.

Now we can attach to Editor process, not only app

![](http://habrastorage.org/files/d52/88b/f67/d5288bf674a14c6399e45f22d6388e8a.gif)

**Comment by robert-wallis** [comment]
I can confirm this does not work on Mac, consulo looks for the exe file on Windows, even when running it in OSX.

**Comment by VISTALL** [comment]
Hi. Not only .exe file 

https://github.com/consulo/consulo-unity3d/blob/master/src/org/mustbe/consulo/unity3d/run/debugger/UnityProcessDialog.java#L97

Wait few mins i will check it.

**Comment by VISTALL** [comment]
![](http://klikr.org/667da427c7155c1804921fc65b01.png)

Consulo saw Unity Editor. But i cant test debug - due i have 4.6 unity, need 5. After 10 min, i will test it

**Comment by VISTALL** [comment]
I got exception. We moving to another issue https://github.com/consulo/consulo-unity3d/issues/13
