### ISSUE TITLE
Consulo doesn't pick up dll's as part of the project

### ISSUE THREAD

**Issue by UCh** [consulo/consulo-unity3d#50]
If I add a C# DLL in a unity folder, the consult project didn't pick up that dependency and I need to add it manually.

**Comment by VISTALL** [comment]
Please say 
-  library path

**Comment by VISTALL** [comment]
And module name what missed dependency

**Comment by rogeratplumbee** [comment]
To reproduce:
- Copy a valid C# dll inside assets (in assets/plugins for example)
- In MonoDevelop the code from the dlll is available when I use auto import
- In Consulo I need to open the module config and add the dll as dependency manually in order to make Consulo aware of it

**Comment by VISTALL** [comment]
Read https://github.com/consulo/consulo-unity3d/wiki/3.-Troubleshooting second part

**Comment by VISTALL** [comment]
any news?

**Comment by UCh** [comment]
My bad, apologies. Manually sync fix the issue, cheers!
