### ISSUE TITLE
Can not import unity project 

### ISSUE THREAD

**Issue by Taraweesh** [consulo/consulo-unity3d#52]
here is the log:
5:16:37 PM IllegalArgumentException: Argument for @NotNull parameter 'firstItem' of com/intellij/openapi/roots/ui/configuration/SdkComboBox.setSetupButton must not be null: Argument for @NotNull parameter 'firstItem' of com/intellij/openapi/roots/ui/configuration/SdkComboBox.setSetupButton must not be null

**Comment by subiron** [comment]
same here, 
I have installed consulo yesterday -everything was working fine until today's update ( together with plugins)

**Comment by VISTALL** [comment]
Hi. Sorry. Fixed
