### ISSUE TITLE
Unity debug variables watch does't work for structures

### ISSUE THREAD

**Issue by Sipaha** [consulo/consulo-unity3d#53]
Hi, I really like consulo, but one problem not allow use it as a main IDE for Unity.

I define variables of some structures (Vector2, IntVec2) in my class:

![image](https://cloud.githubusercontent.com/assets/3995047/12084928/fd9cbf8c-b2e3-11e5-99fc-94f2c05ec2f6.png)

When I attach Consulo to Unity editor, start game and stop at break point, I got this:

![image](https://cloud.githubusercontent.com/assets/3995047/12084999/1cdb3454-b2e5-11e5-8dbe-ad50e8c2c8f3.png)

In Event Log I found this exceptions: [exceptions.txt](https://github.com/consulo/consulo/files/76927/exceptions.txt)

**Comment by VISTALL** [comment]
Hi. About first exception - please update Java plugin.

About second - i will fix it.

Sorry but watchers dont supported fully. About value - i will check it, maybe my mistake

**Comment by VISTALL** [comment]
Yeah, struct values have problems in debugger

**Comment by VISTALL** [comment]
ref to debugger lib: https://github.com/consulo/mono-soft-debugging/issues/3

in progress

**Comment by VISTALL** [comment]
Please test new plugins build(.NET plugin + C# + Unity3D) after one hour. I had fixed value reading and value evaluation

Thanks for issue
