### ISSUE TITLE
Content of variables doesn't displayed for some structures and all enums in debug mode

### ISSUE THREAD

**Issue by Sipaha** [consulo/consulo-unity3d#54]
Hi, after [this](https://github.com/consulo/consulo-unity3d/issues/53) fix all types are defined correctly, but there are still some problem. Content doesn't displayed for some structures:

![image](https://cloud.githubusercontent.com/assets/3995047/12099375/3e06b17c-b352-11e5-8160-655e4b6104ab.png)

UnityEngine.\* structures which works great:
Color, Rect, Matrix4x4

structures with problem:
Vector2, Vector3, Quaternion

This problem also actual for enums:

![image](https://cloud.githubusercontent.com/assets/3995047/12099651/03436006-b354-11e5-8e46-63ab0eaa4168.png)

Also I think after variable name and type we should see ToString() result if this function was defined or nothing otherwise. Example from Intellij IDEA 15:

![vars_as_tostring](https://cloud.githubusercontent.com/assets/3995047/12099773/c2d9a56a-b354-11e5-9bb9-ad4d424091e7.jpg)

If this would be implemented, then problems described above would be not critical.

**Comment by Sipaha** [comment]
Example from MonoDevelop:

![image](https://cloud.githubusercontent.com/assets/3995047/12109024/0d8ff624-b3a8-11e5-8458-984cfe26bb6b.png)

and Visual Studio:

![image](https://cloud.githubusercontent.com/assets/3995047/12109029/19861f08-b3a8-11e5-9fbe-56f58161031d.png)

**Comment by VISTALL** [comment]
Thanks. I will review node presentation.

**Comment by VISTALL** [comment]
Hi. I done with Struct & Enum values. Test it after one hour (require updates for .NET Core & C# plugins)

Thanks!
