### ISSUE TITLE
Unity Editor crashes in debug mode on classes extended from MonoBehaviour

### ISSUE THREAD

**Issue by Sipaha** [consulo/consulo-unity3d#55]
This problem appeared after today changes. Reason is something with acces violation:

KERNELBASE.dll caused an Access Violation (0xc0000005)
  in module KERNELBASE.dll at 0033:e7f38b9c.

[error.txt](https://github.com/consulo/consulo-unity3d/files/78244/error.txt)

**Comment by VISTALL** [comment]
Idk - i cant repeat it. I working with Unity while testing, and its never crashed.

**Comment by Sipaha** [comment]
Ok, I will try collect more information about the problem

**Comment by Sipaha** [comment]
Maybe this video and test project will help to repeat it

https://youtu.be/AJPo0dafIZg

[UnityEditorCrashTest.zip](https://github.com/consulo/consulo-unity3d/files/78373/UnityEditorCrashTest.zip)

**Comment by VISTALL** [comment]
lol

litte later i will test it in other Unity builds, maybe its a Unity bug

Thanks

**Comment by VISTALL** [comment]
Reproduced. Thanks

**Comment by VISTALL** [comment]
```

You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  MonoBehaviours can only be added using AddComponent().  Alternatively, your script can inherit from ScriptableObject or no base class at all
UnityEngine.MonoBehaviour:.ctor()
NotBehaviour:SomeMethod() (at Assets/NotBehaviour.cs:10)
TestScript:Start() (at Assets/TestScript.cs:8)

```

Strange

**Comment by VISTALL** [comment]
Cant repeat at MonoDevelop. **null** value exists too, but no crash when i go inside

**Comment by Sipaha** [comment]
> You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.

Yes, "new MonoBehaviour()" here just for test and some versions of Unity may show error like this. Here test project with tag "Test" on GameObject and "GameObject.FindGameObjectWithTag("Test").GetComponent<TestScript>()" instead of "new MonoBehaviour()"
[UnityEditorCrashTest.zip](https://github.com/consulo/consulo-unity3d/files/78437/UnityEditorCrashTest.zip)

Problem reproduced if breakpoint located above of behaviour initialization.

> null value exists too

I think **null** here is just ToString realization and not bug. Also Unity have custom behaviour for '==' operator which can return true in comparison with null, but it's can be not true.

**Comment by VISTALL** [comment]
Fixed. Please update .NET plugin after one hour
