### ISSUE TITLE
'ClassName': Cannot derive from static class 'UnityEngine.MonoBehaviour'

### ISSUE THREAD

**Issue by SillentAssembly** [consulo/consulo-unity3d#56]
The error appears on all classes extending the MonoBehaviour. Did NOT have this before. Maybe it doesn't belong on Unity3D plug-in tho.
http://prntscr.com/9ojnk4

**Comment by VISTALL** [comment]
Hi. Thanks for report, its regression. Its ok, you created issue and its good.

**Comment by VISTALL** [comment]
After one hour you can update C# plugin, and isse will resolved
