### ISSUE TITLE
nunit.framework should be added as external library

### ISSUE THREAD

**Issue by hrmoller** [consulo/consulo-unity3d#57]
When creating a standard test suite using the Editor Test Runner `Assert` is not recognised by Consulo.

Manually attaching  `/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/EditorTestsRunner/Editor/nunit.framework.dll` as external library seems to fix the problem.

Reproduce it by simply opening Editor Test Runner in an empty scene, hit the Create editor test button and open the generated file in Consulo. The Assert keyword on line 20 will be marked as en error.

Using Unity 5.3.1f1 on a Mac.

**Comment by VISTALL** [comment]
Now library 'nunit.framework' will be added to Editor modules. Use sync project for adding it.

As part of this issue - i created new https://github.com/consulo/consulo-unity3d/issues/58 (Test integration). Idk when i will implement it, but will be good run tests inside Consulo

**Comment by VISTALL** [comment]
Thanks

**Comment by hrmoller** [comment]
Perfect. Yeah, running tests from Consulo would be cool!

**Comment by VISTALL** [comment]
Hi. I am searching people how will test new builds (when it will stable) with Test Integration. You can help me with it?

**Comment by hrmoller** [comment]
I can try:-)

**Comment by VISTALL** [comment]
Ok. I will write here maybe. For now - Consulo can communicate with Unity(and Unity with Consulo). And Editor plugin can run **tests**. Current ploblem is **unity sync**, after source modify - need a time for Unity (searching way how improve it)

![](http://klikr.org/758199375bc622524fba83fce6d4.png)

**Comment by kosz78** [comment]
I cannot open run view for TestMe test and TestMe decorated as Class, not unit test class

**Comment by VISTALL** [comment]
Current version of NUnit plugin does not support Unity. But i am already
working on it in branch. I have only one problem, when i fix it, i will
push into master

**Comment by VISTALL** [comment]
I am pushed my changed to master. And now NUnit tests flagged as Tests. 

And.

U can try run it inside Consulo via new run configuration type Unity Test. But be care with it (**dont use it without Version Control**), because it have full access to Scene file, and can change

**Comment by VISTALL** [comment]
And need update UnityEditor consulo plugin https://github.com/consulo/UnityEditorConsuloPlugin

For now it have few problems with refresh

**Comment by onMouseUp** [comment]
Is there a solution for refreshing problems?

**Comment by VISTALL** [comment]
For now - i can't fix. When UnityEditor is out of focus, he can't  refresh (and reload project). It's 50 vs 50. Sometimes all ok, sometimes not.

**Comment by avvakhnin** [comment]
@VISTALL, 
Hello, what resolution on this bug? Do I still have to add the plugin manually?
Consulo highlight TestTools as error. But all problems pass when I add "TestRunner" as "Standart library" on "Modules" tab.

Linux
Unity3d - 2018.2.0b5
Consulo - 2010
Last version of UnityEditorConsuloPlugin2017.2.dll

![testtoolshighline](https://user-images.githubusercontent.com/31824236/40886057-f67b85f0-6739-11e8-8ab6-47161d5a0708.png)

![testrunneradd](https://user-images.githubusercontent.com/31824236/40886059-ffc3ced8-6739-11e8-991c-bef468e225bb.png)

**Comment by VISTALL** [comment]
Hello. Looks like you found new issue. In theory they add new library, or bug in library reading.

I will check it after my holidays(around two weeks). 

Can you create a new issue?

Thanks

**Comment by avvakhnin** [comment]
Yes, ok.
Today I will also check it on another computer where Windows 10 is installed. 
And after that I'll create a new issue.

**Comment by avvakhnin** [comment]
#155
