### ISSUE TITLE
Unity builtin keywords

### ISSUE THREAD

**Issue by cupsster** [consulo/consulo-unity3d#60]
Duno if it is only me but I'm missing keyword highlighting for most common components.. Can this be setup in some way? I just recently installed it and spend some time in settings but I was unable to figure this out.

**Comment by cupsster** [comment]
My bad, apologies. I opened only one file from inside of unity project so it wont loaded up all references. This thing is working perfectly. Just uninstalled VS2015! I may have found new favourite editor. You've done great job.

**Comment by VISTALL** [comment]
Ok, thanks.
