### ISSUE TITLE
XmlAttribute

### ISSUE THREAD

**Issue by cupsster** [consulo/consulo-unity3d#61]
using System;
using System.Xml;
using System.Xml.Serialization;

XmlAttribute tag is not recognized.. I'm using it in custom class under custom namespace like this:
[XmlAttribute("CustomName", Type = typeof(float))]

It offers me Use 'System' ?

**Comment by VISTALL** [comment]
Hi. I repeated problem. AutoImport trying to suggest for import System.Type for property. Its a bug.

I will fix it in a few days(maybe today)

**Comment by VISTALL** [comment]
Fixed. Please update C# plugin after one hour
