### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cupsster** [consulo/consulo-unity3d#62]
Hi I'm getting this error:
[http://i.imgur.com/peL15Ke.gif](url)
![alt text](http://i.imgur.com/peL15Ke.gif)

What can I do about it? It is really annoying and I'm not sure if this comes from Consulo or Editor plugin. I have updated all plugins to their latest versions but can't launch IDE by double clicking on file in Unity.

**Comment by cupsster** [comment]
To give you more details: This only happen when Edit > Use Consulo as External Editor is checked in menu. When I uncheck it it works just fine... Strange, I have both --line $(Line) "$(File)" and DLL placed in correct location and with correct version of editor I'm using.

**Comment by VISTALL** [comment]
Its a current limitation, Consulo plugin cant start Consulo, need start it manually
