### ISSUE TITLE
Navigation from prefab to scene

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-unity3d#64]

**Comment by VISTALL** [comment]
Cant find way how determine it

**Comment by sfjohansson** [comment]
hmm in what sense?

**Comment by VISTALL** [comment]
Unity scene file did not contains GUID of prefab

**Comment by sfjohansson** [comment]
Hmm I on thin ice here when it comes to my understanding as have not dig into it...so you have the prefabs...and the GUID stuff in the scene files are listed under m_modifications...I i.e. all changes you made in the inspector to the components on the prefab.

`m_Modifications:
    - target: {fileID: 400000, guid: 2e0e49bdcbac4a14bb1351a24beecc59, type: 2}
      propertyPath: m_LocalPosition.x
      value: -3.39185977`

**Comment by VISTALL** [comment]
Can you send me scene & prefab(with meta files)  ? (via email)

**Comment by sfjohansson** [comment]
Yeah no problem give me a few min.

**Comment by sfjohansson** [comment]
Sent, zipped a super mini project!

**Comment by VISTALL** [comment]
Hm!!

**Comment by VISTALL** [comment]
:D looks like, i am bad UnityEditor user)

**Comment by VISTALL** [comment]
Yeah - i found reference, thanks.

**Comment by sfjohansson** [comment]
Not as bad as IDE developer as I am... =O Feel free to ask if you wonder...I've been using unity for 4 years...it's too complex to know everything but hopefully I learned a few things... :)

**Comment by sfjohansson** [comment]
...or have ideas of stuff to implement...

**Comment by VISTALL** [comment]
Implemented
![](http://klikr.org/d4886d65fd0fd75586a69a51a526.png)

**Comment by VISTALL** [comment]
Update plugin after 30 min - and maybe need call Invalidate cache

**Comment by sfjohansson** [comment]
hehe...I can't believe it...pretty awesome...I'll grab latest after lunch...and take it out for a spin :)

**Comment by VISTALL** [comment]
In last build - navigation is not work, i fixed it

https://github.com/consulo/consulo-unity3d/commit/497abc85431203aa33cb25903be0a7881f7a444e

**Comment by sfjohansson** [comment]
No worries, I'll give it some more time :)

**Comment by sfjohansson** [comment]
I got latest now :) ...do you have walk through guide to test?

**Comment by VISTALL** [comment]
Try to open prefab only)

**Comment by sfjohansson** [comment]
So open a prefab file in consulo?

**Comment by VISTALL** [comment]
yes

**Comment by sfjohansson** [comment]
so I'm getting a plain text file with no added navigation options

**Comment by VISTALL** [comment]
Try to open test project(what u give me)

**Comment by sfjohansson** [comment]
Yeah cool...so it seem somewhat broken..in the way that first I don't get the scene reference gutter icon..I imported project afresh ..but still no luck.

I got the UnityEditorConsuloPlugin4.6 plugin in the project, I'm running unity 4.7.1

**Comment by sfjohansson** [comment]
I can see in the file explorer that prefabs are recognised as unity files through the icon

**Comment by VISTALL** [comment]
Plugin not matter. 

You changed Asset write mode ? (need Force Text)

**Comment by sfjohansson** [comment]
ahh yeah...it's a new project...my bad let me have another go

**Comment by sfjohansson** [comment]
Cool seem to be working..getting some errors in editor if I choose to navigate using the unity gutter icon:

Failed to unpersist: Not loaded ID: 116 FileID: 173854
UnityEditor.EditorApplication:OpenScene(String)
MustBe.Consulo.Internal.<Process>c__AnonStorey1:<>m__1()
MustBe.Consulo.Internal.<RunInMainThread>c__AnonStorey0:<>m__0()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by sfjohansson** [comment]
Maybe add header to the pop ups to sort stuff....here is as an suggestion for the hover pop up:

https://dl.dropboxusercontent.com/u/14611821/Temp/Consulo_ListPrefabs%3Ascenes%20Suggestion.png

**Comment by VISTALL** [comment]
Grouping - hard to add.

But, about absolute path - i will replace it by relative path

**Comment by sfjohansson** [comment]
Hmm..another solution could be right click and choose between show scenes/prefabs... unless that of course is also trouble. The fact that you can find the dependencies is awesome.. Especially as a lot of people prefer to build stuff in code with prefabs rather than drag stuff into scenes.

**Comment by VISTALL** [comment]
Now relative path will show. 

![](http://klikr.org/98d2c9891cb87662940d37ad3281.png)

And i added sorting (scenes then prefabs)

**Comment by VISTALL** [comment]
I am idiot. You show **example** for tooltip. Tooltip is html code, and i can make groups) 

But not for popups

**Comment by VISTALL** [comment]
![](http://klikr.org/f14605b0f2f4f2f66da5fb4298b8.png)

**Comment by sfjohansson** [comment]
Lucky pick from my side to demonstrate what I was thinking... =O

Organisation is definitely important to make the feature useful, as you can see on a larger project:

![consulolonglist](https://cloud.githubusercontent.com/assets/912814/13683534/12d9b266-e6ff-11e5-981b-ed52cd7023ba.jpg)

For the non tooltip one solution could be two split it into two gutter icons as that would also match how unity shows prefabs and scene files..like this:

![consulowithprefabiconexample](https://cloud.githubusercontent.com/assets/912814/13683556/3750ba68-e6ff-11e5-80a5-171fcebe0298.jpg)

What do you think?

**Comment by VISTALL** [comment]
Wow

**Comment by VISTALL** [comment]
I will think today how fix it

**Comment by VISTALL** [comment]
Problem with linemarker - if Unity have another assets with class including, will be bad

**Comment by sfjohansson** [comment]
Good morning! Hmm..if both of them gives a pop up lists..just like the scene line marker?

**Comment by VISTALL** [comment]
But if more that two icons

A B C    public class A {}

that bad

**Comment by sfjohansson** [comment]
Just been awake for 1 a minute..so my brain is probably half a sleep. 

Would there ever be more than two icons? 

There is one icon for scenes, and one icon for prefabs...clicking on any of them would provide a popup which list all references...one shows a list with all scenes referencing a script and the other a list of all prefabs referencing a script

**Comment by VISTALL** [comment]
![](http://klikr.org/9da8c87247f245d42ed52bb5909e.png)

**Comment by sfjohansson** [comment]
Ahh yeah...there could be some other kind also, so in one build of consulo my gutter got screwed up and I had like five of those scene markers in a row and my gutter was wider so it seems to be adjustable to fit more into it.

**Comment by VISTALL** [comment]
If i placed 3 icons, it will be too wide (gutter panel). And after 4 icons - it will be sucks

**Comment by sfjohansson** [comment]
hehe yes, I can see it could become a growing problem... I personally mostly hide the explorer on the side so I only have code tab open..so it wouldn't do me harm too much harm with a wider gutter but yes 4 icons would start eating into the active area.. =O

**Comment by VISTALL** [comment]
I limited tooltip(now will show only ten items per group)

**Comment by sfjohansson** [comment]
Cool...I'd have more than that in a lot of cases...If not everything is shown...the value decreases as it can't be trusted for refactoring  but as you can't scroll in a tooltip...it wont work anyway so i guess that is fine.

Maybe for the gutter icons..is it possible to have a unity gutter config in preferences?
(So people can have an ultra slim... i.e. only line numbers, unity combo icon or scene+prefab icon) 

one other solution could be to combine just one gutter with key a key pressed...nothing pressed..list= shows everything... click and press cmd for just scenes and alt for just prefabs...

But yeah you could try to put in that extra gutter icon for a a build or two and see what people think..
