### ISSUE TITLE
Consulo mark internal generic class as an error but it's not

### ISSUE THREAD

**Issue by rogeratplumbee** [consulo/consulo-unity3d#65]
I'm using this state machine library:

https://github.com/dotnet-state-machine/stateless

The class: 

```
public class StateMachine<TState, TTrigger>
```

has an internal public class: 

```
public class Transition<TState, TTrigger>
```

I'm creating this code:

```
bootstrap = new StateMachine<string, string>("Started");

        bootstrap.Configure("Started")
        .OnEntry(OnEntryState)
        .Permit("LoadMath", "LoadingMathModel");
```

And the the OnEntryState:

```
void OnEntryState(StateMachine<string, string>.Transition transition) {
        Debug.Log("Trigger " + transition.Trigger + " Transition from " + transition.Source + " to " + transition.Destination);

    }
```

Consulo mark the type of the parameter as an error:

`StateMachine<string, string>.Transition`

but the code is correct, compile and do the expected job.

![screen shot 2016-03-17 at 11 06 36](https://cloud.githubusercontent.com/assets/5928367/13844228/6762cf3a-ec30-11e5-8633-9e53f91a9f54.png)

If I change the signature to this:

```
void OnEntryState(StateMachine<string, string>.Transition<string, string> transition) {
        Debug.Log("Trigger " + transition.Trigger + " Transition from " + transition.Source + " to " + transition.Destination);

    }
```

The error disappear in Consulo but the code is incorrect and doesn't compile.

**Comment by VISTALL** [comment]
Hi. I think it was fixed (see this report https://github.com/consulo/consulo-csharp/issues/372).

Can you say  C# plugin version?

![](http://klikr.org/5a49acf26583d44e3983581812c7.png)

I think you need only call About -> Check for updates

**Comment by rogeratplumbee** [comment]
I just updated Consulo to the latest build and is fixed, yes. Apologies! 
PD You're so quick fixing bugs that you fix them before I finished typing :D

**Comment by VISTALL** [comment]
Please report any other code issues or features. Most C# problems you can report here https://github.com/consulo/consulo-csharp

Thanks
