### ISSUE TITLE
'yield' is not resolved

### ISSUE THREAD

**Issue by TeorikDeli** [consulo/consulo-unity3d#66]
I commented on an old (closed) issue at consulo-csharp project earlier, but I think the problem is unity3d plugin. I can reproduce it everytime (tried with other computers too).

Consulo v1291
C# v2800
.NET Core v2332
Unity3D v2311
OS X 10.11.3/4

The second one is from an Unity project (using UnityEngine & System.Collections), the first one is consulo-charp issue #163 example.

<img width="379" alt="ekran resmi 2016-03-22 01 19 17" src="https://cloud.githubusercontent.com/assets/9395555/13937456/a7084624-efcd-11e5-8a41-c1b54b4b9394.png">
<img width="381" alt="ekran resmi 2016-03-22 01 18 03" src="https://cloud.githubusercontent.com/assets/9395555/13937455/a702e828-efcd-11e5-9c6f-379be5b6bfcf.png">

**Comment by VISTALL** [comment]
I will check at morning. Thanks

**Comment by VISTALL** [comment]
Hm. I cant reproduce it 

(unity project - all ok)
![](http://klikr.org/6fa3ce0d5b65bce876187dd4b7fe.png)

**Comment by TeorikDeli** [comment]
That's interesting =/ By the way, I didn't tried on a Windows. Is your OS is Windows? I don't have any .NET SDK, I'm only using Unity3D SDK

These are from my project structure

<img width="1120" alt="ekran resmi 2016-03-22 12 59 02" src="https://cloud.githubusercontent.com/assets/9395555/13949501/1c6ef74a-f02e-11e5-97db-d14b3e1f0023.png">
<img width="518" alt="ekran resmi 2016-03-22 12 59 20" src="https://cloud.githubusercontent.com/assets/9395555/13949498/1c6cb61a-f02e-11e5-9718-44b46974fc31.png">
<img width="446" alt="ekran resmi 2016-03-22 12 59 44" src="https://cloud.githubusercontent.com/assets/9395555/13949499/1c6f1c3e-f02e-11e5-936d-c71cf97cafce.png">
<img width="419" alt="ekran resmi 2016-03-22 12 59 50" src="https://cloud.githubusercontent.com/assets/9395555/13949500/1c6f6a04-f02e-11e5-8469-0250e5b4cea3.png">

Thanks

**Comment by VISTALL** [comment]
Its ok. Strange

**Comment by TeorikDeli** [comment]
Yeah. I tried again with fresh install consulo & plugins on OS X, still the same =/ Is there any setting to disable this inspector message for yield?

By the way, the best IDE for Unity 👍🏻  I'm recommending consulo to all the Unity devs around me 😂 Thanks for rescuing us from the MonoDevelop.

**Comment by VISTALL** [comment]
You cant - its parsing problem. I have no idea why you catch this error. Can you create empty unity project with this file - and send me it?

**Comment by TeorikDeli** [comment]
[Finger Ball.zip](https://github.com/consulo/consulo-unity3d/files/184022/Finger.Ball.zip)

I didn't delete the .consulo directory.

**Comment by VISTALL** [comment]
Its good. Thanks

**Comment by VISTALL** [comment]
![image](https://cloud.githubusercontent.com/assets/542934/13951022/686b522c-f03f-11e5-8674-96f39218eab2.png)

**Comment by VISTALL** [comment]
Can you say you locate in system? and say file encoding

**Comment by VISTALL** [comment]
I tested with your github locate **Turkey** and think i known a problem

**Comment by TeorikDeli** [comment]
System locale is Turkish (tr_TR) and file encodings are should be UTF-8.

And, yeah locale is the problem. =/

<img width="404" alt="ekran resmi 2016-03-22 14 48 37" src="https://cloud.githubusercontent.com/assets/9395555/13952105/32317148-f03d-11e5-9cbb-f53793f21f54.png">
<img width="1134" alt="ekran resmi 2016-03-22 14 52 26" src="https://cloud.githubusercontent.com/assets/9395555/13952193/ba671126-f03d-11e5-8c49-4b470e76d138.png">

If I change 'yield' to 'yıeld' the parsing error goes, but of course it should be 'yield'. How can I fix the library files?

**Comment by VISTALL** [comment]
Yeah. You got it :+1: 

I will push fix now - and you can update plugin C# after 30-60 minutes.

Its will fix all issues with library & source files

**Comment by TeorikDeli** [comment]
Thanks a lot! 👍🏻
