### ISSUE TITLE
Unit test output not visible

### ISSUE THREAD

**Issue by UCh** [consulo/consulo-unity3d#67]
Running Unity unit test from Consulo works like a charm, but console output from Unity doesn't appear on the IDE console, forcing you to look at the Unity IDE test runner window.

**Comment by VISTALL** [comment]
Nice - i was waiting this answer (due i dont have Unity projects)

I will think about it. I known - how get info from console, but don't have time to implement it (in C# & java code)

**Comment by UCh** [comment]
Probably no-one asked before because TDD and testing in general is sadly not that popular in Unity as in other environments :D I can provide a project sample if that helps.

**Comment by VISTALL** [comment]
Not needed. I said that i don't have Unity projects(production) but i have many test unity projects.

I have question. How you print to console inside tests ? Unity test system is not handled many options(i missed **sout** output handling for example)

**Comment by VISTALL** [comment]
Or you use **Debug.Log** ?

**Comment by rogeratplumbee** [comment]
The test output is in a different file. If you run the test calling Unity from command line, you can decide the path for the output, but no idea where is the default place.

**Comment by VISTALL** [comment]
Consulo is not used Unity command line - due limitation (one instance per pc)

**Comment by VISTALL** [comment]
Oh. I missed messages from Assert, etc. Working on it

**Comment by VISTALL** [comment]
I implemented many missed parts. Try it - and give me result.

You need update Consulo Plugin for Unity(https://github.com/consulo/UnityEditorConsuloPlugin) & Unity Plugin for Consulo  (:D)

**Comment by rogeratplumbee** [comment]
Awesomesauce man! Exactly what I was asking for! Kudos!
<img width="1440" alt="screen shot 2016-04-02 at 09 00 16" src="https://cloud.githubusercontent.com/assets/5928367/14225199/ef07c750-f8b1-11e5-9989-f9d656da7d33.png">

**Comment by VISTALL** [comment]
Hi. Thanks big for answer.  Today i fixed **0 ms**. You can update after 30-60 mins.

> > You need update Consulo Plugin for Unity(https://github.com/consulo/UnityEditorConsuloPlugin) & Unity Plugin for Consulo
