### ISSUE TITLE
Shortcut for go to/generate unit test from class

### ISSUE THREAD

**Issue by UCh** [consulo/consulo-unity3d#68]
On other platforms (for example Java or Actionscript) it's possible to open a test from a class or the other way around with a shortcut. In case that there is no test you can create a test template from the same shortcut. It is possible do that? I know that folder structure in Unity is a bit loose but maybe configuring the path pattern.

**Comment by VISTALL** [comment]
Goto test is not implemented by NUnit plugin

**Comment by VISTALL** [comment]
I move this issue to correct repository

**Comment by VISTALL** [comment]
fixed
