### ISSUE TITLE
Unity namespace generation

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-unity3d#69]
Current - **Assets** is root, and all namespaces calculated by relative path.
-  **Editor** scripts need calculate namespace from last **Editor** parent directory ?
- But what about **first-script** modules ? They have base dir **Scripts** ?

**Comment by winxalex** [comment]
There is no base directory "Editor" or "Scripts". You can have many of them in hierarchy and unity find all of them. So make the namespace logic from the last Editor or Scripts directory without them.

**Comment by VISTALL** [comment]
I did't say about single directory. Assembly-CSharp-Editor - eat all scripts inside any **Editor** directory.

Ok - i will try implement this

**Comment by VISTALL** [comment]
Oh. I was wrong about **Scripts**.

Paths for **first-pass** is

``` java

        String[] paths = new String[]{
                "Assets/Standard Assets",
                "Assets/Pro Standard Assets",
                "Assets/Plugins"
        };
```

**Comment by VISTALL** [comment]
fixed

**Comment by winxalex** [comment]
:+1:

**Comment by WeslomPo** [comment]
I'm thinking about make issue about that namespace issue too, but you fix that by yourself ^__^

**Comment by rogeratplumbee** [comment]
It is possible to add the "Scripts" path logic in the same way that the "Editor" one? Something like if Consulo find the folder name "Scripts" then start the namespace from there instead of from "Assets". A lot of us use thins convention:

-Assets
  |_Prefabs
  |_Materials
  |_Scenes
  |_Scripts
.
.
.
  |_Module
    |_Prefabs
    |_Materials
    |_Scenes
    |_Scripts
...

**Comment by VISTALL** [comment]
yeah - added
