### ISSUE TITLE
UnityEngine.UI not found

### ISSUE THREAD

**Issue by GromHoll** [consulo/consulo-unity3d#7]
UnityEngine.UI library (for 4.6 Unity3d version) not found for imported project.
It was fixed by manual added this library to project module by full path.

![error](https://cloud.githubusercontent.com/assets/1131266/6431349/f4e15770-c03d-11e4-94d0-ee50c07fe7cc.png)
![aftermanualadding](https://cloud.githubusercontent.com/assets/1131266/6431347/f48148d0-c03d-11e4-9b09-6120af0819a5.png)

**Comment by VISTALL** [comment]
4.6.3? Unity

**Comment by GromHoll** [comment]
Nope, 4.6.1f1

**Comment by VISTALL** [comment]
Try to update Unity3D plugin. I think it similar as https://github.com/consulo/consulo-unity3d/issues/6

**Comment by VISTALL** [comment]
any news?

**Comment by GromHoll** [comment]
Yes, It's work.
Tnaks for IDE.

**Comment by ernestp** [comment]
Same error happens with Unity 5.1.2

**Comment by VISTALL** [comment]
Please create new issue - this issue obsolete. Please say version of unity plugin.

I will check it - maybe today

**Comment by VISTALL** [comment]
And please say your OS

**Comment by ernestp** [comment]
After update Unity plugin and reimport there is no problem with UI library.

**Comment by VISTALL** [comment]
Okey thanks for notify
