### ISSUE TITLE
Adding a using broke preprocessor instructions in using block

### ISSUE THREAD

**Issue by WeslomPo** [consulo/consulo-unity3d#70]
Hi.

If add some preprocessor instructions in using, after add something that need a brand new using it broke all beauty. That was annoying, it happens silently (how it should be), and when you building game for standalone it makes you to fix using again and again. :(

I make some video for you.

http://take.ms/gj020

**Comment by VISTALL** [comment]
Please update to last builds. As i see - you have old preprocessor.

![image](http://klikr.org/b325a5ecf2c6e28835ffd25b0e67.gif)

It add using inside block - its a bug. But it not remove it
