### ISSUE TITLE
Find Definition or Even local variables not working in this kind of structure

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#71]
<img width="1009" alt="screen shot 2016-04-22 at 9 45 52 am" src="https://cloud.githubusercontent.com/assets/689092/14735121/6a074a6c-086f-11e6-9ec6-12b3e61f3012.png">
<img width="742" alt="screen shot 2016-04-22 at 9 50 01 am" src="https://cloud.githubusercontent.com/assets/689092/14735196/ddc11e10-086f-11e6-8066-b19081911042.png">
<img width="833" alt="screen shot 2016-04-22 at 9 51 31 am" src="https://cloud.githubusercontent.com/assets/689092/14735197/df25b2c0-086f-11e6-84a0-634f47e69781.png">
ThirdPersonAnimator:ThirdPersonMotor where quickStop is defined

**Comment by winxalex** [comment]
In Unity folders not need to be the same with namespace

**Comment by VISTALL** [comment]
Looks like you changed project structure. Try invoke - "Re-import Unity project" (in context menu on right click at project dir)

**Comment by winxalex** [comment]
Yes that fix the issue as consulo made reindexing, I didn't check manual project structure. I just imported new packages in Unity. Is there are way consulo to notice that and auto reindex?

**Comment by VISTALL** [comment]
That need check all files. Its a very heavy task. For now - only one way is call it via action

https://github.com/consulo/consulo-unity3d/issues/45

**Comment by winxalex** [comment]
think you need to save size of .sln,.project files and if they change u reindex :)

**Comment by VISTALL** [comment]
Consulo not use sln project files

**Comment by winxalex** [comment]
Just file size. I wasn't thinking of actually reimport.
