### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SillentAssembly** [consulo/consulo-unity3d#72]
Pressing ctrl-space won't show the documentation for anything (c# or unity code). Is there a way to fix this?

**Comment by VISTALL** [comment]
Unit didn't contains .NET documentation, but contains Unity docs (ctrl + q)

![](http://klikr.org/e5665f37af878653639d3892a289.png)

**Comment by VISTALL** [comment]
And documentation is not showing while completion for default, need enabled it 

![image](https://cloud.githubusercontent.com/assets/542934/14852717/c8cdd208-0c90-11e6-9a8e-60730daabc23.png)

(last option)

**Comment by SillentAssembly** [comment]
Sorry my bad. It works on windows but not Linux. ctrl-space and ctrl-q doesn't work on linux. Windows ok. In linux i saw that unity was missing documentation and i copied from windows but still doesn't work.

**Comment by VISTALL** [comment]
what you copied?

**Comment by SillentAssembly** [comment]
documentation folder at /opt/Unity/Editor/Data/Documentation/

**Comment by VISTALL** [comment]
Consulo used .xml files around .dll files. I will check Linux distribution, maybe it have some change

**Comment by VISTALL** [comment]
There no .xml files in Linux distribution.

no file

```
unity\Editor\Data\Managed\UnityEditor.xml
```

**Comment by SillentAssembly** [comment]
True no files. If i copy from windows should work?

**Comment by VISTALL** [comment]
Must. If not - it's a bug and i will fix it. Test it:)

**Comment by VISTALL** [comment]
Copy UnityEngine.xml too

**Comment by VISTALL** [comment]
Please report me - if documentation is work

**Comment by SillentAssembly** [comment]
copied both. Works OK. Ty :) So basically idiots from Unity fail again (cause in windows RuntimePlatform.LinuxEditor poduces error but in linux works ok... :p)
