### ISSUE TITLE
Red caret see image

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#74]
<img width="672" alt="screen shot 2016-05-09 at 2 04 09 pm" src="https://cloud.githubusercontent.com/assets/689092/15112527/29113b0c-15ef-11e6-82e1-15c87e9a318c.png">

**Comment by VISTALL** [comment]
Hi. It's a part of known issue https://github.com/consulo/consulo-csharp/issues/307

Sorry
