### ISSUE TITLE
I can't put breakpoints anymore

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#75]
updated to 1333.
when I engage sortcut it says "can't find declaraton to go"
I restart app and reload unity project.

**Comment by VISTALL** [comment]
Can you show screenshot - or something. I currently playing with debugger - and all work's.

**Comment by VISTALL** [comment]
And give me log (About -> Show log in Reveal)

**Comment by winxalex** [comment]
<img width="1436" alt="screen shot 2016-05-10 at 5 02 39 pm" src="https://cloud.githubusercontent.com/assets/689092/15151406/4226e82a-16d1-11e6-9552-4f4273ef2c96.png">
<img width="1437" alt="screen shot 2016-05-10 at 5 04 45 pm" src="https://cloud.githubusercontent.com/assets/689092/15151432/59cee950-16d1-11e6-8b46-ee23ad575125.png">

**Comment by winxalex** [comment]
Logs

[Archive.zip](https://github.com/consulo/consulo-unity3d/files/257467/Archive.zip)

**Comment by winxalex** [comment]
<img width="1436" alt="screen shot 2016-05-10 at 5 09 01 pm" src="https://cloud.githubusercontent.com/assets/689092/15151574/f3b80bfa-16d1-11e6-814b-d6dad9621dd1.png">

**Comment by VISTALL** [comment]
No problems in log related to breakpoints. I will test on mac

**Comment by winxalex** [comment]
u saw the menu? They are disabled?

**Comment by VISTALL** [comment]
For unity it will be always disabled, due it not used default Run system (it's attach not run)

**Comment by VISTALL** [comment]
Hm. No problems 

![](http://klikr.org/07dd6c1d7c5adac7f91d253bb855.png)

You have update plugins ?(C# + .NET)

**Comment by winxalex** [comment]
So that was the problem. So every release comes with the old pluggins right? Need update? Thx

**Comment by winxalex** [comment]
Now they are enabled in the Menu. :)

**Comment by VISTALL** [comment]
Sometimes. Few days ago i changed API in Consulo. And it required plugin change, due i made incompatible change in debugger API.

Sorry
