### ISSUE TITLE
Default keyboard map web page is getting 404

### ISSUE THREAD

**Issue by cupsster** [consulo/consulo-unity3d#76]
Consulo launcher > Actions > Docs and How-Tos > Default Keymap Reference

It launches this url:
http://must-be.org/consulo/IntelliJIDEA_ReferenceCard.pdf
From which I get 404.
[ERROR]
HTTP Status 404 - /consulo/IntelliJIDEA_ReferenceCard.pdf

type Status report

message /consulo/IntelliJIDEA_ReferenceCard.pdf

description The requested resource is not available.

Apache Tomcat/7.0.61
[/ERROR]

**Comment by VISTALL** [comment]
Hi. It's legacy from IDEA (they don't provide this document by free license)

You can read it here https://resources.jetbrains.com/assets/products/intellij-idea/IntelliJIDEA_ReferenceCard.pdf

**Comment by cupsster** [comment]
TY, handy resource, I suppose you can update URL to point to this file you linked above. :)

**Comment by VISTALL** [comment]
Consulo is not related to IntelliJ IDEA, i can't do that:)

**Comment by VISTALL** [comment]
After some fix - it open page at consulo repo. But wiki is empty for now
