### ISSUE TITLE
Debbuger still missing variables

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#78]
<img width="1440" alt="screen shot 2016-07-14 at 7 56 20 pm" src="https://cloud.githubusercontent.com/assets/689092/16877555/000d3abe-4aa9-11e6-850c-3c128033c787.png">

**Comment by VISTALL** [comment]
Hi. Sorry for delay, but it's not simple issue, i can't reproduce it without simple example

**Comment by winxalex** [comment]
Don't how to create... What should I do. It is inside the Modal Dialog as you can see.???

**Comment by VISTALL** [comment]
I saw. Try minimize code inside method. 

I have no problem with local var evaluation

![](http://klikr.org/9bae00baf934e7554713dbadbe0b.png)

**Comment by winxalex** [comment]
It is in Modal Dialog might have been on other thread. its complex . See behaviourOrdInx is shown and logicCOmponentID not even not listed

**Comment by VISTALL** [comment]
I close this issue. If you repeat it again. Create new with new description.

Thanks
