### ISSUE TITLE
Can't recognize field Graph.edges (No compiler errors)

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#79]
<img width="1440" alt="screen shot 2016-07-15 at 5 37 05 pm" src="https://cloud.githubusercontent.com/assets/689092/16879903/f2131672-4ab2-11e6-8ed3-aadd803984b3.png">
<img width="1440" alt="screen shot 2016-07-15 at 5 37 29 pm" src="https://cloud.githubusercontent.com/assets/689092/16879911/fc750c10-4ab2-11e6-852b-697b0dea2858.png">

**Comment by VISTALL** [comment]
When you invoke completion after dot **m_Graph.** that you saw ?  Me interest what you can choose

**Comment by winxalex** [comment]
UnityEditor.Graphs namespace

```
public abstract class GraphGUI : UnityEngine.ScriptableObject

UnityEditor.Graphs.Graph m_Graph;

        UnityEditor.EditorWindow m_Host;

        UnityEditor.Graphs.IEdgeGUI m_EdgeGUI;
```

completion doesn't show them
<img width="1440" alt="screen shot 2016-07-18 at 2 32 18 pm" src="https://cloud.githubusercontent.com/assets/689092/16914848/b73c85b2-4cf4-11e6-91b9-3cda7cc7c834.png">

**Comment by VISTALL** [comment]
Looks like its a problem with GraphGUI type.

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2016-07-18 at 2 29 49 pm" src="https://cloud.githubusercontent.com/assets/689092/16919413/d89077f4-4d09-11e6-818a-ff1b0c107701.png">

**Comment by VISTALL** [comment]
Fixed by https://github.com/consulo/consulo-dotnet/commit/b1c5994d6ecb96a53ad00551def9ba1b7b1a3759

Try after .NET API plugin update
