### ISSUE TITLE
Can't implicit convert [] to out [] error

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#80]
<img width="1440" alt="screen shot 2016-07-18 at 2 42 12 pm" src="https://cloud.githubusercontent.com/assets/689092/16915048/d98de5a6-4cf5-11e6-8a47-7a6c9edf6c76.png">
<img width="1440" alt="screen shot 2016-07-18 at 2 41 32 pm" src="https://cloud.githubusercontent.com/assets/689092/16915053/e1a7dfd0-4cf5-11e6-89db-576170f3ac3c.png">

**Comment by VISTALL** [comment]
Strange. Sorry - but without example i can't fix it

**Comment by winxalex** [comment]
Write code from the screens

```
public static void MyFunc(out GUIContent[] displayOptions){
List<GUIContent> guiContentList=new List<GUIContent>();
displayOptions=guiContetentList.ToArray();
}
```

**Comment by VISTALL** [comment]
Hm, reproduced

**Comment by VISTALL** [comment]
Simple example

``` csharp
namespace AA
{
    public static class Test
    {
        public static void test(out string[] t)
        {
            string[] otherParams = new string[0];

            t = otherParams;
        }
    }
}
```
