### ISSUE TITLE
Unity Debugging usually doesn't work

### ISSUE THREAD

**Issue by ghost** [consulo/consulo-unity3d#83]
Attaching the debugger to Unity seems to succeed, but breakpoints do not work.  I have seen breakpoints work a single time, but since then nothing I do will cause them to work again.

**Comment by VISTALL** [comment]
Hi. Can you say your OS, Unity3D info?

And maybe create some gif with a problem?

Thanks

**Comment by ghost** [comment]
OS X El Capitan, Unity 5.3 and 5.4.  I'm not sure if a GIF would be super useful, the steps are simply:

Add a break point
Press Attach to Unity and select it in the list
Press play on Unity

The Consulo console will say Successfully Attached to Unity, but the breakpoints won't fire.  Pressing pause in the debugger will pause Unity however, so it definitely seems attached.
This is the same on three different computers of mine.

**Comment by VISTALL** [comment]
Left icon is like on this image?

![](http://klikr.org/74d7e3cbfcef7f55d1f1c22cc5c9.png)

Can you attach *_idea.log_ (About -> show logs in reveal)

**Comment by ghost** [comment]
Sorry the GIF is a little blurry:
![consulo attach bug](https://cloud.githubusercontent.com/assets/1824057/17562195/fb44b76c-5ee6-11e6-847c-271d35dfd735.gif)

[idea.log.txt](https://github.com/consulo/consulo-unity3d/files/411632/idea.log.txt)

Every once in awhile the breakpoints will work just fine, but when I quit and start Unity or quit and start Consulo again they will stop working again.  I haven't been able to figure out the steps for it to always work.

**Comment by VISTALL** [comment]
You have restarted attach ? after reopen (consulo or unity)

**Comment by ghost** [comment]
Yeah, multiple times

**Comment by VISTALL** [comment]
Strange. Can you create simple project -try on it, and when give me it(if bug exists)?

**Comment by ghost** [comment]
Ok, looking more into this, breakpoints actually do work in other methods in the class, I was just unlucky with the ones I picked.
There are some specific methods that won't trigger the breakpoint and I can't understand why.  They are definitely being called.
I made a small project but that doesn't seem to have the issue.
Are there any limitations on what methods you can break on?  These specific methods would have very large stacks if that has anything to do with it.

**Comment by VISTALL** [comment]
There no limits. But some statements have own breakpoint logic (async, yield, lambdas, etc)

**Comment by ghost** [comment]
I just tested the same breakpoints in MonoDevelop and they work there.  It is a series of nested coroutines, however I did the same thing in my test project and it's not an issue there.  Any ideas?  I would love to use Consulo to debug :)

**Comment by VISTALL** [comment]
Consulo have own logic for debugging. If you found how repeat, i will fix it

Sorry

**Comment by ghost** [comment]
Ok, for now I will use MonoDevelop.  I will reopen if I can figure out a repro.  Thanks for looking!
