### ISSUE TITLE
Debugging - Code Selection Debug Tooltips are not showing up

### ISSUE THREAD

**Issue by TomCoursow** [consulo/consulo-unity3d#88]
I tried to turn on show tooltip on code selection in the ide settings and so on but debug toolstips are not working

Hapened on a Unity3D Project.

**Comment by VISTALL** [comment]
Will check maybe after few days

**Comment by VISTALL** [comment]
$moveto consulo-dotnet

**Comment by VISTALL** [comment]
Sorry - i can't check it. Busy at work, and 2.0 release take my free time

**Comment by VISTALL** [comment]
fixed but only in second version
