### ISSUE TITLE
UnityEngine.UI.dll

### ISSUE THREAD

**Issue by robert-wallis** [consulo/consulo-unity3d#9]
Please import `UnityEngine.UI.dll` into external references so we can do this:

```
using UnityEngine.UI;
using UnityEngine.EventSystems;
```

It's in the `Assembly-CSharp.csproj` file:

```
 <Reference Include="UnityEngine.UI">
 <HintPath>/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll</HintPath>
 </Reference>
```

Thanks!  Great work!

**Comment by robert-wallis** [comment]
I see it's already being imported here:
https://github.com/consulo/consulo-unity3d/blob/799be689c8d3f1ac4887f0f1e5e179fe7f355d7c/src/org/mustbe/consulo/unity3d/projectImport/Unity3dProjectImportBuilder.java#L336

But for some reason it must not be detecting version 5.0.0 :(

**Comment by VISTALL** [comment]
On MacOS - sdk version is 0.0, due i dont known how get it. U need manually add it(via dependencies->add->standard library->UnityEngine.UI)

**Comment by VISTALL** [comment]
I found way - how get version on MacOS. Maybe today i will fix this issue

**Comment by VISTALL** [comment]
I think now - all good (after this fix https://github.com/consulo/consulo-unity3d/commit/5a2600617cd9b59c774d8eb600fc044b6f9f36ab)

Try update plugin - and then import project again

**Comment by robert-wallis** [comment]
Thanks for checking this out. 
- I updated the Unity3D to version 853, and re-imported the project, but that didn't work.
- Then I tried to go to ProjectSettings->Modules->MyGame->Dependencies and add via the Standard Library, but it didn't have the UnityEngine.UI library.
- So then I tried adding the DLL manually from the path mentioned above in the VS project file.  And it added the DLL in the "External Libraries" section of the project, and I can even look inside and see classes like "Text" are available, however I still get errors inside Consulo (but not in Unity).
  ![screen shot 2015-03-23 at 6 15 16 pm](https://cloud.githubusercontent.com/assets/145938/6793916/a212c590-d188-11e4-98bb-107368c41a73.png)

**Comment by VISTALL** [comment]
Hm. They again moved UI library(maybe)

**Comment by VISTALL** [comment]
Or me made mistake

**Comment by VISTALL** [comment]
Wait pls some time and update to 854 plugin, and try again

**Comment by VISTALL** [comment]
Now u can update plugin

**Comment by VISTALL** [comment]
And make pls sceen of Bundles inside project structure

**Comment by robert-wallis** [comment]
Thank you!  It works now.  I'm not sure where to find "Bundles" but here's a screenshot of the dependencies in Standard Library now:
![screen shot 2015-03-23 at 9 14 52 pm](https://cloud.githubusercontent.com/assets/145938/6795705/db3c0f16-d1a1-11e4-9650-cc55cfc766a5.png)

Interestingly, when I re-imported the project just now it recognized Unity 5.0.0, even though the dependencies says the version is a different number.
![screen shot 2015-03-23 at 9 17 12 pm](https://cloud.githubusercontent.com/assets/145938/6795709/ff485bf8-d1a1-11e4-88e2-b8e02ab9af57.png)

Thank you for fixing the bug so quickly!

**Comment by VISTALL** [comment]
I said about this window:

![](http://klikr.org/99426c321e15ef8f035ee6dcf830.png)

But u already answered, your Unity version is 5.0.0 - but few days ago plugin would say 0.0.0

Thanks for bug :smile:
