### ISSUE TITLE
GetValue not recognized from SystemReflection

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#93]
<img width="1440" alt="screen shot 2016-11-28 at 2 53 39 pm" src="https://cloud.githubusercontent.com/assets/689092/20670732/9705846c-b57a-11e6-8a36-1372a5413ece.png">

**Comment by VISTALL** [comment]
If you call completion at **GetValue** what you see?

**Comment by winxalex** [comment]
Generate>Copyrights :D  LOL

**Comment by VISTALL** [comment]
$moveto consulo-csharp
