### ISSUE TITLE
Generics funciton not recognized

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#94]
<img width="1440" alt="screen shot 2016-11-28 at 2 56 30 pm" src="https://cloud.githubusercontent.com/assets/689092/20670806/f8cb5f00-b57a-11e6-9590-1dc1dcc91c80.png">
<img width="1440" alt="screen shot 2016-11-28 at 2 56 46 pm" src="https://cloud.githubusercontent.com/assets/689092/20670807/f8d0bdd8-b57a-11e6-8314-9cfe66e6a069.png">

**Comment by VISTALL** [comment]
$moveto consulo-csharp
