### ISSUE TITLE
Double click on error message in Unity console gets you to "+1" line

### ISSUE THREAD

**Issue by moozgoos** [consulo/consulo-unity3d#96]
Unity 4.7.2
Consulo 1.0 #1401
Os X Sierra

After clicking on error message in Unity, Consulo gets you under corresponding line. I.e. if you have error in line 11 (and Unity says it's line 11), Consulo gets you to line 12.

**Comment by moozgoos** [comment]
Script attached here:
https://github.com/minhdu/UnityConsulo/blob/master/Assets/UnityConsulo/UnityConsulo.cs
seems to be working better than your plugin, at least for Unity 4.7.2 (except "Enable/Disable menu" code, wich i commented").

**Comment by VISTALL** [comment]
Hi. I will rework Consulo start from Unity when  arrive home(I am in another country at this moment).

**Comment by moozgoos** [comment]
Consulo is so great, i will wait for patch :+1:

**Comment by VISTALL** [comment]
Hi. This problem fixed in Consulo 2 (downloads will be open after month maybe or closer)
