### ISSUE TITLE
Still no focus to Consulo window after double click on script in Unity window [OS X]

### ISSUE THREAD

**Issue by moozgoos** [consulo/consulo-unity3d#97]
Unity 4.7.2f1
Consulo 1.0 #1401
Os X Sierra

Consulo still doesn't get focus after double click on script in Unity. Consulo opens corresponding script, window getting focus for very short time (like 1 ms), than focus returns to Unity.

**Comment by moozgoos** [comment]
Script attached here:
https://github.com/minhdu/UnityConsulo/blob/master/Assets/UnityConsulo/UnityConsulo.cs
seems to be working better than your plugin, at least for Unity 4.7.2 (except "Enable/Disable menu" code, wich i commented").

**Comment by VISTALL** [comment]
Hi. Known issue. Duplicate https://github.com/consulo/consulo-unity3d/issues/97

Working on it.

Thanks
