### ISSUE TITLE
Add some information when Consulo don't start due startup error 'platform dir is not found'

### ISSUE THREAD

**Issue by rehv** [consulo/consulo-unity3d#99]
Hi! I'm sorry if this is a dumb problem, but I was trying to adapt [these instructions](https://github.com/consulo/consulo-unity3d/wiki/1.-Setup-and-Usage)  to integrate Consulo 2.0 with Unity 4.7.2f1. 

The problem is, if you just set the External Script Editor and command lines as suggested in the wiki, Consulo 2.0 will throw an error: "'platform' directory not found" when double clicking any C# script.

I'm not sure if this is intended since 2.0, but to 'fix' this, I've discovered that you'll also need to install the Unity Editor Consulo Plugin to your project. So, just for peace of mind, I'm informing it here just in case this isn't intended.

Thanks!

**Comment by VISTALL** [comment]
Hi. It's ok. Can you install this plugin https://github.com/consulo/UnityEditorConsuloPlugin 

And try again

**Comment by rehv** [comment]
No problem. As I've said, that's the solution I've found :) With it included in the project, there's no problem at all.

Thanks!

**Comment by VISTALL** [comment]
Oh :-)

Yeah plugin is required for correct running Consulo from Unity (there no good way provide some information for this moment).

I will think about this.

Thanks you

**Comment by VISTALL** [comment]
That doc was outdated - fixed

**Comment by FullStackForger** [comment]
Well... not fixed I think. I just got latest version of consulo. Assigned it as external tools editor from Unity and getting the same error. Any idea what is the problem. It seems to work on MacOS

**Comment by VISTALL** [comment]
You need Consulo plugin for Unity (https://github.com/consulo/UnityEditorConsuloPlugin)

**Comment by VISTALL** [comment]
In last version of Consulo, you will see message.

>> 'platform' directory is not found. Visit https://consulo.io/trouble.html

And it will redirect to https://github.com/consulo/consulo/wiki/Frequently-Asked-Questions with answer for fix

**Comment by pecheny** [comment]
For some reasons the plugin doesn't work for me. 
So i use folowing workaround (For Windows users):
create consulo.cmd at the Consulo location:
```
%~d0
cd %~dp0
consulo64.exe %1 %2 %3
```
And use it instead of consulo64.exe in Unity's 'External Tools' dialog.

**Comment by VISTALL** [comment]
Hi 

> For some reasons the plugin doesn't work for me.
can you say your Unity version? 5.6 had troubles with plugin - but i fixed it.  But you need last version of Consulo & plugins

Thanks

**Comment by pecheny** [comment]
Hi! the reason why it "Doesn't work for me" is not in plugin itself but rather in the way it works. I guess it captures and overrides unity's call to external editor.
I also use a plugin  [(UberLogger)](https://github.com/bbbscarter/UberLogger) which calls to external editor through Unity API like
```
UnityEditorInternal.InternalEditorUtility.OpenFileAtLineExternal(filename, frame.LineNumber)
```
It can be handy to navigate through stacktrace. 
Seems that Consulo plugin doesn't affect to this API call.

However it would be nice if Consulo will able to start outside it's own dir like 
```
c:\somepath\Consulo\consulo64.exe
```
as well as Idea can.

**Comment by VISTALL** [comment]
I extracted issue https://github.com/consulo/consulo-unity3d/issues/113

Even if I add option for run as *.exe file - Consulo can't import new Unity project.

Our plugin - helps importing project into Consulo, and provide more faster file opening (and other features, like console log)

Thanks

**Comment by pecheny** [comment]
Thanks!
I guess it may be titled more general, like Compatibility with UnityEditorInternal.InternalEditorUtility.OpenFileAtLineExternal API.
The note wasn't against the plugin, it works fine for other purposes for me.
On the other hand ability to call .exe by full path can be useful for other cases (Without using unity at all).
For example, JetBrains'd done diff tool very well and it can be used as dedicated tool [Manual](https://www.jetbrains.com/help/idea/running-intellij-idea-as-a-diff-or-merge-command-line-tool.html)
I didn't try it with Consulo, but i guess inability to launch outside it's own dir can be one of obstacles to do such thing.
